/// @file
/// @brief   mc.ear.select~: pick channels of a multichannel signal by number,
///          to route the tracks of an ADM file (as reported by ear.adm) to the
///          renderer that handles them.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_mc.h"

#include <algorithm>

using namespace earmax;

class mc_ear_select_tilde : public object<mc_ear_select_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Select channels of a multichannel signal by number (1-based), in the order given: "
                     "'tracks 7 8 9 10' outputs input channels 7 to 10 as output channels 1 to 4. The arguments "
                     "set the initial selection. ear.adm reports the tracks of each rendering item in this form, so "
                     "mc.sfplay~ into mc.ear.select~ into a renderer routes a file's objects, bed or scene. The "
                     "output channel count follows the selection when the audio is restarted; a selected channel "
                     "the input does not have is silent." };
    MIN_TAGS{ "spatial audio, ADM, audio, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "ear.adm, mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    std::vector<long> m_tracks;    // 0-based input channels, one per output channel

public:
    inlet<> in_main{ this, "(multichannelsignal) input; (tracks) the channels to select" };
    outlet<> out_main{ this, "(multichannelsignal) the selected channels", "multichannelsignal" };

    mc_ear_select_tilde(const atoms& args = {})
    {
        if (!set_tracks(args) || m_tracks.empty()) {
            m_tracks = { 0 };
        }
    }

    message<> tracks{ this, "tracks",
        "Select input channels by number (1-based): 'tracks 7 8 9 10'. Takes effect on the output channel count when the audio is restarted.",
        MIN_FUNCTION {
            if (!set_tracks(args)) {
                cerr << "tracks needs channel numbers (1-based)" << endl;
            }
            return {};
        } };

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_select_tilde>(c);
            return {};
        } };

    long mc_output_channels(long) const
    {
        return static_cast<long>(std::max<size_t>(1, m_tracks.size()));
    }

    long mc_input_changed(long, long)
    {
        return 0;
    }

    void operator()(audio_bundle input, audio_bundle output)
    {
        const long frames = input.frame_count();
        const long outs = output.channel_count();
        for (long ch = 0; ch < outs; ++ch) {
            double* out = output.samples(ch);
            const long source = ch < static_cast<long>(m_tracks.size()) ? m_tracks[static_cast<size_t>(ch)] : -1;
            if (source >= 0 && source < input.channel_count()) {
                const double* in = input.samples(source);
                std::copy(in, in + frames, out);
            }
            else {
                std::fill(out, out + frames, 0.0);
            }
        }
    }

    const std::vector<long>& selected() const
    {
        return m_tracks;
    }

private:
    bool set_tracks(const atoms& args)
    {
        std::vector<long> tracks;
        for (const auto& a : args) {
            if (!atom_is_numeric(a)) {
                return false;
            }
            const long n = static_cast<long>(static_cast<double>(a));
            if (n < 1) {
                return false;
            }
            tracks.push_back(n - 1);
        }
        if (tracks.empty()) {
            return false;
        }
        m_tracks = std::move(tracks);
        return true;
    }
};
