/// @file
/// @brief   mc.ear.select~: pick channels of a multichannel signal by number,
///          to route the tracks of an ADM file (as reported by ear.adm) to the
///          renderer that handles them.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_mc.h"

#include <algorithm>
#include <atomic>
#include <cmath>
#include <mutex>

using namespace earmax;

class mc_ear_select_tilde : public object<mc_ear_select_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Select channels of a multichannel signal by number (1-based), in the order given: "
                     "'tracks 7 8 9 10' outputs input channels 7 to 10 as output channels 1 to 4. The arguments "
                     "set the initial selection. ear.adm reports the tracks of each rendering item in this form, so "
                     "mc.sfplay~ into mc.ear.select~ into a renderer routes a file's objects, bed or scene. The "
                     "output channel count follows the selection when the audio is restarted; a selected channel "
                     "the input does not have is silent." };
    MIN_TAGS{ "spatial audio, ADM, audio, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "ear.adm, mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    static constexpr size_t k_max_tracks = 1024;    // Max's multichannel limit

    // The message thread owns m_tracks (0-based input channels, one per
    // output channel) under m_mutex. The audio thread keeps its own copy,
    // allocated once at the full capacity: when a change is flagged it
    // try_locks the mutex and copies the selection (never blocking and
    // never allocating or freeing on the audio thread), otherwise it keeps
    // routing with the previous copy until the next vector.
    mutable std::mutex m_mutex;
    std::vector<long> m_tracks{ 0 };
    std::vector<long> m_audio_tracks;
    std::atomic<bool> m_changed{ false };

    /// the audio thread's copy of the selection, refreshed when it changed
    const std::vector<long>& audio_tracks()
    {
        if (m_changed.load(std::memory_order_acquire) && m_mutex.try_lock()) {
            const size_t n = std::min(m_tracks.size(), m_audio_tracks.capacity());
            m_audio_tracks.resize(n);    // within the reserved capacity: no allocation
            std::copy(m_tracks.begin(), m_tracks.begin() + static_cast<long>(n), m_audio_tracks.begin());
            m_changed.store(false, std::memory_order_release);
            m_mutex.unlock();
        }
        return m_audio_tracks;
    }

public:
    inlet<> in_main{ this, "(multichannelsignal) input; (tracks) the channels to select" };
    outlet<> out_main{ this, "(multichannelsignal) the selected channels", "multichannelsignal" };

    mc_ear_select_tilde(const atoms& args = {})
    {
        m_audio_tracks.reserve(k_max_tracks);
        m_audio_tracks = m_tracks;
        set_tracks(args);    // the default selection (channel 1) stays when there are no arguments
    }

    message<> tracks{ this, "tracks",
        "Select input channels by number (1-based): 'tracks 7 8 9 10'. Takes effect on the output channel count when the audio is restarted.",
        MIN_FUNCTION {
            if (!set_tracks(args)) {
                cerr << "tracks needs channel numbers (1 to " << k_max_tracks << ")" << endl;
            }
            return {};
        } };

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_select_tilde>(c);
            return {};
        } };

    long mc_output_channels(long) const
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        return static_cast<long>(std::max<size_t>(1, m_tracks.size()));
    }

    long mc_input_changed(long, long)
    {
        return 0;
    }

    void operator()(audio_bundle input, audio_bundle output)
    {
        const std::vector<long>& tracks = audio_tracks();
        const long frames = input.frame_count();
        const long outs = output.channel_count();
        for (long ch = 0; ch < outs; ++ch) {
            double* out = output.samples(ch);
            const long source = ch < static_cast<long>(tracks.size()) ? tracks[static_cast<size_t>(ch)] : -1;
            if (source >= 0 && source < input.channel_count()) {
                const double* in = input.samples(source);
                std::copy(in, in + frames, out);
            }
            else {
                std::fill(out, out + frames, 0.0);
            }
        }
    }

    std::vector<long> selected() const
    {
        std::lock_guard<std::mutex> lock(m_mutex);
        return m_tracks;
    }

private:
    bool set_tracks(const atoms& args)
    {
        if (args.size() > k_max_tracks) {
            return false;    // more outputs than the audio thread's copy can hold
        }
        std::vector<long> tracks;
        for (const auto& a : args) {
            if (!atom_is_numeric(a)) {
                return false;
            }
            // validated as a double first: a NaN, an infinity or a huge value
            // must not reach the conversion to long
            const double value = static_cast<double>(a);
            if (!std::isfinite(value) || value < 1.0 || value > static_cast<double>(k_max_tracks)) {
                return false;
            }
            tracks.push_back(static_cast<long>(value) - 1);
        }
        if (tracks.empty()) {
            return false;
        }
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            m_tracks.swap(tracks);    // the old list is freed here, on the message thread
        }
        m_changed.store(true, std::memory_order_release);
        return true;
    }
};
