/// @file
/// @brief   mc.ear.hoa~: decode an ambisonic (ADM HOA) scene to a multichannel
///          loudspeaker signal with libear's BS.2127 HOA decoder.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_dsp.h"
#include "../shared/ear_max_mc.h"

#include <cmath>

using namespace earmax;

class mc_ear_hoa_tilde : public object<mc_ear_hoa_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Decode an ambisonic scene (ADM HOA) to loudspeaker signals with libear (ITU-R BS.2127), "
                     "with multichannel signal input and output. The input carries the ambisonic components in "
                     "ACN order (W Y Z X ... for first order); the output has one channel per loudspeaker of the "
                     "BS.2051 layout given as argument. The decoder is the EAR's AllRAD design for that layout. "
                     "Sum the output with mc.ear.objects~ and mc.ear.direct~ rendering to the same layout to mix "
                     "scene-based, object-based and channel-based audio." };
    MIN_TAGS{ "spatial audio, ADM, ambisonics, audio, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.objects~, mc.ear.direct~, ear.objects" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

    static constexpr int k_max_order = 8;

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    ear::Layout m_layout;
    std::unique_ptr<ear::GainCalculatorHOA> m_calc;
    std::vector<std::vector<float>> m_matrix;    // one vector of loudspeaker gains per ambisonic component
    std::vector<float> m_silence;
    int m_order{ 1 };
    std::string m_normalization{ "SN3D" };
    long m_reported_mismatch{ 0 };
    bus_renderer m_bus;

public:
    inlet<> in_main{ this, "(multichannelsignal) ambisonic components in ACN order; (order/normalization) metadata" };
    outlet<> out_main{ this, "(multichannelsignal) loudspeaker signals in layout channel order", "multichannelsignal" };

    mc_ear_hoa_tilde(const atoms& args = {})
    {
        const std::string name = layout_from_args(args);
        if (!apply_layout(name)) {
            apply_layout(k_default_layout);
        }
        update();
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<symbol> layout{ this, "layout", k_default_layout,
        description{ "ITU-R BS.2051 output layout name, fixed at creation (give it as argument)." },
        setter{ MIN_FUNCTION {
            const std::string name = args[0];
            if (m_calc && name != m_layout.name()) {
                cerr << "layout cannot be changed after creation; create a new object with the layout as argument" << endl;
            }
            return { symbol(m_layout.name()) };
        } } };

    attribute<int> order{ this, "order", 1,
        description{ "Ambisonic order of the input scene, 0 to 8. The input has (order+1)^2 channels in ACN order; "
                     "a new channel count takes effect when the audio is restarted." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            if (n < 0 || n > k_max_order) {
                cerr << "order must be between 0 and " << k_max_order << endl;
                n = std::max(0, std::min(n, k_max_order));
            }
            m_order = n;
            update();
            return { n };
        } } };

    attribute<symbol> normalization{ this, "normalization", "SN3D",
        description{ "Normalization of the ambisonic components: SN3D (the ADM default, also AmbiX), N3D or FuMa." },
        setter{ MIN_FUNCTION {
            const std::string name = args[0];
            if (name != "SN3D" && name != "N3D" && name != "FuMa") {
                cerr << "normalization must be SN3D, N3D or FuMa" << endl;
                return { symbol(m_normalization) };
            }
            m_normalization = name;
            update();
            return args;
        } } };

    attribute<number> ramp{ this, "ramp", 10.0,
        description{ "Gain interpolation time in milliseconds when the order or normalization changes." },
        setter{ MIN_FUNCTION {
            const double ms = std::max(0.0, static_cast<double>(args[0]));
            m_bus.set_ramp_ms(ms);
            return { ms };
        } } };

    attribute<bool> align{ this, "align", true,
        description{ "Delay the output by the latency of the object renderers (255 samples, the BS.2127 "
                     "decorrelator compensation delay) so that the scene stays time-aligned with mc.ear.objects~ "
                     "and ear.objects~ when their decorrelation is on, as the EAR reference renderer does. "
                     "Turn off for zero latency when no decorrelating renderer is mixed in." },
        setter{ MIN_FUNCTION {
            m_bus.set_delay_compensation(static_cast<bool>(args[0]));
            return args;
        } } };

    // ------------------------------------------------------------------
    // messages
    // ------------------------------------------------------------------

    message<> channels{ this, "channels", "Post the channel names of the output layout to the Max console.",
        MIN_FUNCTION {
            std::string names;
            for (const auto& name : m_layout.channelNames()) {
                names += name + " ";
            }
            cout << m_layout.name() << ": " << names << endl;
            return {};
        } };

    message<> components{ this, "components",
        "Post the ambisonic components expected on the input channels (ACN index, order and degree) to the Max console.",
        MIN_FUNCTION {
            std::string text;
            for (size_t i = 0; i < input_count(); ++i) {
                int n = 0, m = 0;
                acn_to_order_degree(static_cast<int>(i), n, m);
                text += std::to_string(i + 1) + ":(" + std::to_string(n) + "," + std::to_string(m) + ") ";
            }
            cout << "order " << m_order << " " << m_normalization << ": " << text << endl;
            return {};
        } };

    message<> dspsetup{ this, "dspsetup",
        MIN_FUNCTION {
            m_bus.configure(m_layout, input_count(), static_cast<size_t>(vector_size()), samplerate(), false, true);
            m_bus.set_delay_compensation(static_cast<bool>(align));
            for (size_t i = 0; i < m_matrix.size(); ++i) {
                m_bus.set_gains_now(i, m_matrix[i], m_silence);
            }
            return {};
        } };

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_hoa_tilde>(c);
            return {};
        } };

    // ------------------------------------------------------------------
    // multichannel plumbing (see ear_max_mc.h)
    // ------------------------------------------------------------------

    long mc_output_channels(long) const
    {
        return static_cast<long>(channel_count());
    }

    long mc_input_changed(long, long channels)
    {
        if (channels != static_cast<long>(input_count()) && channels != m_reported_mismatch) {
            m_reported_mismatch = channels;
            cerr << "input has " << channels << " channels but order " << m_order << " has " << input_count()
                 << " components; " << (channels > static_cast<long>(input_count()) ? "extra channels are ignored" : "missing components are silent")
                 << endl;
        }
        return 0;
    }

    // ------------------------------------------------------------------
    // audio
    // ------------------------------------------------------------------

    void operator()(audio_bundle input, audio_bundle output)
    {
        m_bus.process(input.samples(), static_cast<size_t>(input.channel_count()), output.samples(),
                      static_cast<size_t>(output.channel_count()), static_cast<size_t>(input.frame_count()));
    }

    // ------------------------------------------------------------------
    // state
    // ------------------------------------------------------------------

    size_t channel_count() const
    {
        return m_layout.channels().size();
    }

    /// number of ambisonic components for the current order
    size_t input_count() const
    {
        return static_cast<size_t>((m_order + 1) * (m_order + 1));
    }

    /// loudspeaker gains of ambisonic component `i` (a column of the decoding matrix)
    const std::vector<float>& gains(size_t i) const
    {
        return m_matrix[i];
    }

    int latency() const
    {
        return m_bus.latency();
    }

    /// ACN channel index to (order, degree)
    static void acn_to_order_degree(int acn, int& n, int& m)
    {
        n = static_cast<int>(std::floor(std::sqrt(static_cast<double>(acn))));
        m = acn - n * n - n;
    }

private:
    bool apply_layout(const std::string& name)
    {
        try {
            ear::Layout new_layout = ear::getLayout(name);
            m_layout = std::move(new_layout);
            m_calc = std::make_unique<ear::GainCalculatorHOA>(m_layout);
            m_silence.assign(channel_count(), 0.0f);
            return true;
        }
        catch (const std::exception& e) {
            cerr << e.what() << "; known layouts: " << layout_names_joined() << endl;
            return false;
        }
    }

    /// Recompute the decoding matrix for the current order and normalization
    /// and hand it to the bus (ramped when audio is running).
    void update()
    {
        if (!m_calc) {
            return;
        }
        const size_t n_components = input_count();
        ear::HOATypeMetadata meta;
        meta.normalization = m_normalization;
        for (size_t i = 0; i < n_components; ++i) {
            int n = 0, m = 0;
            acn_to_order_degree(static_cast<int>(i), n, m);
            meta.orders.push_back(n);
            meta.degrees.push_back(m);
        }
        std::vector<std::vector<float>> matrix(n_components, std::vector<float>(channel_count(), 0.0f));
        try {
            m_calc->calculate(meta, matrix, [this](const ear::Warning& warning) { cerr << warning.message << endl; });
        }
        catch (const std::exception& e) {
            cerr << e.what() << endl;
            return;
        }
        m_matrix = std::move(matrix);
        if (initialized()) {
            // components beyond the bus capacity (a higher order than at the
            // last dspsetup) are picked up when the audio is restarted; bus
            // inputs beyond the new component count (a lower order) are silenced
            for (size_t i = 0; i < m_bus.capacity(); ++i) {
                m_bus.set_targets(i, i < m_matrix.size() ? m_matrix[i] : m_silence, m_silence);
            }
        }
    }
};
