/// @file
/// @brief   Unit tests for ear.adm (run against the Min mock kernel): reading
///          the parity fixture generated by the EAR (test_data/), the emitted
///          renderer messages, the transport, and the capture / write round trip.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#include <chrono>
#include <cstdio>
#include <sstream>
#include <thread>

#include "../shared/ear_max_test.h"
#include "ear.adm.h"

// the mock kernel has no scheduler clock; the tests timestamp captures explicitly
namespace c74::max {
extern "C" long gettime(void)
{
    return 0;
}
}

#include "ear.adm.cpp"

using namespace earmax_test;

namespace {

const std::string k_fixture = std::string(EARMAX_TEST_DATA_DIR) + "/reference.wav";

enum outlet_index { k_objects = 0, k_direct = 1, k_hoa = 2, k_info = 3 };

std::string message_text(const c74::max::t_atom_vector& msg)
{
    std::ostringstream s;
    bool first = true;
    for (const auto& a : msg) {
        if (!first) {
            s << ' ';
        }
        first = false;
        if (a.a_type == c74::max::A_SYM) {
            s << a.a_w.w_sym->s_name;
        }
        else if (a.a_type == c74::max::A_LONG) {
            s << a.a_w.w_long;
        }
        else {
            s << a.a_w.w_float;
        }
    }
    return s.str();
}

/// every message sent from an outlet, one string per message
std::vector<std::string> messages(void* obj, int outlet)
{
    std::vector<std::string> out;
    for (const auto& msg : *c74::max::object_getoutput(obj, outlet)) {
        out.push_back(message_text(msg));
    }
    return out;
}

void clear_outputs(void* obj)
{
    for (int i = 0; i < 4; ++i) {
        c74::max::object_getoutput(obj, i)->clear();
    }
}

bool contains(const std::vector<std::string>& msgs, const std::string& text)
{
    return std::find(msgs.begin(), msgs.end(), text) != msgs.end();
}

size_t count_prefix(const std::vector<std::string>& msgs, const std::string& prefix)
{
    size_t n = 0;
    for (const auto& m : msgs) {
        if (m.compare(0, prefix.size(), prefix) == 0) {
            ++n;
        }
    }
    return n;
}

/// a short multichannel wav as mc.sfrecord~ would record it
std::string write_audio(const std::string& name, uint16_t channels, uint64_t frames)
{
    const std::string path = std::string(EARMAX_TEST_OUT_DIR) + "/" + name;
    auto writer = bw64::writeFile(path, channels, 48000, 24);
    std::vector<float> interleaved(static_cast<size_t>(frames) * channels, 0.0f);
    for (uint64_t f = 0; f < frames; ++f) {
        for (uint16_t c = 0; c < channels; ++c) {
            interleaved[static_cast<size_t>(f * channels + c)] = 0.25f * static_cast<float>(c + 1);
        }
    }
    writer->write(interleaved.data(), frames);
    return path;
}

} // namespace

SCENARIO("ear.adm reads the rendering items of an ADM file like the EAR") {
    ext_main(nullptr);

    GIVEN("an instance that read the parity fixture") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(k_fixture) });
        REQUIRE(obj.loaded());

        THEN("the file information is reported") {
            REQUIRE(obj.info().samplerate == 48000);
            REQUIRE(obj.info().channels == 12);
            REQUIRE(obj.info().frames == 4800);
            const auto info = messages(obj, k_info);
            REQUIRE(count_prefix(info, "file ") == 1);
            REQUIRE(contains(info, "programmes 1"));
            REQUIRE(contains(info, "objects 2"));
            REQUIRE(contains(info, "object 1 1 object A 3"));
            REQUIRE(contains(info, "object 2 2 object B 1"));
            REQUIRE(contains(info, "direct 6"));
            REQUIRE(contains(info, "directspeakers 4 6 bed 0+5+0 LFE1"));
            REQUIRE(contains(info, "hoa 1"));
            REQUIRE(contains(info, "scene 1 scene 1 SN3D 9 10 11 12"));
        }

        THEN("the Objects items match the reference selection (reference.json)") {
            const auto& items = obj.items();
            REQUIRE(items.objects.size() == 2);
            const auto& a = items.objects[0];
            REQUIRE(a.name == "object A");
            REQUIRE(a.track == 0);
            REQUIRE(a.blocks.size() == 3);
            REQUIRE(a.blocks[0].start == Approx(0.0));
            REQUIRE(a.blocks[0].end == Approx(1.0));
            REQUIRE(a.blocks[0].interp == Approx(0.0));    // first block of the item: no interpolation
            REQUIRE(a.blocks[0].state.azimuth == Approx(30.0));
            REQUIRE(a.blocks[1].start == Approx(1.0));
            REQUIRE(a.blocks[1].interp == Approx(0.25));    // jumpPosition with interpolationLength
            REQUIRE(a.blocks[1].state.azimuth == Approx(-30.0));
            REQUIRE(a.blocks[1].state.elevation == Approx(10.0));
            REQUIRE(a.blocks[1].state.width == Approx(20.0));
            REQUIRE(a.blocks[1].state.gain == Approx(0.5));
            REQUIRE(a.blocks[2].start == Approx(2.5));
            REQUIRE(a.blocks[2].interp == Approx(0.0));    // jumpPosition without a length
            REQUIRE(a.blocks[2].state.elevation == Approx(30.0));

            const auto& b = items.objects[1];
            REQUIRE(b.name == "object B");
            REQUIRE(b.track == 1);
            REQUIRE(b.blocks.size() == 1);
            REQUIRE(b.blocks[0].start == Approx(0.5));    // the audioObject start offsets the block
            REQUIRE(b.blocks[0].end == Approx(2.5));
            REQUIRE(b.blocks[0].state.cartesian);
            REQUIRE(b.blocks[0].state.x == Approx(0.5));
            REQUIRE(b.blocks[0].state.y == Approx(0.5));
            REQUIRE(b.blocks[0].state.diffuse == Approx(0.5));
            REQUIRE(b.blocks[0].state.screenref);
            REQUIRE(b.blocks[0].state.channellock);
            REQUIRE(b.blocks[0].state.channellock_distance == Approx(0.3));
            REQUIRE(b.blocks[0].state.divergence == Approx(0.2));
        }

        THEN("the DirectSpeakers and HOA items match the reference selection") {
            const auto& items = obj.items();
            REQUIRE(items.direct.size() == 6);
            const std::vector<std::string> labels{ "M+030", "M-030", "M+000", "LFE1", "M+110", "M-110" };
            for (size_t i = 0; i < labels.size(); ++i) {
                REQUIRE(items.direct[i].track == static_cast<int>(i + 2));
                REQUIRE(items.direct[i].labels == std::vector<std::string>{ labels[i] });
                REQUIRE(items.direct[i].name == "bed 0+5+0");
            }
            REQUIRE(items.direct[0].azimuth == Approx(30.0));
            REQUIRE(items.direct[4].azimuth == Approx(110.0));
            REQUIRE(items.direct[3].lfe);
            REQUIRE_FALSE(items.direct[0].lfe);

            REQUIRE(items.hoa.size() == 1);
            REQUIRE(items.hoa[0].tracks == std::vector<int>{ 8, 9, 10, 11 });
            REQUIRE(items.hoa[0].order == 1);
            REQUIRE(items.hoa[0].normalization == "SN3D");
            REQUIRE(items.hoa[0].complete);
            REQUIRE(items.warnings.empty());
        }

        THEN("the renderer outlets receive the track lists and the static metadata") {
            const auto objects = messages(obj, k_objects);
            REQUIRE(objects.front() == "tracks 1 2");
            const auto direct = messages(obj, k_direct);
            REQUIRE(direct.front() == "tracks 3 4 5 6 7 8");
            REQUIRE(contains(direct, "setvalue 1 speakerlabel M+030"));
            REQUIRE(contains(direct, "setvalue 1 position 30 0 1"));
            REQUIRE(contains(direct, "setvalue 4 lfe 1"));
            REQUIRE(contains(direct, "setvalue 1 lfe 0"));
            REQUIRE(count_prefix(direct, "setvalue 1 packformat AP_") == 1);
            const auto hoa = messages(obj, k_hoa);
            REQUIRE(contains(hoa, "order 1"));
            REQUIRE(contains(hoa, "normalization SN3D"));
            REQUIRE(contains(hoa, "tracks 9 10 11 12"));
        }

        THEN("reading emits the blocks active at time 0 as a jump") {
            const auto objects = messages(obj, k_objects);
            REQUIRE(contains(objects, "setvalue 1 ramp 0"));
            REQUIRE(contains(objects, "setvalue 1 cartesian 0"));
            REQUIRE(contains(objects, "setvalue 1 position 30 0 1"));
            REQUIRE(contains(objects, "setvalue 1 gain 1"));
            REQUIRE(count_prefix(objects, "setvalue 2 ") == 0);    // object B starts at 0.5 s
        }

        WHEN("the transport reaches the second block of object A") {
            clear_outputs(obj);
            obj.time(atoms{ 1000.0 });
            THEN("the block is emitted with the EAR's interpolation length as the ramp") {
                const auto objects = messages(obj, k_objects);
                REQUIRE(objects.front() == "setvalue 1 ramp 250");
                REQUIRE(contains(objects, "setvalue 1 position -30 10 1"));
                REQUIRE(contains(objects, "setvalue 1 width 20"));
                REQUIRE(contains(objects, "setvalue 1 gain 0.5"));
                // object B's block started at 0.5 s and was not emitted yet: it is a jump
                REQUIRE(contains(objects, "setvalue 2 ramp 0"));
                REQUIRE(contains(objects, "setvalue 2 cartesian 1"));
                REQUIRE(contains(objects, "setvalue 2 position 0.5 0.5 0"));
                REQUIRE(contains(objects, "setvalue 2 channellock_distance 0.3"));
                REQUIRE(contains(objects, "setvalue 2 screenref 1"));
            }

            AND_WHEN("the same time is requested again") {
                clear_outputs(obj);
                obj.time(atoms{ 1500.0 });
                THEN("nothing is re-emitted") {
                    REQUIRE(messages(obj, k_objects).empty());
                }
            }

            AND_WHEN("the transport goes back in time") {
                clear_outputs(obj);
                obj.time(atoms{ 0.0 });
                THEN("the blocks are emitted again as a jump") {
                    const auto objects = messages(obj, k_objects);
                    REQUIRE(objects.front() == "setvalue 1 ramp 0");
                    REQUIRE(contains(objects, "setvalue 1 position 30 0 1"));
                }
            }
        }

        WHEN("a block that does not follow the previous one directly is reached") {
            obj.time(atoms{ 1000.0 });
            clear_outputs(obj);
            obj.time(atoms{ 2500.0 });
            THEN("it is a jump (the fixture's third block has jumpPosition without a length)") {
                const auto objects = messages(obj, k_objects);
                REQUIRE(objects.front() == "setvalue 1 ramp 0");
                REQUIRE(contains(objects, "setvalue 1 position 0 30 1"));
            }
        }

        WHEN("the time is in a gap between two blocks of an object, or after its last block") {
            obj.time(atoms{ 1000.0 });
            clear_outputs(obj);
            obj.time(atoms{ 2200.0 });
            THEN("the object is silenced once, as in the EAR") {
                auto objects = messages(obj, k_objects);
                REQUIRE(objects == std::vector<std::string>{ "setvalue 1 ramp 0", "setvalue 1 gain 0" });
                clear_outputs(obj);
                obj.time(atoms{ 2300.0 });
                REQUIRE(messages(obj, k_objects).empty());
            }
            AND_WHEN("the next block starts") {
                clear_outputs(obj);
                obj.time(atoms{ 2600.0 });
                THEN("object A comes back with a jump and object B, whose last block ended at 2.5 s, is silenced") {
                    const auto objects = messages(obj, k_objects);
                    REQUIRE(objects.front() == "setvalue 1 ramp 0");
                    REQUIRE(contains(objects, "setvalue 1 gain 1"));
                    REQUIRE(contains(objects, "setvalue 1 position 0 30 1"));
                    REQUIRE(contains(objects, "setvalue 2 gain 0"));
                }
            }
        }

        WHEN("the time is before an object's first block") {
            obj.time(atoms{ 0.0 });
            clear_outputs(obj);
            THEN("nothing is sent for it (its gain was never set)") {
                REQUIRE(count_prefix(messages(obj, k_objects), "setvalue 2 ") == 0);
            }
        }

        WHEN("the transport is stepped from the start") {
            obj.seek(atoms{ 0.0 });
            clear_outputs(obj);
            obj.step();
            THEN("the first step is object B's block at 0.5 s") {
                REQUIRE(obj.position() == Approx(0.5));
                REQUIRE(contains(messages(obj, k_info), "position 500"));
                REQUIRE(count_prefix(messages(obj, k_objects), "setvalue 2 ") > 0);
            }
            obj.step();
            REQUIRE(obj.position() == Approx(1.0));
            obj.step();
            THEN("the end of a block is a step too: object A falls silent at 2 s") {
                REQUIRE(obj.position() == Approx(2.0));
                const auto objects = messages(obj, k_objects);
                REQUIRE(objects.back() == "setvalue 1 gain 0");
            }
            obj.step();
            REQUIRE(obj.position() == Approx(2.5));
            obj.step();
            THEN("the last step is the end of the metadata (the fixture's audio is shorter than its blocks)") {
                REQUIRE(obj.position() == Approx(3.0));
                REQUIRE(contains(messages(obj, k_info), "end 3000"));
                REQUIRE_FALSE(obj.running());
            }
        }

        WHEN("a file that does not exist is read afterwards") {
            obj.time(atoms{ 1000.0 });
            clear_outputs(obj);
            obj.read(atoms{ symbol(std::string(EARMAX_TEST_DATA_DIR) + "/missing.wav") });
            THEN("the previous file is gone as well: nothing plays and a programme change does not bring it back") {
                REQUIRE_FALSE(obj.loaded());
                REQUIRE(contains(messages(obj, k_info), "file none"));
                obj.programme(atoms{ 1 });
                REQUIRE_FALSE(obj.loaded());
                clear_outputs(obj);
                obj.time(atoms{ 0.0 });
                obj.step();
                REQUIRE(messages(obj, k_objects).empty());
            }
        }

        WHEN("the file is read again after a time change") {
            obj.time(atoms{ 2000.0 });
            clear_outputs(obj);
            obj.read(atoms{ symbol(k_fixture) });
            THEN("the position is back at 0") {
                REQUIRE(obj.position() == Approx(0.0));
                REQUIRE(contains(messages(obj, k_objects), "setvalue 1 position 30 0 1"));
            }
        }
    }

    GIVEN("an instance reading a file that does not exist") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.programme(atoms{ 2 });    // before any file: remembered, no error
        obj.read(atoms{ symbol(std::string(EARMAX_TEST_DATA_DIR) + "/missing.wav") });
        THEN("nothing is loaded and the transport does nothing") {
            REQUIRE_FALSE(obj.loaded());
            obj.time(atoms{ 1000.0 });
            obj.step();
            REQUIRE(messages(obj, k_objects).empty());
        }
    }
}

SCENARIO("ear.adm captures object messages and writes them as ADM") {
    ext_main(nullptr);

    GIVEN("an instance capturing two objects") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.chans = 2;
        obj.ramp = 10.0;
        obj.name(atoms{ 1, symbol("voice") });

        obj.setvalue(atoms{ 1, symbol("azimuth"), 30.0 });    // before the capture: part of the initial state
        obj.begin_capture_at(1000.0);
        obj.capture_at(1500.0, "position", 1, atoms{ -30.0, 10.0 });
        obj.capture_at(1500.0, "ramp", 1, atoms{ 250.0 });
        obj.capture_at(1500.0, "gain", 1, atoms{ 0.5 });
        obj.capture_at(2000.0, "cartesian", 2, atoms{ 1 });
        obj.capture_at(2000.0, "position", 2, atoms{ 0.5, 0.5, 0.0 });
        obj.capture_at(2000.0, "diffuse", 0, atoms{ 0.25 });
        obj.capture_at(2000.0, "zone", 2, atoms{ symbol("polar"), 150.0, -150.0, -90.0, 90.0 });    // azimuths wrapping the back: fine
        obj.capture_at(2500.0, "zone", 1, atoms{ symbol("polar"), -30.0, 30.0, -10.0, 10.0 });
        obj.capture_at(2500.0, "zone", 1, atoms{ symbol("cartesian"), -1.0, 1.0, -1.0, 0.0, -0.5, 0.5 });
        obj.capture_at(2500.0, "zone", 1, atoms{ symbol("polar"), -200.0, 30.0, -10.0, 10.0 });    // out of range: ignored
        obj.capture_at(2500.0, "zone", 2, atoms{ symbol("polar"), 0.0, 90.0 });                     // too few bounds: ignored
        obj.capture_at(2500.0, "zone", 2, atoms{ symbol("cartesian"), 1.0, -1.0, -1.0, 1.0, -1.0, 1.0 });    // minX above maxX: ignored
        obj.capture_at(2500.0, "zone", 2, atoms{ symbol("polar"), -30.0, 30.0, 40.0, 10.0 });              // minEl above maxEl: ignored
        obj.capture_at(2500.0, "azimuth", 1, atoms{ symbol("left") });    // invalid: ignored
        obj.capture_at(3000.0, "ramp", 1, atoms{ -1.0 });                  // back to the ramp attribute
        obj.capture_at(3000.0, "elevation", 1, atoms{ 20.0 });
        obj.capture_at(3000.0, "zone", 1, atoms{ symbol("clear"), 1 });    // surplus argument: ignored
        obj.capture_at(3500.0, "zone", 1, atoms{ symbol("clear") });

        THEN("the changes are timestamped from the capture start, one block per time") {
            const auto& one = obj.captured(0);
            REQUIRE(one.size() == 6);
            REQUIRE(one[0].time == Approx(0.0));
            REQUIRE(one[0].state.azimuth == Approx(30.0));
            REQUIRE(one[1].time == Approx(0.5));
            REQUIRE(one[1].ramp == Approx(0.25));
            REQUIRE(one[1].state.azimuth == Approx(-30.0));
            REQUIRE(one[1].state.elevation == Approx(10.0));
            REQUIRE(one[1].state.gain == Approx(0.5));
            REQUIRE(one[2].time == Approx(1.0));
            REQUIRE(one[2].ramp == Approx(0.25));    // the object's ramp persists like the renderers' per-object ramp
            REQUIRE(one[2].state.diffuse == Approx(0.25));
            REQUIRE(one[3].time == Approx(1.5));
            REQUIRE(one[3].state.zones.size() == 2);    // the two valid zones, the invalid ones rejected
            REQUIRE_FALSE(one[3].state.zones[0].cartesian);
            REQUIRE(one[3].state.zones[0].bounds == std::vector<double>{ -30.0, 30.0, -10.0, 10.0 });
            REQUIRE(one[3].state.zones[1].cartesian);
            REQUIRE(one[3].state.zones[1].bounds == std::vector<double>{ -1.0, 1.0, -1.0, 0.0, -0.5, 0.5 });
            REQUIRE(one[4].time == Approx(2.0));
            REQUIRE(one[4].ramp == Approx(0.01));    // a negative ramp returned the object to the attribute (10 ms)
            REQUIRE(one[4].state.elevation == Approx(20.0));
            REQUIRE(one[4].state.zones.size() == 2);    // zones persist like any parameter; the bad clear was rejected
            REQUIRE(one[5].time == Approx(2.5));
            REQUIRE(one[5].state.zones.empty());
            const auto& two = obj.captured(1);
            REQUIRE(two.size() == 2);    // the rejected zones made no block
            REQUIRE(two[1].time == Approx(1.0));
            REQUIRE(two[1].ramp == Approx(0.01));
            REQUIRE(two[1].state.cartesian);
            REQUIRE(two[1].state.x == Approx(0.5));
            REQUIRE(two[1].state.diffuse == Approx(0.25));
            REQUIRE(two[1].state.zones.size() == 1);
            REQUIRE(two[1].state.zones[0].bounds == std::vector<double>{ 150.0, -150.0, -90.0, 90.0 });
        }

        WHEN("the capture is written with recorded audio and read back") {
            const std::string audio = write_audio("captured_audio.wav", 2, 48000 * 2);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/captured.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            REQUIRE(count_prefix(messages(obj, k_info), "written ") == 1);

            test_wrapper<ear_adm> another_instance;
            ear_adm& reader = another_instance;
            reader.read(atoms{ symbol(out) });
            REQUIRE(reader.loaded());

            THEN("the audio is copied and the objects come back with their blocks") {
                REQUIRE(reader.info().channels == 2);
                REQUIRE(reader.info().frames == 48000 * 2);
                const auto& items = reader.items();
                REQUIRE(items.programmes == std::vector<std::string>{ "libear-max" });
                REQUIRE(items.objects.size() == 2);
                REQUIRE(items.objects[0].name == "voice");
                REQUIRE(items.objects[0].track == 0);
                REQUIRE(items.objects[1].name == "object 2");
                REQUIRE(items.objects[1].track == 1);

                const auto& voice = items.objects[0].blocks;
                REQUIRE(voice.size() == 6);
                REQUIRE(voice[0].start == Approx(0.0));
                REQUIRE(voice[0].end == Approx(0.5));
                REQUIRE(voice[0].state.azimuth == Approx(30.0));
                REQUIRE(voice[1].start == Approx(0.5));
                REQUIRE(voice[1].end == Approx(1.0));
                REQUIRE(voice[1].interp == Approx(0.25));
                REQUIRE(voice[1].state.azimuth == Approx(-30.0));
                REQUIRE(voice[1].state.elevation == Approx(10.0));
                REQUIRE(voice[1].state.gain == Approx(0.5));
                REQUIRE(voice[2].start == Approx(1.0));
                REQUIRE(voice[2].end == Approx(1.5));
                REQUIRE(voice[2].interp == Approx(0.25));    // the object's ramp stays until it is changed
                REQUIRE(voice[2].state.diffuse == Approx(0.25));
                REQUIRE(voice[2].state.zones.empty());
                REQUIRE(voice[3].start == Approx(1.5));
                REQUIRE(voice[3].state.zones.size() == 2);
                REQUIRE_FALSE(voice[3].state.zones[0].cartesian);
                REQUIRE(voice[3].state.zones[0].bounds == std::vector<double>{ -30.0, 30.0, -10.0, 10.0 });
                REQUIRE(voice[3].state.zones[1].cartesian);
                REQUIRE(voice[3].state.zones[1].bounds == std::vector<double>{ -1.0, 1.0, -1.0, 0.0, -0.5, 0.5 });
                REQUIRE(voice[4].start == Approx(2.0));
                REQUIRE(voice[4].end == Approx(2.5));
                REQUIRE(voice[4].state.elevation == Approx(20.0));
                REQUIRE(voice[4].state.zones.size() == 2);
                REQUIRE(voice[5].start == Approx(2.5));
                REQUIRE(voice[5].end == Approx(2.5));    // past the end of the audio: an empty last block
                REQUIRE(voice[5].state.zones.empty());    // the clear

                const auto& second = items.objects[1].blocks;
                REQUIRE(second.size() == 2);
                REQUIRE(second[1].state.cartesian);
                REQUIRE(second[1].state.x == Approx(0.5));
                REQUIRE(second[1].state.y == Approx(0.5));
                REQUIRE(items.direct.empty());
                REQUIRE(items.hoa.empty());
            }

            THEN("the written file plays back the captured ramps") {
                c74::max::object_getoutput(reader, k_objects)->clear();
                reader.time(atoms{ 500.0 });
                const auto objects = messages(reader, k_objects);
                REQUIRE(objects.front() == "setvalue 1 ramp 250");
                REQUIRE(contains(objects, "setvalue 1 position -30 10 1"));
                REQUIRE(contains(objects, "setvalue 1 zone clear"));    // a block without zones clears them
                REQUIRE(count_prefix(objects, "setvalue 1 zone ") == 1);
            }

            THEN("the written file plays back the zones as the renderers' messages") {
                c74::max::object_getoutput(reader, k_objects)->clear();
                reader.time(atoms{ 1500.0 });
                const auto objects = messages(reader, k_objects);
                REQUIRE(contains(objects, "setvalue 1 zone clear"));
                REQUIRE(contains(objects, "setvalue 1 zone polar -30 30 -10 10"));
                REQUIRE(contains(objects, "setvalue 1 zone cartesian -1 1 -1 0 -0.5 0.5"));
                REQUIRE(count_prefix(objects, "setvalue 1 zone ") == 3);
            }
        }

        WHEN("the capture is written as XML") {
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/captured.xml";
            std::remove(out.c_str());
            obj.writexml(atoms{ symbol(out), 3.0 });
            THEN("the file holds an audioFormatExtended with the objects") {
                std::ifstream file(out);
                REQUIRE(file.good());
                std::stringstream xml;
                xml << file.rdbuf();
                REQUIRE(xml.str().find("audioFormatExtended") != std::string::npos);
                REQUIRE(xml.str().find("audioObjectName=\"voice\"") != std::string::npos);
                REQUIRE(xml.str().find("interpolationLength") != std::string::npos);
                REQUIRE(xml.str().find("<zoneExclusion>") != std::string::npos);
                REQUIRE(xml.str().find("minAzimuth=\"-30") != std::string::npos);
                REQUIRE(xml.str().find("maxZ=\"0.5") != std::string::npos);
            }
        }

        WHEN("the capture is cleared") {
            obj.clear();
            THEN("the objects have no blocks and default parameters") {
                REQUIRE(obj.captured(0).empty());
                REQUIRE(obj.captured(1).empty());
            }
        }
    }
}

SCENARIO("ear.adm keeps a zone's label through a file") {
    ext_main(nullptr);

    GIVEN("a file whose object has a labelled Cartesian zone and an unlabelled polar one") {
        const std::string audio = write_audio("zone_label_audio.wav", 1, 4800);
        const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/zone_label.wav";
        admio::captured_object object;
        object.name = "zoned";
        admio::object_state state;
        state.zones.push_back({ true, { -1.0, 1.0, -1.0, 0.0, -1.0, 1.0 }, "Rear" });
        state.zones.push_back({ false, { -180.0, 180.0, 30.0, 90.0 }, "" });
        object.blocks.push_back({ 0.0, 0.0, state });
        std::vector<bw64::AudioId> chna_ids;
        auto doc = admio::build_document("labels", { object }, 0.1, chna_ids);
        REQUIRE(admio::to_xml(doc).find(">Rear</zone>") != std::string::npos);
        std::remove(out.c_str());
        admio::write_file(out, audio, doc, chna_ids);

        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(out) });
        REQUIRE(obj.loaded());

        THEN("the zones come back with the label, and writing them again keeps it") {
            const auto& blocks = obj.items().objects[0].blocks;
            REQUIRE(blocks.size() == 1);
            const auto& zones = blocks[0].state.zones;
            REQUIRE(zones.size() == 2);
            REQUIRE(zones[0].cartesian);
            REQUIRE(zones[0].label == "Rear");
            REQUIRE_FALSE(zones[1].cartesian);
            REQUIRE(zones[1].label.empty());

            admio::captured_object again;
            again.name = "zoned";
            again.blocks.push_back({ 0.0, 0.0, blocks[0].state });
            std::vector<bw64::AudioId> ids;
            const std::string xml = admio::to_xml(admio::build_document("labels", { again }, 0.1, ids));
            REQUIRE(xml.find(">Rear</zone>") != std::string::npos);
            REQUIRE(xml.find("minElevation=\"30") != std::string::npos);
        }

        THEN("playback sends the zones without the label, as the renderers take them") {
            const auto objects = messages(obj, k_objects);
            REQUIRE(contains(objects, "setvalue 1 zone cartesian -1 1 -1 0 -1 1"));
            REQUIRE(contains(objects, "setvalue 1 zone polar -180 180 30 90"));
        }
    }
}

SCENARIO("ear.adm reads the bed of a Dolby Atmos master") {
    ext_main(nullptr);

    GIVEN("a file shaped like a Dolby Atmos master: a 7.1.2 bed with Dolby labels and Cartesian positions, then a Cartesian object") {
        // the bed of the Dolby Atmos Master ADM Profile (table 2-14): custom
        // channel formats, cartesian 1, no frequency element for the LFE
        struct dolby_channel {
            const char* label;
            double x, y, z;
        };
        const dolby_channel channels[] = {
            { "RC_L", -1.0, 1.0, 0.0 },   { "RC_R", 1.0, 1.0, 0.0 },   { "RC_C", 0.0, 1.0, 0.0 },   { "RC_LFE", -1.0, 1.0, -1.0 },
            { "RC_Lss", -1.0, 0.0, 0.0 }, { "RC_Rss", 1.0, 0.0, 0.0 }, { "RC_Lrs", -1.0, -1.0, 0.0 }, { "RC_Rrs", 1.0, -1.0, 0.0 },
            { "RC_Lts", -1.0, 0.0, 1.0 }, { "RC_Rts", 1.0, 0.0, 1.0 },
        };
        const std::string audio = write_audio("dolby_audio.wav", 11, 4800);
        const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/dolby_bed.wav";
        admio::captured_programme captured;
        captured.name = "Atmos_Master";
        admio::captured_object object;
        object.name = "Atmos_Obj_11";
        admio::object_state state;
        state.cartesian = true;
        state.x = 0.5;
        state.y = 0.5;
        state.z = 0.25;
        object.blocks.push_back({ 0.0, 0.0, state });
        captured.objects.push_back(object);
        captured.bed.name = "Atmos_Bed_1";
        for (const auto& c : channels) {
            admio::captured_direct_channel ch;
            ch.labels = { c.label };
            ch.has_position = true;
            ch.cartesian = true;
            ch.x = c.x;
            ch.y = c.y;
            ch.z = c.z;
            captured.bed.channels.push_back(ch);
        }
        std::vector<bw64::AudioId> chna_ids;
        std::vector<std::string> warnings;
        auto doc = admio::build_document(captured, 0.1, chna_ids, warnings);
        const std::string xml = admio::to_xml(doc);
        REQUIRE(xml.find("RC_Lts") != std::string::npos);
        REQUIRE(xml.find("coordinate=\"X\"") != std::string::npos);
        REQUIRE(xml.find("lowPass") == std::string::npos);
        std::remove(out.c_str());
        admio::write_file(out, audio, doc, chna_ids);

        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(out) });
        REQUIRE(obj.loaded());

        THEN("the bed's channels come back with the BS.2051 labels of the same loudspeakers, their Cartesian positions and the LFE") {
            const auto& items = obj.items();
            REQUIRE(items.warnings.empty());
            REQUIRE(items.direct.size() == 10);
            const std::vector<std::string> labels{ "M+030", "M-030", "M+000", "LFE1", "M+090", "M-090", "M+135", "M-135", "U+090", "U-090" };
            for (size_t i = 0; i < labels.size(); ++i) {
                REQUIRE(items.direct[i].labels == std::vector<std::string>{ labels[i] });
                REQUIRE(items.direct[i].track == static_cast<int>(i + 1));
                REQUIRE(items.direct[i].has_position);
                REQUIRE(items.direct[i].cartesian);
                REQUIRE(items.direct[i].x == Approx(channels[i].x));
                REQUIRE(items.direct[i].y == Approx(channels[i].y));
                REQUIRE(items.direct[i].z == Approx(channels[i].z));
                REQUIRE(items.direct[i].lfe == (i == 3));
                REQUIRE(items.direct[i].pack_id.empty() == false);    // the custom pack of the bed
            }
            REQUIRE(items.objects.size() == 1);
            REQUIRE(items.objects[0].blocks[0].state.cartesian);
            REQUIRE(items.objects[0].blocks[0].state.x == Approx(0.5));
        }

        THEN("mc.ear.direct~ is sent the channels in Cartesian coordinates") {
            const auto direct = messages(obj, k_direct);
            REQUIRE(contains(direct, "setvalue 1 speakerlabel M+030"));
            REQUIRE(contains(direct, "setvalue 1 cartesian 1"));
            REQUIRE(contains(direct, "setvalue 1 position -1 1 0"));
            REQUIRE(contains(direct, "setvalue 4 speakerlabel LFE1"));
            REQUIRE(contains(direct, "setvalue 4 lfe 1"));
            REQUIRE(contains(direct, "setvalue 9 speakerlabel U+090"));
            REQUIRE(contains(direct, "setvalue 9 position -1 0 1"));
        }
    }

    GIVEN("an instance capturing a bed channel given in Cartesian coordinates") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.chans = 1;
        obj.directchans = 2;
        obj.direct(atoms{ symbol("setvalue"), 1, symbol("cartesian"), 1 });
        obj.direct(atoms{ symbol("setvalue"), 1, symbol("position"), -1.0, 0.0, 1.0 });
        obj.direct(atoms{ symbol("setvalue"), 1, symbol("speakerlabel"), symbol("U+090") });
        obj.direct(atoms{ symbol("setvalue"), 1, symbol("bounds"), -1.0, -0.5, -0.5, 0.5, 0.5, 1.0 });
        obj.direct(atoms{ symbol("setvalue"), 2, symbol("position"), 30.0, 0.0 });

        WHEN("the capture is written and read back") {
            const std::string audio = write_audio("cartesian_bed_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/cartesian_bed.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            REQUIRE(count_prefix(messages(obj, k_info), "written ") == 1);

            test_wrapper<ear_adm> another_instance;
            ear_adm& reader = another_instance;
            reader.read(atoms{ symbol(out) });
            REQUIRE(reader.loaded());

            THEN("the Cartesian channel keeps its position and bounds, the polar one stays polar") {
                const auto& items = reader.items();
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[0].cartesian);
                REQUIRE(items.direct[0].x == Approx(-1.0));
                REQUIRE(items.direct[0].y == Approx(0.0));
                REQUIRE(items.direct[0].z == Approx(1.0));
                REQUIRE(items.direct[0].bounds == std::vector<double>{ -1.0, -0.5, -0.5, 0.5, 0.5, 1.0 });
                REQUIRE_FALSE(items.direct[1].cartesian);
                REQUIRE(items.direct[1].azimuth == Approx(30.0));
                const auto direct = messages(reader, k_direct);
                REQUIRE(contains(direct, "setvalue 1 cartesian 1"));
                REQUIRE(contains(direct, "setvalue 1 bounds -1 -0.5 -0.5 0.5 0.5 1"));
                REQUIRE(contains(direct, "setvalue 2 cartesian 0"));
                REQUIRE(contains(direct, "setvalue 2 position 30 0 1"));
            }
        }
    }
}

SCENARIO("ear.adm captures a timed bed and plays its blocks back") {
    ext_main(nullptr);

    GIVEN("an instance capturing one object and a stereo bed whose channels change") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.chans = 1;
        obj.directchans = 2;
        obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
        obj.begin_capture_at(1000.0);
        obj.direct_at(1500.0, atoms{ symbol("setvalue"), 1, symbol("position"), 45.0, 0.0 });
        obj.direct_at(1500.0, atoms{ symbol("setvalue"), 1, symbol("bounds"), 40.0, 50.0, -5.0, 5.0 });    // same time: one block
        obj.direct_at(2000.0, atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("M-045") });
        obj.direct_at(2500.0, atoms{ symbol("setvalue"), 2, symbol("lfe"), 1 });    // channel-level: no block
        obj.direct_at(2600.0, atoms{ symbol("setvalue"), 1, symbol("position"), 45.0, 0.0 });    // unchanged: no block
        obj.direct_at(2700.0, atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("M-045") });    // unchanged: no block
        obj.stop();

        THEN("each channel has a block per change, the first at the capture start") {
            const auto& one = obj.bed().blocks(0);
            REQUIRE(one.size() == 2);
            REQUIRE(one[0].time == Approx(0.0));
            REQUIRE(one[0].azimuth == Approx(30.0));
            REQUIRE(one[1].time == Approx(0.5));
            REQUIRE(one[1].azimuth == Approx(45.0));
            REQUIRE(one[1].bounds == std::vector<double>{ 40.0, 50.0, -5.0, 5.0 });
            const auto& two = obj.bed().blocks(1);
            REQUIRE(two.size() == 2);
            REQUIRE(two[1].time == Approx(1.0));
            REQUIRE(two[1].labels == std::vector<std::string>{ "M-045" });
        }

        WHEN("the capture is written and read back") {
            const std::string audio = write_audio("timed_bed_audio.wav", 3, 48000 * 3);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/timed_bed.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            REQUIRE(contains(messages(obj, k_info), "written " + out + " 3 144000"));

            test_wrapper<ear_adm> another_instance;
            ear_adm& reader = another_instance;
            reader.read(atoms{ symbol(out) });
            REQUIRE(reader.loaded());
            const auto& items = reader.items();

            THEN("the bed has its own channel formats with timed blocks") {
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[0].timed());
                REQUIRE(items.direct[0].pack_id != "AP_00010002");    // timed: the common definitions cannot carry it
                REQUIRE(items.direct[0].blocks.size() == 2);
                REQUIRE(items.direct[0].blocks[0].start == Approx(0.0));
                REQUIRE(items.direct[0].blocks[0].end == Approx(0.5));
                REQUIRE(items.direct[0].blocks[1].start == Approx(0.5));
                REQUIRE(items.direct[0].blocks[1].end == Approx(3.0));
                REQUIRE(items.direct[0].blocks[1].azimuth == Approx(45.0));
                REQUIRE(items.direct[0].blocks[1].bounds == std::vector<double>{ 40.0, 50.0, -5.0, 5.0 });
                REQUIRE(items.direct[0].labels == std::vector<std::string>{ "M+030" });    // the first block's
                REQUIRE(items.direct[1].blocks[1].labels == std::vector<std::string>{ "M-045" });
                REQUIRE(items.direct[1].lfe);
            }

            THEN("the first blocks are sent when the file is read, with the channel-level parameters") {
                const auto direct = messages(reader, k_direct);
                REQUIRE(contains(direct, "setvalue 1 speakerlabel M+030"));
                REQUIRE(contains(direct, "setvalue 1 position 30 0 1"));
                REQUIRE(contains(direct, "setvalue 2 lfe 1"));
                REQUIRE(count_prefix(direct, "setvalue 1 position 45") == 0);
            }

            THEN("the transport emits the bed's blocks at their times") {
                c74::max::object_getoutput(reader, k_direct)->clear();
                reader.time(atoms{ 600.0 });
                auto direct = messages(reader, k_direct);
                REQUIRE(contains(direct, "setvalue 1 position 45 0 1"));
                REQUIRE(contains(direct, "setvalue 1 bounds 40 50 -5 5"));
                REQUIRE(count_prefix(direct, "setvalue 2 speakerlabel") == 0);    // channel 2 changes later
                c74::max::object_getoutput(reader, k_direct)->clear();
                reader.step();    // the next boundary is the bed's change at 1 s
                REQUIRE(reader.position() == Approx(1.0));
                direct = messages(reader, k_direct);
                REQUIRE(contains(direct, "setvalue 2 speakerlabel M-045"));
                c74::max::object_getoutput(reader, k_direct)->clear();
                reader.time(atoms{ 0.0 });
                REQUIRE(contains(messages(reader, k_direct), "setvalue 1 position 30 0 1"));
            }
        }
    }
}

SCENARIO("ear.adm keeps a bed static when its metadata is only repeated") {
    ext_main(nullptr);

    GIVEN("an instance capturing a bed whose layout and parameters are sent again unchanged") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.directchans = 2;
        obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
        obj.begin_capture_at(1000.0);
        obj.direct_at(1500.0, atoms{ symbol("inputlayout"), symbol("0+2+0") });
        obj.direct_at(2000.0, atoms{ symbol("setvalue"), 1, symbol("speakerlabel"), symbol("M+030") });
        obj.direct_at(2500.0, atoms{ symbol("applyvalues"), symbol("azimuth"), 30.0, -30.0 });
        obj.stop();
        THEN("each channel keeps its single block and the bed still references the layout") {
            REQUIRE(obj.bed().blocks(0).size() == 1);
            REQUIRE(obj.bed().blocks(1).size() == 1);
            const auto bed = obj.bed().bed();
            REQUIRE(!bed.channels[0].timed());
            REQUIRE(bed.channels[0].pack_id == "AP_00010002");
        }
    }
}

SCENARIO("ear.adm seeds a bed channel added while capturing") {
    ext_main(nullptr);

    GIVEN("an instance capturing a bed that grows by a channel") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.directchans = 2;
        obj.begin_capture_at(1000.0);
        obj.directchans = 3;
        obj.direct_at(3000.0, atoms{ symbol("setvalue"), 3, symbol("speakerlabel"), symbol("M+000") });
        obj.stop();
        THEN("the new channel starts with its state at time 0 and the change is its second block") {
            const auto& three = obj.bed().blocks(2);
            REQUIRE(three.size() == 2);
            REQUIRE(three[0].time == Approx(0.0));
            REQUIRE(three[0].labels.empty());
            REQUIRE(three[1].time == Approx(2.0));
            REQUIRE(three[1].labels == std::vector<std::string>{ "M+000" });
        }
    }
}

SCENARIO("ear.adm writes a DirectSpeakers bed and an HOA scene after the objects") {
    ext_main(nullptr);

    GIVEN("an instance with one object, a 5.1 bed and a first-order scene") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.chans = 1;
        obj.directchans = 6;
        obj.hoa(atoms{ symbol("order"), 1 });
        obj.hoa(atoms{ symbol("normalization"), symbol("N3D") });
        obj.hoa(atoms{ symbol("name"), symbol("ambience") });
        obj.direct(atoms{ symbol("tracks"), 2, 3 });    // from a reading ear.adm: ignored
        obj.direct(atoms{ symbol("inputlayout"), symbol("0+5+0") });
        obj.direct(atoms{ symbol("name"), symbol("music") });
        obj.setvalue(atoms{ 1, symbol("azimuth"), 30.0 });

        THEN("the bed and scene are captured as mc.ear.direct~ and mc.ear.hoa~ would take them") {
            REQUIRE(static_cast<int>(obj.hoaorder) == 1);
            REQUIRE(obj.scene().normalization == "N3D");
            REQUIRE(obj.scene().channels() == 4);
            REQUIRE(obj.scene().name == "ambience");
            REQUIRE(obj.bed().size() == 6);
            REQUIRE(obj.bed().at(3).dstm.speakerLabels == std::vector<std::string>{ "LFE1" });
            REQUIRE(static_cast<bool>(obj.bed().at(3).dstm.channelFrequency.lowPass));
            REQUIRE(obj.bed().at(4).position.azimuth == Approx(110.0));
            REQUIRE(*obj.bed().at(0).dstm.audioPackFormatID == "AP_00010003");
        }

        WHEN("the capture is written with 11 tracks of audio and read back") {
            const std::string audio = write_audio("bed_audio.wav", 11, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            REQUIRE(contains(messages(obj, k_info), "written " + out + " 11 4800"));

            test_wrapper<ear_adm> another_instance;
            ear_adm& reader = another_instance;
            reader.read(atoms{ symbol(out) });
            REQUIRE(reader.loaded());
            const auto& items = reader.items();

            THEN("the object comes first, the bed references the common definitions layout, the scene follows") {
                REQUIRE(items.warnings.empty());
                REQUIRE(items.objects.size() == 1);
                REQUIRE(items.objects[0].track == 0);
                REQUIRE(items.direct.size() == 6);
                for (size_t i = 0; i < 6; ++i) {
                    REQUIRE(items.direct[i].track == static_cast<int>(i + 1));
                    REQUIRE(items.direct[i].name == "music");
                    REQUIRE(items.direct[i].pack_id == "AP_00010003");
                }
                // the common definitions carry the labels in their URN form (libear takes both)
                REQUIRE(items.direct[0].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:M+030" });
                REQUIRE(items.direct[0].has_position);
                REQUIRE(items.direct[0].azimuth == Approx(30.0));
                REQUIRE(items.direct[3].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:LFE" });    // the layout's LFE1
                REQUIRE(items.direct[3].lfe);
                REQUIRE(items.hoa.size() == 1);
                REQUIRE(items.hoa[0].name == "ambience");
                REQUIRE(items.hoa[0].order == 1);
                REQUIRE(items.hoa[0].normalization == "N3D");
                REQUIRE(items.hoa[0].complete);
                REQUIRE(items.hoa[0].tracks == std::vector<int>{ 7, 8, 9, 10 });
                REQUIRE(contains(messages(reader, k_direct), "setvalue 4 speakerlabel urn:itu:bs:2051:0:speaker:LFE"));
                REQUIRE(contains(messages(reader, k_direct), "setvalue 4 lfe 1"));
                REQUIRE(contains(messages(reader, k_hoa), "order 1"));
                REQUIRE(contains(messages(reader, k_hoa), "normalization N3D"));
                REQUIRE(contains(messages(reader, k_hoa), "tracks 8 9 10 11"));
            }
        }

        WHEN("the audio has fewer tracks than captured") {
            const std::string audio = write_audio("bed_audio_short.wav", 9, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_short.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the objects and the bed are written and the incomplete scene is dropped") {
                REQUIRE(contains(messages(obj, k_info), "written " + out + " 7 4800"));
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.objects.size() == 1);
                REQUIRE(items.direct.size() == 6);
                REQUIRE(items.hoa.empty());
            }
        }

        WHEN("the bed is given custom channels instead of a layout") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("setvalue"), 1, symbol("speakerlabel"), symbol("M+045"), symbol("M+030") });
            obj.direct(atoms{ symbol("setvalue"), 1, symbol("position"), 45.0, 0.0 });
            obj.direct(atoms{ symbol("setvalue"), 1, symbol("bounds"), 30.0, 60.0, -5.0, 5.0 });
            obj.direct(atoms{ symbol("applyvalues"), symbol("lfe"), 0, 1 });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("LFE1") });
            obj.direct(atoms{ symbol("packformat"), symbol("none") });
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_custom_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_custom.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed is written with its own channel formats and reads back the same") {
                REQUIRE(contains(messages(obj, k_info), "written " + out + " 3 4800"));
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[0].labels == std::vector<std::string>{ "M+045", "M+030" });
                REQUIRE(items.direct[0].has_position);
                REQUIRE(items.direct[0].azimuth == Approx(45.0));
                REQUIRE(items.direct[0].bounds == std::vector<double>{ 30.0, 60.0, -5.0, 5.0 });
                REQUIRE(!items.direct[0].lfe);
                REQUIRE(items.direct[0].pack_id.rfind("AP_0001", 0) == 0);
                REQUIRE(items.direct[0].pack_id != "AP_00010003");
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "LFE1" });
                REQUIRE(items.direct[1].azimuth == Approx(-30.0));    // kept from the layout given before
                REQUIRE(items.direct[1].lfe);
                REQUIRE(items.hoa.empty());
            }
        }

        WHEN("a read bed with URN labels is captured again") {
            obj.directchans = 2;
            obj.hoa(atoms{ symbol("order"), -1 });
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 1, symbol("speakerlabel"), symbol("urn:itu:bs:2051:0:speaker:M+030") });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("urn:itu:bs:2051:1:speaker:M-030") });
            const std::string audio = write_audio("bed_urn_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_urn.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed still references the common definitions layout") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[1].pack_id == "AP_00010002");
            }
        }

        WHEN("a packformat is set that the labels do not fit") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("M+030") });    // twice the same label
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_fallback_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_fallback.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed falls back to its own channel formats") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "M+030" });
                REQUIRE(items.direct[1].pack_id != "AP_00010002");
                REQUIRE(items.direct[1].pack_id.rfind("AP_0001", 0) == 0);
            }
        }

        WHEN("a label from another layout is given with the packformat") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("speakerlabel"), symbol("M+110") });    // not in 0+2+0
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_other_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_other.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed is written with its own channel formats, keeping the label") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "M+110" });
                REQUIRE(items.direct[1].pack_id != "AP_00010002");
            }
        }

        WHEN("a layout channel is moved after inputlayout") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("position"), -45.0, 10.0, 1.0 });
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_moved_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_moved.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed is written with its own channel formats, keeping the position") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "M-030" });
                REQUIRE(items.direct[1].pack_id != "AP_00010002");
                REQUIRE(items.direct[1].pack_id.rfind("AP_0001", 0) == 0);
                REQUIRE(items.direct[1].azimuth == Approx(-45.0));
                REQUIRE(items.direct[1].elevation == Approx(10.0));
                REQUIRE(items.direct[0].azimuth == Approx(30.0));
            }
        }

        WHEN("a layout channel is given bounds or Cartesian coordinates after inputlayout") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 1, symbol("bounds"), 20.0, 40.0, -5.0, 5.0 });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("cartesian"), 1 });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("position"), 1.0, 1.0, 0.0 });
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_edited_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_edited.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed is written with its own channel formats, keeping the bounds and coordinates") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[0].pack_id != "AP_00010002");
                REQUIRE(items.direct[0].pack_id.rfind("AP_0001", 0) == 0);
                REQUIRE(items.direct[0].labels == std::vector<std::string>{ "M+030" });
                REQUIRE(items.direct[0].bounds == std::vector<double>{ 20.0, 40.0, -5.0, 5.0 });
                REQUIRE(!items.direct[0].cartesian);
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "M-030" });
                REQUIRE(items.direct[1].cartesian);
                REQUIRE(items.direct[1].x == Approx(1.0));
                REQUIRE(items.direct[1].y == Approx(1.0));
                REQUIRE(items.direct[1].z == Approx(0.0));
            }
        }

        WHEN("a layout channel is moved and then put back after inputlayout") {
            obj.directchans = 2;
            obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("azimuth"), -45.0 });
            obj.direct(atoms{ symbol("setvalue"), 2, symbol("azimuth"), -30.0 });
            obj.hoa(atoms{ symbol("order"), -1 });
            const std::string audio = write_audio("bed_restored_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/bed_restored.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            THEN("the bed still references the common definitions layout") {
                const auto items = admio::select_items(admio::load_file(out));
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[1].pack_id == "AP_00010002");
            }
        }

        WHEN("invalid bed and scene messages are sent") {
            obj.direct(atoms{ symbol("setvalue"), 9, symbol("lfe"), 1 });
            obj.direct(atoms{ symbol("inputlayout"), symbol("9+10+3") });    // more channels than the bed has
            obj.hoa(atoms{ symbol("order"), 12 });
            obj.hoa(atoms{ symbol("normalization"), symbol("MaxN") });
            THEN("they are rejected and the capture is unchanged") {
                REQUIRE(obj.bed().at(0).dstm.speakerLabels == std::vector<std::string>{ "M+030" });
                REQUIRE(obj.scene().order == 1);
                REQUIRE(obj.scene().normalization == "N3D");
            }
        }
    }
}

SCENARIO("ear.adm writes a Dolby Atmos master") {
    ext_main(nullptr);
    const size_t npos = std::string::npos;

    GIVEN("a programme captured with the Dolby profile: two objects, a 7.1.2 bed and a scene") {
        admio::captured_programme captured;
        captured.name = "Mix";
        captured.profile = admio::adm_profile::dolby;

        // a polar object with the profile's back zone, another zone, and
        // things the profile has no place for
        admio::captured_object voice;
        voice.name = "voice";
        admio::object_state s1;
        s1.azimuth = 30.0;
        s1.width = 20.0;
        s1.height = 10.0;
        s1.divergence = 0.5;
        s1.diffuse = 0.3;
        s1.screenref = true;
        admio::exclusion_zone back;
        back.cartesian = true;
        back.bounds = { -1.0, 1.0, -1.0, -0.41934, -0.499, 0.499 };
        admio::exclusion_zone other;
        other.bounds = { -30.0, 30.0, -10.0, 10.0 };
        s1.zones = { back, other };
        voice.blocks.push_back({ 0.0, 0.0, s1 });
        admio::object_state s1b = s1;
        s1b.azimuth = -30.0;
        voice.blocks.push_back({ 0.5, 0.01, s1b });

        // a Cartesian object outside the cube, channel locked with a
        // distance, with the top zone by its label
        admio::captured_object fx;
        fx.name = "fx";
        admio::object_state s2;
        s2.cartesian = true;
        s2.x = 1.5;
        s2.y = 0.5;
        s2.channellock = true;
        s2.channellock_distance = 1.0;
        s2.gain = 0.5;
        s2.diffuse = 1.0;
        admio::exclusion_zone top;
        top.cartesian = true;
        top.bounds = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
        top.label = "ZT";
        s2.zones = { top };
        fx.blocks.push_back({ 0.0, 0.0, s2 });
        captured.objects = { voice, fx };

        // the bed by the BS.2051 labels inputlayout and the reader give
        const char* labels[] = { "M+030", "M-030", "M+000", "LFE1", "M+090", "M-090", "M+135", "M-135", "U+090", "U-090" };
        captured.bed.name = "bed";
        for (const char* label : labels) {
            admio::captured_direct_channel ch;
            ch.labels = { label };
            ch.has_position = true;
            ch.azimuth = 30.0;
            ch.lfe = std::string(label) == "LFE1";
            captured.bed.channels.push_back(ch);
        }
        captured.scene.order = 1;

        std::vector<bw64::AudioId> chna_ids;
        std::vector<std::string> warnings;
        auto doc = admio::build_document(captured, 1.0, chna_ids, warnings, admio::audio_format{ 48000, 24 });
        const std::string xml = admio::to_xml(doc);
        INFO(xml);

        THEN("the bed has the profile's channel formats, labels and positions and no frequency element") {
            REQUIRE(xml.find("audioChannelFormatName=\"RoomCentricLeft\"") != npos);
            REQUIRE(xml.find("audioChannelFormatName=\"RoomCentricRightTopSurround\"") != npos);
            REQUIRE(xml.find("<speakerLabel>RC_Lts</speakerLabel>") != npos);
            REQUIRE(xml.find("<cartesian>1</cartesian>") != npos);
            REQUIRE(xml.find("coordinate=\"X\">-1.000000</position>") != npos);
            REQUIRE(xml.find("lowPass") == npos);
            REQUIRE(xml.find("audioStreamFormatName=\"PCM_RoomCentricLFE\"") != npos);
            REQUIRE(xml.find("audioTrackFormatName=\"PCM_RoomCentricLFE\"") != npos);
        }

        THEN("the objects have Cartesian blocks with the fixed interpolation and the vocabulary's zones") {
            REQUIRE(xml.find("audioStreamFormatName=\"PCM_voice\"") != npos);
            REQUIRE(xml.find("interpolationLength=\"0.00000\"") != npos);
            REQUIRE(xml.find("interpolationLength=\"0.005208\"") != npos);
            REQUIRE(xml.find("objectDivergence") == npos);
            REQUIRE(xml.find("<screenRef>1</screenRef>") == npos);
            REQUIRE(xml.find("maxDistance") == npos);
            REQUIRE(xml.find("<channelLock>1</channelLock>") != npos);
            REQUIRE(xml.find("<diffuse>1.000000</diffuse>") != npos);
            REQUIRE(xml.find("<diffuse>0") == npos);
            REQUIRE(xml.find(">ZM1</zone>") != npos);
            REQUIRE(xml.find("maxZ=\"1.000000\">ZT</zone>") != npos);
            REQUIRE(xml.find("coordinate=\"azimuth\"") == npos);
            REQUIRE(xml.find("coordinate=\"X\">1.000000</position>") != npos);    // clamped
            REQUIRE(xml.find("<width>") != npos);
            REQUIRE(xml.find("<depth>") != npos);
        }

        THEN("the names, references, timing and ids are the profile's") {
            REQUIRE(xml.find("audioProgrammeID=\"APR_1001\"") != npos);
            REQUIRE(xml.find("audioContentID=\"ACO_1001\"") != npos);
            REQUIRE(xml.find("audioContentName=\"Atmos_Master_Content\"") != npos);
            REQUIRE(xml.find("<dialogue mixedContentKind=\"0\">2</dialogue>") != npos);
            REQUIRE(xml.find("audioObjectID=\"AO_1001\" audioObjectName=\"bed\"") != npos);
            REQUIRE(xml.find("audioObjectID=\"AO_100b\" audioObjectName=\"voice\"") != npos);
            REQUIRE(xml.find("audioObjectID=\"AO_100c\" audioObjectName=\"fx\"") != npos);
            REQUIRE(xml.find("AC_0001100a") != npos);    // the bed's tenth channel
            REQUIRE(xml.find("AB_0001100a_00000001") != npos);
            REQUIRE(xml.find("AC_0003100b") != npos);    // the first object's channel
            REQUIRE(xml.find("AB_0003100b_00000002") != npos);
            REQUIRE(xml.find("AS_0003100c") != npos);
            REQUIRE(xml.find("AT_0003100c_01") != npos);
            REQUIRE(xml.find("AP_00011001") != npos);
            REQUIRE(xml.find("AP_00031002") != npos);
            REQUIRE(xml.find("AP_00031003") != npos);
            REQUIRE(xml.find("ATU_0000000c") != npos);
            REQUIRE(xml.find("ATU_0000000d") == npos);
            REQUIRE(xml.find("sampleRate=\"48000\"") != npos);
            REQUIRE(xml.find("bitDepth=\"24\"") != npos);
            REQUIRE(xml.find("start=\"00:00:00.00000\"") != npos);
            REQUIRE(xml.find("end=\"00:00:01.00000\"") != npos);
            REQUIRE(xml.find("duration=\"00:00:01.00000\"") != npos);
            REQUIRE(xml.find("typeDefinition=\"HOA\"") == npos);
            // the stream references both the channel and the pack
            const size_t stream = xml.find("<audioStreamFormat audioStreamFormatID=\"AS_0003100b\"");
            REQUIRE(stream != npos);
            const size_t stream_end = xml.find("</audioStreamFormat>", stream);
            REQUIRE(xml.find("<audioChannelFormatIDRef>AC_0003100b</audioChannelFormatIDRef>", stream) < stream_end);
            REQUIRE(xml.find("<audioPackFormatIDRef>AP_00031002</audioPackFormatIDRef>", stream) < stream_end);
        }

        THEN("the chna entries are the objects' then the bed's, with the profile's ids") {
            REQUIRE(chna_ids.size() == 12);
            REQUIRE(chna_ids[0].trackIndex() == 1);
            REQUIRE(chna_ids[0].uid() == "ATU_0000000b");
            REQUIRE(chna_ids[0].trackRef() == "AT_0003100b_01");
            REQUIRE(chna_ids[0].packRef() == "AP_00031002");
            REQUIRE(chna_ids[2].trackIndex() == 3);
            REQUIRE(chna_ids[2].uid() == "ATU_00000001");
            REQUIRE(chna_ids[2].packRef() == "AP_00011001");
            REQUIRE(chna_ids[11].uid() == "ATU_0000000a");
        }

        THEN("what the profile cannot carry is reported") {
            REQUIRE(warnings.size() == 3);
            REQUIRE(contains(warnings, "scene 'scene': an HOA scene has no place in the Dolby profile; its tracks are written without metadata"));
            std::string voice_warning, fx_warning;
            for (const auto& w : warnings) {
                if (w.rfind("object 'voice': ", 0) == 0) voice_warning = w;
                if (w.rfind("object 'fx': ", 0) == 0) fx_warning = w;
            }
            REQUIRE(voice_warning.find("not in the Dolby profile, left out: ") != npos);
            REQUIRE(voice_warning.find("objectDivergence") != npos);
            REQUIRE(voice_warning.find("screenRef") != npos);
            REQUIRE(voice_warning.find("diffuse rounded to 0 or 1") != npos);
            REQUIRE(voice_warning.find("an exclusion zone that is not one of the profile's") != npos);
            REQUIRE(voice_warning.find("width, height and depth differ") != npos);
            REQUIRE(fx_warning.find("a position outside the cube was clamped to -1..1") != npos);
            REQUIRE(fx_warning.find("the channelLock maxDistance") != npos);
        }
    }

    GIVEN("a bed that is not one of the profile's configurations") {
        admio::captured_programme captured;
        captured.profile = admio::adm_profile::dolby;
        const char* labels[] = { "M+030", "M-030", "M+110" };
        for (const char* label : labels) {
            admio::captured_direct_channel ch;
            ch.labels = { label };
            captured.bed.channels.push_back(ch);
        }
        admio::captured_direct_channel odd;
        odd.labels = { "B+000" };
        odd.has_position = true;
        odd.azimuth = 0.0;
        odd.elevation = -30.0;
        captured.bed.channels.push_back(odd);
        std::vector<bw64::AudioId> chna_ids;
        std::vector<std::string> warnings;
        auto doc = admio::build_document(captured, 1.0, chna_ids, warnings, admio::audio_format{ 44100, 16 });
        const std::string xml = admio::to_xml(doc);
        INFO(xml);

        THEN("the known channels are written as the profile's, the other as captured, and the problems are reported") {
            REQUIRE(xml.find("audioChannelFormatName=\"RoomCentricLeftSurround\"") != npos);
            REQUIRE(xml.find("<speakerLabel>B+000</speakerLabel>") != npos);
            REQUIRE(xml.find("audioChannelFormatName=\"bed B+000\"") != npos);
            REQUIRE(contains(warnings, "the Dolby profile takes 48000 or 96000 Hz audio, not 44100"));
            REQUIRE(contains(warnings, "the Dolby profile takes 24-bit audio, not 16"));
            bool configuration = false, label = false;
            for (const auto& w : warnings) {
                if (w.find("L R Ls B+000 is not one of the profile's channel configurations") != npos) configuration = true;
                if (w.find("channel 4 (B+000) is not one of the profile's bed channels") != npos) label = true;
            }
            REQUIRE(configuration);
            REQUIRE(label);
        }
    }

    GIVEN("an instance writing with the Dolby profile") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.chans = 1;
        obj.directchans = 2;
        obj.hoa(atoms{ symbol("order"), -1 });
        obj.profile = "dolby";
        REQUIRE(obj.profile == symbol("dolby"));
        obj.profile = "atmos";    // not a profile: kept
        REQUIRE(obj.profile == symbol("dolby"));
        obj.direct(atoms{ symbol("inputlayout"), symbol("0+2+0") });
        obj.setvalue(atoms{ 1, symbol("azimuth"), 30.0 });

        WHEN("the capture is written and read back") {
            const std::string audio = write_audio("dolby_write_audio.wav", 3, 4800);
            const std::string out = std::string(EARMAX_TEST_OUT_DIR) + "/dolby_write.wav";
            std::remove(out.c_str());
            obj.write(atoms{ symbol(out), symbol(audio) });
            REQUIRE(contains(messages(obj, k_info), "written " + out + " 3 4800"));

            test_wrapper<ear_adm> another_instance;
            ear_adm& reader = another_instance;
            reader.read(atoms{ symbol(out) });
            REQUIRE(reader.loaded());

            THEN("the file is a Dolby-shaped master that reads back as a bed at Dolby's positions and a Cartesian object") {
                {
                    std::ifstream file(out, std::ios::binary);
                    char id[4] = { 0, 0, 0, 0 };
                    file.read(id, 4);
                    REQUIRE(std::string(id, 4) == "RIFF");    // RF64 only from 4 GB
                }
                const auto& items = reader.items();
                REQUIRE(items.warnings.empty());
                REQUIRE(items.direct.size() == 2);
                REQUIRE(items.direct[0].labels == std::vector<std::string>{ "M+030" });
                REQUIRE(items.direct[0].cartesian);
                REQUIRE(items.direct[0].x == Approx(-1.0));
                REQUIRE(items.direct[0].y == Approx(1.0));
                REQUIRE(items.direct[0].z == Approx(0.0));
                REQUIRE(items.direct[0].pack_id == "AP_00011001");
                REQUIRE(items.direct[1].labels == std::vector<std::string>{ "M-030" });
                REQUIRE(items.objects.size() == 1);
                REQUIRE(items.objects[0].blocks.size() == 1);
                REQUIRE(items.objects[0].blocks[0].state.cartesian);
                REQUIRE(items.objects[0].blocks[0].state.x < 0.0);
                REQUIRE(items.objects[0].blocks[0].state.y > 0.0);
                REQUIRE(contains(messages(reader, k_direct), "setvalue 1 cartesian 1"));
                REQUIRE(contains(messages(reader, k_direct), "setvalue 1 position -1 1 0"));
            }
        }
    }
}

namespace {

/// A BW64 file with the given ADM XML and chna entries and silent audio, as
/// the EBU's test files are shaped: the audioTrackUIDs reference nothing in
/// the XML, the chna chunk names their track and pack formats.
std::string write_described_by_chna(const std::string& name, const std::string& xml, const std::vector<bw64::AudioId>& ids,
                                    uint16_t channels)
{
    const std::string path = std::string(EARMAX_TEST_OUT_DIR) + "/" + name;
    std::remove(path.c_str());
    auto chna = std::make_shared<bw64::ChnaChunk>();
    for (const auto& id : ids) {
        chna->addAudioId(id);
    }
    auto axml = std::make_shared<bw64::AxmlChunk>(xml);
    auto writer = bw64::writeFile(path, channels, 48000, 24, chna, axml);
    std::vector<float> silence(4800 * channels, 0.0f);
    writer->write(silence.data(), 4800);
    writer->close();
    return path;
}

const char* k_chna_described_xml = R"(<?xml version="1.0" encoding="UTF-8"?>
<ebuCoreMain xmlns="urn:ebu:metadata-schema:ebuCore" xml:lang="en">
  <coreMetadata>
    <format>
      <audioFormatExtended>
        <audioProgramme audioProgrammeID="APR_1001" audioProgrammeName="Described">
          <audioContentIDRef>ACO_1001</audioContentIDRef>
        </audioProgramme>
        <audioContent audioContentID="ACO_1001" audioContentName="Described">
          <audioObjectIDRef>AO_1001</audioObjectIDRef>
          <audioObjectIDRef>AO_1002</audioObjectIDRef>
        </audioContent>
        <audioObject audioObjectID="AO_1001" audioObjectName="Stereo">
          <audioPackFormatIDRef>AP_00010002</audioPackFormatIDRef>
          <audioTrackUIDRef>ATU_00000001</audioTrackUIDRef>
          <audioTrackUIDRef>ATU_00000002</audioTrackUIDRef>
        </audioObject>
        <audioObject audioObjectID="AO_1002" audioObjectName="Noise">
          <audioPackFormatIDRef>AP_00031001</audioPackFormatIDRef>
          <audioTrackUIDRef>ATU_00000003</audioTrackUIDRef>
        </audioObject>
        <audioPackFormat audioPackFormatID="AP_00031001" audioPackFormatName="Noise" typeLabel="0003" typeDefinition="Objects">
          <audioChannelFormatIDRef>AC_00031001</audioChannelFormatIDRef>
        </audioPackFormat>
        <audioChannelFormat audioChannelFormatID="AC_00031001" audioChannelFormatName="Noise" typeLabel="0003" typeDefinition="Objects">
          <audioBlockFormat audioBlockFormatID="AB_00031001_00000001">
            <position coordinate="azimuth">45.00</position>
            <position coordinate="elevation">0.00</position>
            <position coordinate="distance">1.00</position>
          </audioBlockFormat>
        </audioChannelFormat>
        <audioTrackUID UID="ATU_00000001" sampleRate="48000" bitDepth="24"/>
        <audioTrackUID UID="ATU_00000002" sampleRate="48000" bitDepth="24"/>
        <audioTrackUID UID="ATU_00000003" sampleRate="48000" bitDepth="24"/>
      </audioFormatExtended>
    </format>
  </coreMetadata>
</ebuCoreMain>
)";

} // namespace

SCENARIO("ear.adm reads files whose tracks are described by the chna chunk only") {
    ext_main(nullptr);

    GIVEN("a file whose audioTrackUIDs reference nothing, with the formats in the chna chunk, as the EBU's test files") {
        const std::string path = write_described_by_chna("chna_described.wav", k_chna_described_xml,
                                                         { bw64::AudioId(1, "ATU_00000001", "AT_00010001_01", "AP_00010002"),
                                                           bw64::AudioId(2, "ATU_00000002", "AT_00010002_01", "AP_00010002"),
                                                           bw64::AudioId(3, "ATU_00000003", "AT_00031001_01", "AP_00031001") },
                                                         3);
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(path) });
        REQUIRE(obj.loaded());

        THEN("the bed's channels come from the chna's track formats and the object's from its pack") {
            const auto& items = obj.items();
            REQUIRE(items.warnings.empty());
            REQUIRE(items.direct.size() == 2);
            REQUIRE(items.direct[0].track == 0);
            REQUIRE(items.direct[0].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:M+030" });
            REQUIRE(items.direct[0].pack_id == "AP_00010002");
            REQUIRE(items.direct[1].track == 1);
            REQUIRE(items.direct[1].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:M-030" });
            REQUIRE(items.objects.size() == 1);
            REQUIRE(items.objects[0].track == 2);
            REQUIRE(items.objects[0].blocks.size() == 1);
            REQUIRE(items.objects[0].blocks[0].state.azimuth == Approx(45.0));
        }
    }

    GIVEN("the same file with a chna chunk that names no formats") {
        const std::string path = write_described_by_chna("chna_bare.wav", k_chna_described_xml,
                                                         { bw64::AudioId(1, "ATU_00000001", "", ""),
                                                           bw64::AudioId(2, "ATU_00000002", "", ""),
                                                           bw64::AudioId(3, "ATU_00000003", "", "") },
                                                         3);
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(path) });
        REQUIRE(obj.loaded());

        THEN("the UIDs stand for the channels of the objects' packs in order") {
            const auto& items = obj.items();
            REQUIRE(items.warnings.empty());
            REQUIRE(items.direct.size() == 2);
            REQUIRE(items.direct[0].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:M+030" });
            REQUIRE(items.direct[1].labels == std::vector<std::string>{ "urn:itu:bs:2051:0:speaker:M-030" });
            REQUIRE(items.objects.size() == 1);
            REQUIRE(items.objects[0].blocks[0].state.azimuth == Approx(45.0));
        }
    }
}

SCENARIO("ear.adm scans an overview of the read file on its own thread") {
    ext_main(nullptr);

    GIVEN("an instance that read the parity fixture") {
        test_wrapper<ear_adm> an_instance;
        ear_adm& obj = an_instance;
        obj.read(atoms{ symbol(k_fixture) });
        REQUIRE(obj.loaded());

        WHEN("an overview is asked for at 100 bins per second") {
            obj.overview(atoms{ symbol("ov"), 100 });
            const auto deadline = std::chrono::steady_clock::now() + std::chrono::seconds(5);
            while (!obj.overview_ready() && std::chrono::steady_clock::now() < deadline) {
                std::this_thread::sleep_for(std::chrono::milliseconds(1));
            }
            REQUIRE(obj.overview_ready());
            obj.flush_overview();    // the main thread's part (the mock kernel has no buffer~, so the write reports)
            THEN("the 12 tracks of 4800 frames give ten bins each") {
                const auto& ov = obj.last_overview();
                REQUIRE(ov.channels == 12);
                REQUIRE(ov.bins == 10);
                REQUIRE(ov.buffer_rate() == Approx(200.0));
                REQUIRE(ov.data.size() == 10 * 2 * 12);
            }
        }

        WHEN("an overview is asked for without a buffer~ name") {
            obj.overview(atoms{});
            THEN("no scan starts") {
                REQUIRE(!obj.overview_ready());
            }
        }
    }
}

EARMAX_TEST_GENERATE_MAXREF(ear_adm, "ear.adm")
