/// @file
/// @brief   ear.adm: read and write ADM (BW64) files alongside the renderers.
///          Reading resolves the file's rendering items like the EAR and
///          emits the renderer messages for a time position; writing captures
///          the object metadata messages a patch sends to the renderers and
///          combines them with recorded audio into a BW64 file with ADM.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_adm_player.h"

#include <cmath>
#include <fstream>
#include <limits>
#include <memory>

using namespace earmax;

class ear_adm : public object<ear_adm> {
public:
    MIN_DESCRIPTION{ "Read and write ADM files (BW64 with ADM metadata) alongside the renderers. 'read' loads a file's "
                     "ADM, reports its rendering items and which file tracks carry them, and 'time', 'start' or 'seek' "
                     "emit the metadata of the Objects items as mc.ear.objects~ messages with the EAR's interpolation "
                     "rules (a 'setvalue N ramp' message precedes each block). DirectSpeakers beds and HOA scenes are "
                     "emitted as mc.ear.direct~ and mc.ear.hoa~ messages when the file is read. For writing, 'record' "
                     "captures the object messages sent to this object, and 'write' combines the captured timeline "
                     "with an audio file recorded by mc.sfrecord~ into a BW64 file with ADM metadata." };
    MIN_TAGS{ "spatial audio, ADM, files" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~, mc.ear.select~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    // reading: the file, its items and their emission live in the player
    // shared with mc.ear.play~; the transport (scheduler timing) is here
    admio::item_player m_player;
    bool m_running{ false };

    // capturing
    struct capture_slot {
        std::string name;
        admio::object_state state;
        double ramp_ms{ -1.0 };    // per-object interpolation time; negative = the ramp attribute
        std::vector<admio::captured_block> blocks;
    };
    std::vector<capture_slot> m_slots;
    bool m_capturing{ false };
    double m_capture_origin{ 0.0 };    // scheduler time (ms) when the capture started
    double m_capture_last{ 0.0 };      // last captured time in seconds

public:
    inlet<> in_main{ this, "(read/time/start/stop/seek) play a file's metadata; (record/write/setvalue...) capture metadata" };
    outlet<> out_objects{ this, "(messages) for mc.ear.objects~: tracks, setvalue N ramp/parameters" };
    outlet<> out_direct{ this, "(messages) for mc.ear.direct~: tracks, setvalue N speakerlabel/position/lfe/packformat" };
    outlet<> out_hoa{ this, "(messages) for mc.ear.hoa~: tracks, order, normalization" };
    outlet<> out_info{ this, "(messages) file, programme, item and warning reports, position, end" };

    ear_adm(const atoms& args = {})
    {
        resize_slots(static_cast<size_t>(static_cast<int>(chans)));
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<number> ramp{ this, "ramp", 10.0,
        description{ "Default interpolation time in milliseconds written for captured changes, as the renderer's "
                     "ramp attribute; 'setvalue N ramp ms' overrides it per object (a negative value returns to it)." },
        setter{ MIN_FUNCTION {
            return { std::max(0.0, static_cast<double>(args[0])) };
        } } };

    attribute<int> chans{ this, "chans", 16,
        description{ "Number of objects captured for writing (one per audio track of the file written)." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(1, std::min(n, 1024));
            resize_slots(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<symbol> programmename{ this, "programmename", "libear-max",
        description{ "Name of the audioProgramme written." } };

    // ------------------------------------------------------------------
    // reading
    // ------------------------------------------------------------------

    message<> read{ this, "read",
        "Read an ADM (BW64) file: 'read path'. Reports the file, its programmes and rendering items on the info outlet, "
        "sends the track lists and static metadata to the renderer outlets and emits the object metadata for time 0.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "read needs a file path" << endl;
                return {};
            }
            load(admio::resolve_path(std::string(args[0]), true));
            return {};
        } };

    message<> programme{ this, "programme",
        "Select the audioProgramme to render by index (1-based) when the file has several, and re-read the items.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "programme needs an index (1-based)" << endl;
                return {};
            }
            select_programme(std::max(0, static_cast<int>(static_cast<double>(args[0])) - 1));
            return {};
        } };

    message<> dump{ this, "dump", "Report the file, its programmes, rendering items and warnings on the info outlet.",
        MIN_FUNCTION {
            m_player.report(sinks());
            return {};
        } };

    message<> time{ this, "time",
        "Emit the object metadata for a time position in milliseconds ('time 1500'), as the renderer messages for the "
        "blocks active at that time. Only blocks that changed since the last emission are sent.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "time needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            if (ms < m_player.position() * 1000.0) {
                m_player.reset_emitted();    // going back in time: re-emit everything as a jump
            }
            m_player.set_position(ms / 1000.0);
            m_player.emit(m_player.position(), false, sinks());
            return {};
        } };

    message<> start{ this, "start",
        "Start the transport: emits the object metadata at every block boundary from the current position, on Max's "
        "scheduler, until the end of the file. Send 'start' to mc.sfplay~ at the same time to play the audio.",
        MIN_FUNCTION {
            if (!m_player.loaded()) {
                cerr << "no file read" << endl;
                return {};
            }
            m_running = true;
            m_player.reset_emitted();
            m_player.emit(m_player.position(), true, sinks());
            schedule_next();
            return {};
        } };

    message<> stop{ this, "stop", "Stop the transport (and a running capture).",
        MIN_FUNCTION {
            m_running = false;
            if (m_timer) {
                m_timer->stop();
            }
            if (m_capturing) {
                m_capturing = false;
                out_info.send("captured", static_cast<int>(m_slots.size()), m_capture_last * 1000.0);
            }
            return {};
        } };

    message<> seek{ this, "seek", "Move the transport to a position in milliseconds ('seek 0' rewinds) and emit the metadata there.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "seek needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            m_player.set_position(ms / 1000.0);
            m_player.reset_emitted();
            m_player.emit(m_player.position(), true, sinks());
            if (m_running) {
                schedule_next();
            }
            return {};
        } };

    // ------------------------------------------------------------------
    // writing
    // ------------------------------------------------------------------

    message<> record{ this, "record",
        "Start capturing the object messages sent to this object (setvalue, applyvalues, parameters, lists), "
        "timestamped from now; the current state of every object becomes its first block. Stop with 'stop'.",
        MIN_FUNCTION {
            begin_capture(now_ms());
            return {};
        } };

    message<> clear{ this, "clear", "Discard the captured timeline and reset every object's parameters.",
        MIN_FUNCTION {
            m_capturing = false;
            for (auto& slot : m_slots) {
                slot.blocks.clear();
                slot.state = admio::object_state();
                slot.ramp_ms = -1.0;
            }
            m_capture_last = 0.0;
            return {};
        } };

    message<> name{ this, "name", "Name an object for writing: 'name N symbol' (N is 1-based).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "name needs an object number and a name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 1 || static_cast<size_t>(index) > m_slots.size()) {
                cerr << "name: object number out of range 1.." << m_slots.size() << endl;
                return {};
            }
            m_slots[static_cast<size_t>(index - 1)].name = std::string(args[1]);
            return {};
        } };

    message<> write{ this, "write",
        "Write a BW64 file with the captured timeline as ADM metadata: 'write out.wav in.wav' copies the audio of "
        "in.wav (one track per object, recorded with mc.sfrecord~ for example) into out.wav with the chna and axml chunks.",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_symbol(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "write needs the output path and the path of the recorded audio" << endl;
                return {};
            }
            const std::string out = admio::resolve_path(std::string(args[0]), false);
            const std::string in = admio::resolve_path(std::string(args[1]), true);
            try {
                auto reader = bw64::readFile(in);
                const double length = static_cast<double>(reader->numberOfFrames()) / reader->sampleRate();
                const size_t objects = std::min<size_t>(m_slots.size(), reader->channels());
                if (reader->channels() < m_slots.size()) {
                    cerr << "the audio file has " << reader->channels() << " channels; only the first " << objects
                         << " objects are written" << endl;
                }
                std::vector<bw64::AudioId> chna_ids;
                auto doc = admio::build_document(programme_name(), captured_objects(objects, length), length, chna_ids);
                reader.reset();
                const uint64_t frames = admio::write_file(out, in, doc, chna_ids);
                out_info.send("written", symbol(out), static_cast<int>(objects), static_cast<double>(frames));
            }
            catch (const std::exception& e) {
                cerr << "write: " << e.what() << endl;
            }
            return {};
        } };

    message<> writexml{ this, "writexml",
        "Write the captured timeline as an ADM XML file: 'writexml out.xml [length seconds]' (for inspection, or "
        "for tools that take the metadata separately).",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "writexml needs an output path" << endl;
                return {};
            }
            double length = m_capture_last;
            if (args.size() > 1 && atom_is_numeric(args[1])) {
                length = std::max(0.0, static_cast<double>(args[1]));
            }
            try {
                std::vector<bw64::AudioId> chna_ids;
                auto doc = admio::build_document(programme_name(), captured_objects(m_slots.size(), length), length, chna_ids);
                std::ofstream file(admio::resolve_path(std::string(args[0]), false));
                if (!file) {
                    throw std::runtime_error("cannot open the file for writing");
                }
                file << admio::to_xml(doc);
                out_info.send("written", args[0], static_cast<int>(m_slots.size()));
            }
            catch (const std::exception& e) {
                cerr << "writexml: " << e.what() << endl;
            }
            return {};
        } };

    message<> setvalue{ this, "setvalue",
        "Captured object metadata, in the mc.ear.objects~ format: 'setvalue N parameter values...' (N is 1-based; 0 "
        "sets all objects). Parameters: azimuth elevation distance x y z cartesian position width height depth gain "
        "diffuse channellock channellock_distance divergence divergence_range screenref screenedgelock_h "
        "screenedgelock_v, and ramp (the interpolation time written for the next changes of that object; negative "
        "returns to the ramp attribute).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "setvalue needs an object number (1-based, 0 for all) and a parameter name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 0 || static_cast<size_t>(index) > m_slots.size()) {
                cerr << "setvalue: object number out of range 0.." << m_slots.size() << endl;
                return {};
            }
            const std::string parameter = args[1];
            const atoms values(args.begin() + 2, args.end());
            if (index == 0) {
                capture_all(parameter, values);
            }
            else {
                capture_one(static_cast<size_t>(index - 1), parameter, values);
            }
            return {};
        } };

    message<> applyvalues{ this, "applyvalues",
        "Captured object metadata: 'applyvalues parameter v1 v2 v3 ...' spreads values over the objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "applyvalues needs a parameter name followed by one value per object" << endl;
                return {};
            }
            const std::string parameter = args[0];
            const size_t n = std::min(args.size() - 1, m_slots.size());
            for (size_t i = 0; i < n; ++i) {
                capture_one(i, parameter, atoms{ args[i + 1] });
            }
            return {};
        } };

    message<> anything{ this, "anything", "Captured object metadata: any parameter sent as a message applies to all objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                return {};
            }
            capture_all(std::string(args[0]), atoms(args.begin() + 1, args.end()));
            return {};
        } };

    message<> list{ this, "list", "Captured object metadata: a list sets the position of all objects.",
        MIN_FUNCTION {
            capture_all("position", args);
            return {};
        } };

    // ------------------------------------------------------------------
    // transport timer
    // ------------------------------------------------------------------

    // delivered on Max's main thread, like the messages that share the
    // transport state (the renderers' messages are deferred there anyway).
    // Created on first use: Min's mock kernel (the unit tests) starts a
    // thread for every clock before the clock's own mutexes exist, which
    // can abort the test binary; the tests step the transport without it.
    using transport_timer = timer<timer_options::defer_delivery>;
    std::unique_ptr<transport_timer> m_timer;

    transport_timer& transport()
    {
        if (!m_timer) {
            m_timer = std::make_unique<transport_timer>(this, MIN_FUNCTION {
                on_tick();
                return {};
            });
        }
        return *m_timer;
    }

    // ------------------------------------------------------------------
    // state access (tests)
    // ------------------------------------------------------------------

    bool loaded() const
    {
        return m_player.loaded();
    }

    const admio::selection& items() const
    {
        return m_player.items();
    }

    const admio::file_info& info() const
    {
        return m_player.info();
    }

    double position() const
    {
        return m_player.position();
    }

    /// capture a message at an explicit scheduler time (ms), for tests and
    /// for hosts that timestamp messages themselves
    void capture_at(double scheduler_ms, const std::string& parameter, long index, const atoms& values)
    {
        m_capture_time_override = scheduler_ms;
        if (index == 0) {
            capture_all(parameter, values);
        }
        else {
            capture_one(static_cast<size_t>(index - 1), parameter, values);
        }
        m_capture_time_override = -1.0;
    }

    void begin_capture_at(double scheduler_ms)
    {
        begin_capture(scheduler_ms);
    }

    const std::vector<admio::captured_block>& captured(size_t i) const
    {
        return m_slots[i].blocks;
    }

    bool running() const
    {
        return m_running;
    }

    /// the transport step the timer performs
    void on_tick()
    {
        advance(true);
    }

    /// one transport step without the scheduler (tests): the next block
    /// boundary is emitted as the timer would
    void step()
    {
        if (!m_player.loaded()) {
            return;
        }
        m_running = true;
        advance(false);
    }

private:
    double m_capture_time_override{ -1.0 };

    static bool same_time(double a, double b)
    {
        return std::abs(a - b) < 1e-6;
    }

    std::string programme_name() const
    {
        const symbol name = programmename;
        return name;
    }

    double now_ms() const
    {
        if (m_capture_time_override >= 0.0) {
            return m_capture_time_override;
        }
        return static_cast<double>(c74::max::gettime());
    }

    /// where the transport ends: the end of the audio, or of the last block
    /// when the metadata outlasts the audio
    // ---- reading -----------------------------------------------------

    /// the outlets as the shared player sends to them
    admio::message_sinks sinks()
    {
        admio::message_sinks out;
        out.objects = [this](const atoms& a) { out_objects.send(a); };
        out.direct = [this](const atoms& a) { out_direct.send(a); };
        out.hoa = [this](const atoms& a) { out_hoa.send(a); };
        out.info = [this](const atoms& a) { out_info.send(a); };
        return out;
    }

    void load(const std::string& path)
    {
        m_running = false;
        if (m_timer) {
                m_timer->stop();
            }
        try {
            m_player.load(path);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            m_player.report(sinks());    // "file none": the previous file is gone too
            return;
        }
        announce();
    }

    void select_programme(int index)
    {
        if (!m_player.loaded()) {
            m_player.select(index);    // remembered for the next file
            return;
        }
        try {
            m_player.select(index);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            return;
        }
        announce();
    }

    /// report the file and send the static metadata and the blocks active
    /// at the current position
    void announce()
    {
        const auto out = sinks();
        m_player.report(out);
        m_player.send_static(out, true);
        m_player.emit(m_player.position(), true, out);
    }

    /// emit the next block boundary; `arm` schedules the one after it
    void advance(bool arm)
    {
        if (!m_running || !m_player.loaded()) {
            return;
        }
        const double next = m_player.next_boundary(m_player.position());
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_player.position() * 1000.0);
            return;
        }
        m_player.set_position(next);
        m_player.emit(next, false, sinks());
        out_info.send("position", next * 1000.0);
        if (admio::item_player::same_time(next, m_player.end_time())) {
            m_running = false;
            out_info.send("end", next * 1000.0);
            return;
        }
        if (arm) {
            schedule_next();
        }
    }

    void schedule_next()
    {
        const double next = m_player.next_boundary(m_player.position());
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_player.position() * 1000.0);
            return;
        }
        transport().delay((next - m_player.position()) * 1000.0);
    }

    // ---- capturing ---------------------------------------------------

    void resize_slots(size_t n)
    {
        const size_t old = m_slots.size();
        m_slots.resize(n);
        for (size_t i = old; i < n; ++i) {
            m_slots[i].name = "object " + std::to_string(i + 1);
        }
    }

    void begin_capture(double scheduler_ms)
    {
        m_capture_origin = scheduler_ms;
        m_capture_last = 0.0;
        m_capturing = true;
        for (auto& slot : m_slots) {
            slot.blocks.clear();
            slot.blocks.push_back({ 0.0, 0.0, slot.state });
        }
    }

    void record_change(size_t i)
    {
        if (!m_capturing) {
            return;
        }
        capture_slot& slot = m_slots[i];
        const double t = std::max(0.0, (now_ms() - m_capture_origin) / 1000.0);
        const double ramp_seconds = (slot.ramp_ms < 0.0 ? static_cast<double>(ramp) : slot.ramp_ms) / 1000.0;
        m_capture_last = std::max(m_capture_last, t);
        if (!slot.blocks.empty() && same_time(slot.blocks.back().time, t)) {
            slot.blocks.back().state = slot.state;    // several parameters at the same time: one block
            slot.blocks.back().ramp = ramp_seconds;
            return;
        }
        slot.blocks.push_back({ t, ramp_seconds, slot.state });
    }

    void capture_one(size_t i, const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (apply_parameter(m_slots[i], parameter, values, error)) {
            if (parameter != "ramp") {
                record_change(i);
            }
        }
        else {
            cerr << "object " << (i + 1) << ": " << error << endl;
        }
    }

    void capture_all(const std::string& parameter, const atoms& values)
    {
        for (size_t i = 0; i < m_slots.size(); ++i) {
            std::string error;
            if (!apply_parameter(m_slots[i], parameter, values, error)) {
                if (i == 0) {
                    cerr << error << endl;
                }
                return;
            }
            if (parameter != "ramp") {
                record_change(i);
            }
        }
    }

    static bool number_at(const atoms& values, size_t i, double& out, std::string& error, const char* what)
    {
        if (values.size() <= i || !atom_is_numeric(values[i]) || !std::isfinite(static_cast<double>(values[i]))) {
            error = std::string(what) + " needs a finite number";
            return false;
        }
        out = static_cast<double>(values[i]);
        return true;
    }

    /// apply one mc.ear.objects~ parameter to a captured object's state
    static bool apply_parameter(capture_slot& slot, const std::string& name, const atoms& values, std::string& error)
    {
        admio::object_state& s = slot.state;
        double v = 0.0;
        if (name == "azimuth") return number_at(values, 0, s.azimuth, error, "azimuth");
        if (name == "elevation") return number_at(values, 0, s.elevation, error, "elevation");
        if (name == "distance") return number_at(values, 0, s.distance, error, "distance");
        if (name == "x") return number_at(values, 0, s.x, error, "x");
        if (name == "y") return number_at(values, 0, s.y, error, "y");
        if (name == "z") return number_at(values, 0, s.z, error, "z");
        if (name == "width") return number_at(values, 0, s.width, error, "width");
        if (name == "height") return number_at(values, 0, s.height, error, "height");
        if (name == "depth") return number_at(values, 0, s.depth, error, "depth");
        if (name == "gain") return number_at(values, 0, s.gain, error, "gain");
        if (name == "diffuse") return number_at(values, 0, s.diffuse, error, "diffuse");
        if (name == "channellock_distance") return number_at(values, 0, s.channellock_distance, error, "channellock_distance");
        if (name == "divergence") return number_at(values, 0, s.divergence, error, "divergence");
        if (name == "divergence_range") return number_at(values, 0, s.divergence_range, error, "divergence_range");
        if (name == "ramp") {
            if (!number_at(values, 0, v, error, "ramp")) return false;
            slot.ramp_ms = v < 0.0 ? -1.0 : v;    // negative: back to the ramp attribute, like the renderers
            return true;
        }
        if (name == "cartesian" || name == "channellock" || name == "screenref") {
            if (!number_at(values, 0, v, error, name.c_str())) return false;
            const bool flag = v != 0.0;
            if (name == "cartesian") s.cartesian = flag;
            else if (name == "channellock") s.channellock = flag;
            else s.screenref = flag;
            return true;
        }
        if (name == "screenedgelock_h" || name == "screenedgelock_v") {
            if (values.empty() || !atom_is_symbol(values[0])) {
                error = name + " needs a symbol";
                return false;
            }
            const std::string edge = values[0];
            if (name == "screenedgelock_h") {
                if (edge != "none" && edge != "left" && edge != "right") { error = "screenedgelock_h must be none, left or right"; return false; }
                s.screenedgelock_h = edge;
            }
            else {
                if (edge != "none" && edge != "top" && edge != "bottom") { error = "screenedgelock_v must be none, top or bottom"; return false; }
                s.screenedgelock_v = edge;
            }
            return true;
        }
        if (name == "position" || name == "list") {
            if (values.size() < 2) {
                error = "position needs at least 2 numbers: azimuth elevation [distance] or x y z";
                return false;
            }
            double a = 0.0, b = 0.0, c = s.cartesian ? s.z : s.distance;
            if (!number_at(values, 0, a, error, "position") || !number_at(values, 1, b, error, "position")) return false;
            if (values.size() > 2 && !number_at(values, 2, c, error, "position")) return false;
            if (s.cartesian) { s.x = a; s.y = b; s.z = c; }
            else { s.azimuth = a; s.elevation = b; s.distance = c; }
            return true;
        }
        if (name == "zone") {
            error = "zone exclusion cannot be written (not supported by libadm); ignored";
            return false;
        }
        error = "unknown parameter: " + name;
        return false;
    }

    std::vector<admio::captured_object> captured_objects(size_t count, double length) const
    {
        std::vector<admio::captured_object> objects;
        for (size_t i = 0; i < count && i < m_slots.size(); ++i) {
            admio::captured_object o;
            o.name = m_slots[i].name;
            o.blocks = m_slots[i].blocks;
            if (o.blocks.empty()) {
                o.blocks.push_back({ 0.0, 0.0, m_slots[i].state });    // never captured: a static object
            }
            objects.push_back(std::move(o));
        }
        (void)length;
        return objects;
    }
};
