/// @file
/// @brief   ear.adm: read and write ADM (BW64) files alongside the renderers.
///          Reading resolves the file's rendering items like the EAR and
///          emits the renderer messages for a time position; writing captures
///          the object metadata messages a patch sends to the renderers and
///          combines them with recorded audio into a BW64 file with ADM.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_adm.h"

#include <cmath>
#include <fstream>
#include <limits>

using namespace earmax;

class ear_adm : public object<ear_adm> {
public:
    MIN_DESCRIPTION{ "Read and write ADM files (BW64 with ADM metadata) alongside the renderers. 'read' loads a file's "
                     "ADM, reports its rendering items and which file tracks carry them, and 'time', 'start' or 'seek' "
                     "emit the metadata of the Objects items as mc.ear.objects~ messages with the EAR's interpolation "
                     "rules (a 'setvalue N ramp' message precedes each block). DirectSpeakers beds and HOA scenes are "
                     "emitted as mc.ear.direct~ and mc.ear.hoa~ messages when the file is read. For writing, 'record' "
                     "captures the object messages sent to this object, and 'write' combines the captured timeline "
                     "with an audio file recorded by mc.sfrecord~ into a BW64 file with ADM metadata." };
    MIN_TAGS{ "spatial audio, ADM, files" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~, mc.ear.select~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    // reading
    admio::loaded_file m_file;
    admio::selection m_items;
    bool m_loaded{ false };
    int m_programme{ 0 };
    std::vector<int> m_emitted;    // per Objects item: index of the last emitted block, -1 for none
    double m_position{ 0.0 };      // transport position in seconds
    bool m_running{ false };

    // capturing
    struct capture_slot {
        std::string name;
        admio::object_state state;
        double ramp_ms{ 10.0 };
        std::vector<admio::captured_block> blocks;
    };
    std::vector<capture_slot> m_slots;
    bool m_capturing{ false };
    double m_capture_origin{ 0.0 };    // scheduler time (ms) when the capture started
    double m_capture_last{ 0.0 };      // last captured time in seconds

public:
    inlet<> in_main{ this, "(read/time/start/stop/seek) play a file's metadata; (record/write/setvalue...) capture metadata" };
    outlet<> out_objects{ this, "(messages) for mc.ear.objects~: tracks, setvalue N ramp/parameters" };
    outlet<> out_direct{ this, "(messages) for mc.ear.direct~: tracks, setvalue N speakerlabel/position/lfe/packformat" };
    outlet<> out_hoa{ this, "(messages) for mc.ear.hoa~: tracks, order, normalization" };
    outlet<> out_info{ this, "(messages) file, programme, item and warning reports, position, end" };

    ear_adm(const atoms& args = {})
    {
        resize_slots(static_cast<size_t>(static_cast<int>(chans)));
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<int> chans{ this, "chans", 16,
        description{ "Number of objects captured for writing (one per audio track of the file written)." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(1, std::min(n, 1024));
            resize_slots(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<number> ramp{ this, "ramp", 10.0,
        description{ "Default interpolation time in milliseconds written for captured changes, as the renderer's "
                     "ramp attribute; 'setvalue N ramp ms' overrides it per object." },
        setter{ MIN_FUNCTION {
            const double ms = std::max(0.0, static_cast<double>(args[0]));
            for (auto& slot : m_slots) {
                slot.ramp_ms = ms;
            }
            return { ms };
        } } };

    attribute<symbol> programmename{ this, "programmename", "libear-max",
        description{ "Name of the audioProgramme written." } };

    // ------------------------------------------------------------------
    // reading
    // ------------------------------------------------------------------

    message<> read{ this, "read",
        "Read an ADM (BW64) file: 'read path'. Reports the file, its programmes and rendering items on the info outlet, "
        "sends the track lists and static metadata to the renderer outlets and emits the object metadata for time 0.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "read needs a file path" << endl;
                return {};
            }
            load(resolve_path(std::string(args[0]), true));
            return {};
        } };

    message<> programme{ this, "programme",
        "Select the audioProgramme to render by index (1-based) when the file has several, and re-read the items.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "programme needs an index (1-based)" << endl;
                return {};
            }
            m_programme = std::max(0, static_cast<int>(static_cast<double>(args[0])) - 1);
            if (m_loaded) {
                select();
            }
            return {};
        } };

    message<> dump{ this, "dump", "Report the file, its programmes, rendering items and warnings on the info outlet.",
        MIN_FUNCTION {
            report();
            return {};
        } };

    message<> time{ this, "time",
        "Emit the object metadata for a time position in milliseconds ('time 1500'), as the renderer messages for the "
        "blocks active at that time. Only blocks that changed since the last emission are sent.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "time needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            if (ms < m_position * 1000.0) {
                reset_emitted();    // going back in time: re-emit everything as a jump
            }
            m_position = std::max(0.0, ms) / 1000.0;
            emit_objects(m_position, false);
            return {};
        } };

    message<> start{ this, "start",
        "Start the transport: emits the object metadata at every block boundary from the current position, on Max's "
        "scheduler, until the end of the file. Send 'start' to mc.sfplay~ at the same time to play the audio.",
        MIN_FUNCTION {
            if (!m_loaded) {
                cerr << "no file read" << endl;
                return {};
            }
            m_running = true;
            reset_emitted();
            emit_objects(m_position, true);
            schedule_next();
            return {};
        } };

    message<> stop{ this, "stop", "Stop the transport (and a running capture).",
        MIN_FUNCTION {
            m_running = false;
            m_timer.stop();
            if (m_capturing) {
                m_capturing = false;
                out_info.send("captured", static_cast<int>(m_slots.size()), m_capture_last * 1000.0);
            }
            return {};
        } };

    message<> seek{ this, "seek", "Move the transport to a position in milliseconds ('seek 0' rewinds) and emit the metadata there.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "seek needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            m_position = std::max(0.0, ms) / 1000.0;
            reset_emitted();
            emit_objects(m_position, true);
            if (m_running) {
                schedule_next();
            }
            return {};
        } };

    // ------------------------------------------------------------------
    // writing
    // ------------------------------------------------------------------

    message<> record{ this, "record",
        "Start capturing the object messages sent to this object (setvalue, applyvalues, parameters, lists), "
        "timestamped from now; the current state of every object becomes its first block. Stop with 'stop'.",
        MIN_FUNCTION {
            begin_capture(now_ms());
            return {};
        } };

    message<> clear{ this, "clear", "Discard the captured timeline and reset every object's parameters.",
        MIN_FUNCTION {
            m_capturing = false;
            for (auto& slot : m_slots) {
                slot.blocks.clear();
                slot.state = admio::object_state();
                slot.ramp_ms = static_cast<double>(ramp);
            }
            m_capture_last = 0.0;
            return {};
        } };

    message<> name{ this, "name", "Name an object for writing: 'name N symbol' (N is 1-based).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "name needs an object number and a name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 1 || static_cast<size_t>(index) > m_slots.size()) {
                cerr << "name: object number out of range 1.." << m_slots.size() << endl;
                return {};
            }
            m_slots[static_cast<size_t>(index - 1)].name = std::string(args[1]);
            return {};
        } };

    message<> write{ this, "write",
        "Write a BW64 file with the captured timeline as ADM metadata: 'write out.wav in.wav' copies the audio of "
        "in.wav (one track per object, recorded with mc.sfrecord~ for example) into out.wav with the chna and axml chunks.",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_symbol(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "write needs the output path and the path of the recorded audio" << endl;
                return {};
            }
            const std::string out = resolve_path(std::string(args[0]), false);
            const std::string in = resolve_path(std::string(args[1]), true);
            try {
                auto reader = bw64::readFile(in);
                const double length = static_cast<double>(reader->numberOfFrames()) / reader->sampleRate();
                const size_t objects = std::min<size_t>(m_slots.size(), reader->channels());
                if (reader->channels() < m_slots.size()) {
                    cerr << "the audio file has " << reader->channels() << " channels; only the first " << objects
                         << " objects are written" << endl;
                }
                std::vector<bw64::AudioId> chna_ids;
                auto doc = admio::build_document(programme_name(), captured_objects(objects, length), length, chna_ids);
                reader.reset();
                const uint64_t frames = admio::write_file(out, in, doc, chna_ids);
                out_info.send("written", symbol(out), static_cast<int>(objects), static_cast<double>(frames));
            }
            catch (const std::exception& e) {
                cerr << "write: " << e.what() << endl;
            }
            return {};
        } };

    message<> writexml{ this, "writexml",
        "Write the captured timeline as an ADM XML file: 'writexml out.xml [length seconds]' (for inspection, or "
        "for tools that take the metadata separately).",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "writexml needs an output path" << endl;
                return {};
            }
            double length = m_capture_last;
            if (args.size() > 1 && atom_is_numeric(args[1])) {
                length = std::max(0.0, static_cast<double>(args[1]));
            }
            try {
                std::vector<bw64::AudioId> chna_ids;
                auto doc = admio::build_document(programme_name(), captured_objects(m_slots.size(), length), length, chna_ids);
                std::ofstream file(resolve_path(std::string(args[0]), false));
                if (!file) {
                    throw std::runtime_error("cannot open the file for writing");
                }
                file << admio::to_xml(doc);
                out_info.send("written", args[0], static_cast<int>(m_slots.size()));
            }
            catch (const std::exception& e) {
                cerr << "writexml: " << e.what() << endl;
            }
            return {};
        } };

    message<> setvalue{ this, "setvalue",
        "Captured object metadata, in the mc.ear.objects~ format: 'setvalue N parameter values...' (N is 1-based; 0 "
        "sets all objects). Parameters: azimuth elevation distance x y z cartesian position width height depth gain "
        "diffuse channellock channellock_distance divergence divergence_range screenref screenedgelock_h "
        "screenedgelock_v ramp.",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "setvalue needs an object number (1-based, 0 for all) and a parameter name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 0 || static_cast<size_t>(index) > m_slots.size()) {
                cerr << "setvalue: object number out of range 0.." << m_slots.size() << endl;
                return {};
            }
            const std::string parameter = args[1];
            const atoms values(args.begin() + 2, args.end());
            if (index == 0) {
                capture_all(parameter, values);
            }
            else {
                capture_one(static_cast<size_t>(index - 1), parameter, values);
            }
            return {};
        } };

    message<> applyvalues{ this, "applyvalues",
        "Captured object metadata: 'applyvalues parameter v1 v2 v3 ...' spreads values over the objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "applyvalues needs a parameter name followed by one value per object" << endl;
                return {};
            }
            const std::string parameter = args[0];
            const size_t n = std::min(args.size() - 1, m_slots.size());
            for (size_t i = 0; i < n; ++i) {
                capture_one(i, parameter, atoms{ args[i + 1] });
            }
            return {};
        } };

    message<> anything{ this, "anything", "Captured object metadata: any parameter sent as a message applies to all objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                return {};
            }
            capture_all(std::string(args[0]), atoms(args.begin() + 1, args.end()));
            return {};
        } };

    message<> list{ this, "list", "Captured object metadata: a list sets the position of all objects.",
        MIN_FUNCTION {
            capture_all("position", args);
            return {};
        } };

    // ------------------------------------------------------------------
    // transport timer
    // ------------------------------------------------------------------

    timer<> m_timer{ this, MIN_FUNCTION {
        on_tick();
        return {};
    } };

    // ------------------------------------------------------------------
    // state access (tests)
    // ------------------------------------------------------------------

    bool loaded() const
    {
        return m_loaded;
    }

    const admio::selection& items() const
    {
        return m_items;
    }

    const admio::file_info& info() const
    {
        return m_file.info;
    }

    double position() const
    {
        return m_position;
    }

    /// capture a message at an explicit scheduler time (ms), for tests and
    /// for hosts that timestamp messages themselves
    void capture_at(double scheduler_ms, const std::string& parameter, long index, const atoms& values)
    {
        m_capture_time_override = scheduler_ms;
        if (index == 0) {
            capture_all(parameter, values);
        }
        else {
            capture_one(static_cast<size_t>(index - 1), parameter, values);
        }
        m_capture_time_override = -1.0;
    }

    void begin_capture_at(double scheduler_ms)
    {
        begin_capture(scheduler_ms);
    }

    const std::vector<admio::captured_block>& captured(size_t i) const
    {
        return m_slots[i].blocks;
    }

    bool running() const
    {
        return m_running;
    }

    /// the transport step the timer performs
    void on_tick()
    {
        advance(true);
    }

    /// one transport step without the scheduler (tests): the next block
    /// boundary is emitted as the timer would
    void step()
    {
        if (!m_loaded) {
            return;
        }
        m_running = true;
        advance(false);
    }

private:
    double m_capture_time_override{ -1.0 };

    static bool same_time(double a, double b)
    {
        return std::abs(a - b) < 1e-6;
    }

    /// A file name as the patcher gives it (absolute, Max-style
    /// "Macintosh HD:/..." or, for reading, a name on Max's search path) as
    /// a native absolute path; the name itself when nothing resolves it.
    static std::string resolve_path(const std::string& name, bool for_reading)
    {
        if (for_reading) {
            try {
                path p(name);
                if (p) {
                    const std::string full = p;
                    if (!full.empty()) {
                        return full;
                    }
                }
            }
            catch (...) {
                // not on the search path: try it as an absolute path below
            }
        }
        char native[c74::max::MAX_PATH_CHARS] = { 0 };
        if (c74::max::path_nameconform(name.c_str(), native, c74::max::PATH_STYLE_NATIVE, c74::max::PATH_TYPE_ABSOLUTE) == 0
            && native[0] != 0) {
            return native;
        }
        return name;
    }

    std::string programme_name() const
    {
        const symbol name = programmename;
        return name;
    }

    double now_ms() const
    {
        if (m_capture_time_override >= 0.0) {
            return m_capture_time_override;
        }
        return static_cast<double>(c74::max::gettime());
    }

    /// where the transport ends: the end of the audio, or of the last block
    /// when the metadata outlasts the audio
    double end_time() const
    {
        double end = m_file.info.samplerate ? static_cast<double>(m_file.info.frames) / m_file.info.samplerate : 0.0;
        for (const auto& item : m_items.objects) {
            if (!item.blocks.empty() && std::isfinite(item.blocks.back().end)) {
                end = std::max(end, item.blocks.back().end);
            }
        }
        return end;
    }

    // ---- reading -----------------------------------------------------

    void load(const std::string& path)
    {
        m_running = false;
        m_timer.stop();
        try {
            m_file = admio::load_file(path);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            m_loaded = false;
            return;
        }
        m_loaded = true;
        m_position = 0.0;
        select();
    }

    void select()
    {
        try {
            m_items = admio::select_items(m_file, m_programme);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            m_loaded = false;
            return;
        }
        m_emitted.assign(m_items.objects.size(), -1);
        report();
        send_static();
        emit_objects(m_position, true);
    }

    void report()
    {
        if (!m_loaded) {
            out_info.send("file", symbol("none"));
            return;
        }
        const auto& info = m_file.info;
        out_info.send("file", symbol(info.path), static_cast<int>(info.samplerate), static_cast<int>(info.channels),
                      static_cast<double>(info.frames));
        out_info.send("programmes", static_cast<int>(m_items.programmes.size()));
        for (size_t i = 0; i < m_items.programmes.size(); ++i) {
            out_info.send("programme", static_cast<int>(i + 1), symbol(m_items.programmes[i]),
                          static_cast<int>(i) == m_items.programme ? 1 : 0);
        }
        out_info.send("objects", static_cast<int>(m_items.objects.size()));
        for (size_t i = 0; i < m_items.objects.size(); ++i) {
            const auto& item = m_items.objects[i];
            out_info.send("object", static_cast<int>(i + 1), item.track + 1, symbol(item.name), static_cast<int>(item.blocks.size()));
        }
        out_info.send("direct", static_cast<int>(m_items.direct.size()));
        for (size_t i = 0; i < m_items.direct.size(); ++i) {
            const auto& item = m_items.direct[i];
            atoms a{ symbol("directspeakers"), static_cast<int>(i + 1), item.track + 1, symbol(item.name) };
            for (const auto& label : item.labels) {
                a.push_back(symbol(label));
            }
            out_info.send(a);
        }
        out_info.send("hoa", static_cast<int>(m_items.hoa.size()));
        for (size_t i = 0; i < m_items.hoa.size(); ++i) {
            const auto& item = m_items.hoa[i];
            atoms a{ symbol("scene"), static_cast<int>(i + 1), symbol(item.name), item.order, symbol(item.normalization) };
            for (const int track : item.tracks) {
                a.push_back(track + 1);
            }
            out_info.send(a);
        }
        for (const auto& warning : m_items.warnings) {
            out_info.send("warning", symbol(warning));
        }
    }

    /// track lists and the static metadata of beds and scenes
    void send_static()
    {
        atoms tracks{ symbol("tracks") };
        for (const auto& item : m_items.objects) {
            tracks.push_back(item.track + 1);
        }
        out_objects.send(tracks);

        tracks = atoms{ symbol("tracks") };
        for (const auto& item : m_items.direct) {
            tracks.push_back(item.track + 1);
        }
        out_direct.send(tracks);
        for (size_t i = 0; i < m_items.direct.size(); ++i) {
            const auto& item = m_items.direct[i];
            const int n = static_cast<int>(i + 1);
            atoms labels{ symbol("setvalue"), n, symbol("speakerlabel") };
            for (const auto& label : item.labels) {
                labels.push_back(symbol(label));
            }
            out_direct.send(labels);
            if (item.has_position) {
                out_direct.send("setvalue", n, symbol("position"), item.azimuth, item.elevation, item.distance);
            }
            atoms bounds{ symbol("setvalue"), n, symbol("bounds") };
            for (const double b : item.bounds) {
                bounds.push_back(b);
            }
            out_direct.send(bounds);
            out_direct.send("setvalue", n, symbol("lfe"), item.lfe ? 1 : 0);
            out_direct.send("setvalue", n, symbol("packformat"), symbol(item.pack_id.empty() ? "none" : item.pack_id));
        }

        if (!m_items.hoa.empty()) {
            const auto& item = m_items.hoa.front();
            tracks = atoms{ symbol("tracks") };
            for (const int track : item.tracks) {
                tracks.push_back(track + 1);
            }
            out_hoa.send("order", item.order);
            out_hoa.send("normalization", symbol(item.normalization));
            out_hoa.send(tracks);
            if (m_items.hoa.size() > 1) {
                cerr << "the file has " << m_items.hoa.size() << " HOA scenes; only the first is sent to the hoa outlet" << endl;
            }
        }
        else {
            out_hoa.send("tracks");
        }
    }

    void reset_emitted()
    {
        std::fill(m_emitted.begin(), m_emitted.end(), -1);
    }

    /// emit the blocks active at `time` for every Objects item whose block
    /// changed since the last emission; `jump` forces an immediate change
    void emit_objects(double time, bool jump)
    {
        for (size_t i = 0; i < m_items.objects.size(); ++i) {
            const auto& item = m_items.objects[i];
            const int current = admio::block_at(item, time);
            if (current < 0 || current == m_emitted[i]) {
                continue;
            }
            const auto& block = item.blocks[static_cast<size_t>(current)];
            const bool was_previous = m_emitted[i] == current - 1;
            const double ramp_seconds = (jump || !was_previous) ? 0.0 : block.interp;
            send_block(static_cast<int>(i + 1), block.state, ramp_seconds);
            m_emitted[i] = current;
        }
    }

    void send_block(int n, const admio::object_state& s, double ramp_seconds)
    {
        out_objects.send("setvalue", n, symbol("ramp"), ramp_seconds * 1000.0);
        out_objects.send("setvalue", n, symbol("cartesian"), s.cartesian ? 1 : 0);
        if (s.cartesian) {
            out_objects.send("setvalue", n, symbol("position"), s.x, s.y, s.z);
        }
        else {
            out_objects.send("setvalue", n, symbol("position"), s.azimuth, s.elevation, s.distance);
        }
        out_objects.send("setvalue", n, symbol("width"), s.width);
        out_objects.send("setvalue", n, symbol("height"), s.height);
        out_objects.send("setvalue", n, symbol("depth"), s.depth);
        out_objects.send("setvalue", n, symbol("gain"), s.gain);
        out_objects.send("setvalue", n, symbol("diffuse"), s.diffuse);
        out_objects.send("setvalue", n, symbol("channellock"), s.channellock ? 1 : 0);
        out_objects.send("setvalue", n, symbol("channellock_distance"), s.channellock_distance);
        out_objects.send("setvalue", n, symbol("divergence"), s.divergence);
        out_objects.send("setvalue", n, symbol("divergence_range"), s.divergence_range);
        out_objects.send("setvalue", n, symbol("screenref"), s.screenref ? 1 : 0);
        out_objects.send("setvalue", n, symbol("screenedgelock_h"), symbol(s.screenedgelock_h));
        out_objects.send("setvalue", n, symbol("screenedgelock_v"), symbol(s.screenedgelock_v));
    }

    /// the next block start after `time` over all Objects items, or the file
    /// end when nothing is left; +inf when past the end
    double next_boundary(double time) const
    {
        double next = std::numeric_limits<double>::infinity();
        for (const auto& item : m_items.objects) {
            for (const auto& block : item.blocks) {
                if (block.start > time + 1e-6 && block.start < next) {
                    next = block.start;
                }
            }
        }
        const double length = end_time();
        if (length > time + 1e-6 && length < next) {
            next = length;
        }
        return next;
    }

    /// emit the next block boundary; `arm` schedules the one after it
    void advance(bool arm)
    {
        if (!m_running || !m_loaded) {
            return;
        }
        const double next = next_boundary(m_position);
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_position * 1000.0);
            return;
        }
        m_position = next;
        emit_objects(m_position, false);
        out_info.send("position", m_position * 1000.0);
        if (same_time(m_position, end_time())) {
            m_running = false;
            out_info.send("end", m_position * 1000.0);
            return;
        }
        if (arm) {
            schedule_next();
        }
    }

    void schedule_next()
    {
        const double next = next_boundary(m_position);
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_position * 1000.0);
            return;
        }
        m_timer.delay((next - m_position) * 1000.0);
    }

    // ---- capturing ---------------------------------------------------

    void resize_slots(size_t n)
    {
        const size_t old = m_slots.size();
        m_slots.resize(n);
        for (size_t i = old; i < n; ++i) {
            m_slots[i].name = "object " + std::to_string(i + 1);
            m_slots[i].ramp_ms = static_cast<double>(ramp);
        }
    }

    void begin_capture(double scheduler_ms)
    {
        m_capture_origin = scheduler_ms;
        m_capture_last = 0.0;
        m_capturing = true;
        for (auto& slot : m_slots) {
            slot.blocks.clear();
            slot.blocks.push_back({ 0.0, 0.0, slot.state });
        }
    }

    void record_change(size_t i)
    {
        if (!m_capturing) {
            return;
        }
        capture_slot& slot = m_slots[i];
        const double t = std::max(0.0, (now_ms() - m_capture_origin) / 1000.0);
        m_capture_last = std::max(m_capture_last, t);
        if (!slot.blocks.empty() && same_time(slot.blocks.back().time, t)) {
            slot.blocks.back().state = slot.state;    // several parameters at the same time: one block
            slot.blocks.back().ramp = slot.ramp_ms / 1000.0;
            return;
        }
        slot.blocks.push_back({ t, slot.ramp_ms / 1000.0, slot.state });
    }

    void capture_one(size_t i, const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (apply_parameter(m_slots[i], parameter, values, error)) {
            if (parameter != "ramp") {
                record_change(i);
            }
        }
        else {
            cerr << "object " << (i + 1) << ": " << error << endl;
        }
    }

    void capture_all(const std::string& parameter, const atoms& values)
    {
        for (size_t i = 0; i < m_slots.size(); ++i) {
            std::string error;
            if (!apply_parameter(m_slots[i], parameter, values, error)) {
                if (i == 0) {
                    cerr << error << endl;
                }
                return;
            }
            if (parameter != "ramp") {
                record_change(i);
            }
        }
    }

    static bool number_at(const atoms& values, size_t i, double& out, std::string& error, const char* what)
    {
        if (values.size() <= i || !atom_is_numeric(values[i]) || !std::isfinite(static_cast<double>(values[i]))) {
            error = std::string(what) + " needs a finite number";
            return false;
        }
        out = static_cast<double>(values[i]);
        return true;
    }

    /// apply one mc.ear.objects~ parameter to a captured object's state
    static bool apply_parameter(capture_slot& slot, const std::string& name, const atoms& values, std::string& error)
    {
        admio::object_state& s = slot.state;
        double v = 0.0;
        if (name == "azimuth") return number_at(values, 0, s.azimuth, error, "azimuth");
        if (name == "elevation") return number_at(values, 0, s.elevation, error, "elevation");
        if (name == "distance") return number_at(values, 0, s.distance, error, "distance");
        if (name == "x") return number_at(values, 0, s.x, error, "x");
        if (name == "y") return number_at(values, 0, s.y, error, "y");
        if (name == "z") return number_at(values, 0, s.z, error, "z");
        if (name == "width") return number_at(values, 0, s.width, error, "width");
        if (name == "height") return number_at(values, 0, s.height, error, "height");
        if (name == "depth") return number_at(values, 0, s.depth, error, "depth");
        if (name == "gain") return number_at(values, 0, s.gain, error, "gain");
        if (name == "diffuse") return number_at(values, 0, s.diffuse, error, "diffuse");
        if (name == "channellock_distance") return number_at(values, 0, s.channellock_distance, error, "channellock_distance");
        if (name == "divergence") return number_at(values, 0, s.divergence, error, "divergence");
        if (name == "divergence_range") return number_at(values, 0, s.divergence_range, error, "divergence_range");
        if (name == "ramp") {
            if (!number_at(values, 0, v, error, "ramp")) return false;
            slot.ramp_ms = std::max(0.0, v);
            return true;
        }
        if (name == "cartesian" || name == "channellock" || name == "screenref") {
            if (!number_at(values, 0, v, error, name.c_str())) return false;
            const bool flag = v != 0.0;
            if (name == "cartesian") s.cartesian = flag;
            else if (name == "channellock") s.channellock = flag;
            else s.screenref = flag;
            return true;
        }
        if (name == "screenedgelock_h" || name == "screenedgelock_v") {
            if (values.empty() || !atom_is_symbol(values[0])) {
                error = name + " needs a symbol";
                return false;
            }
            const std::string edge = values[0];
            if (name == "screenedgelock_h") {
                if (edge != "none" && edge != "left" && edge != "right") { error = "screenedgelock_h must be none, left or right"; return false; }
                s.screenedgelock_h = edge;
            }
            else {
                if (edge != "none" && edge != "top" && edge != "bottom") { error = "screenedgelock_v must be none, top or bottom"; return false; }
                s.screenedgelock_v = edge;
            }
            return true;
        }
        if (name == "position" || name == "list") {
            if (values.size() < 2) {
                error = "position needs at least 2 numbers: azimuth elevation [distance] or x y z";
                return false;
            }
            double a = 0.0, b = 0.0, c = s.cartesian ? s.z : s.distance;
            if (!number_at(values, 0, a, error, "position") || !number_at(values, 1, b, error, "position")) return false;
            if (values.size() > 2 && !number_at(values, 2, c, error, "position")) return false;
            if (s.cartesian) { s.x = a; s.y = b; s.z = c; }
            else { s.azimuth = a; s.elevation = b; s.distance = c; }
            return true;
        }
        if (name == "zone") {
            error = "zone exclusion cannot be written (not supported by libadm); ignored";
            return false;
        }
        error = "unknown parameter: " + name;
        return false;
    }

    std::vector<admio::captured_object> captured_objects(size_t count, double length) const
    {
        std::vector<admio::captured_object> objects;
        for (size_t i = 0; i < count && i < m_slots.size(); ++i) {
            admio::captured_object o;
            o.name = m_slots[i].name;
            o.blocks = m_slots[i].blocks;
            if (o.blocks.empty()) {
                o.blocks.push_back({ 0.0, 0.0, m_slots[i].state });    // never captured: a static object
            }
            objects.push_back(std::move(o));
        }
        (void)length;
        return objects;
    }
};
