/// @file
/// @brief   ear.adm: read and write ADM (BW64) files alongside the renderers.
///          Reading resolves the file's rendering items like the EAR and
///          emits the renderer messages for a time position; writing captures
///          the object metadata messages a patch sends to the renderers and
///          combines them with recorded audio into a BW64 file with ADM.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_adm_capture.h"
#include "../shared/ear_max_adm_player.h"

#include <cmath>
#include <fstream>
#include <limits>
#include <memory>

using namespace earmax;

class ear_adm : public object<ear_adm> {
public:
    MIN_DESCRIPTION{ "Read and write ADM files (BW64 with ADM metadata) alongside the renderers. 'read' loads a file's "
                     "ADM, reports its rendering items and which file tracks carry them, and 'time', 'start' or 'seek' "
                     "emit the metadata of the Objects items as mc.ear.objects~ messages with the EAR's interpolation "
                     "rules (a 'setvalue N ramp' message precedes each block). DirectSpeakers beds and HOA scenes are "
                     "emitted as mc.ear.direct~ and mc.ear.hoa~ messages when the file is read. For writing, 'record' "
                     "captures the object messages sent to this object, 'direct ...' and 'hoa ...' take the bed and "
                     "scene metadata in the mc.ear.direct~ and mc.ear.hoa~ formats (written after the objects' tracks), "
                     "and 'write' combines the captured metadata with an audio file recorded by mc.sfrecord~ into a "
                     "BW64 file with ADM metadata." };
    MIN_TAGS{ "spatial audio, ADM, files" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~, mc.ear.select~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    // reading: the file, its items and their emission live in the player
    // shared with mc.ear.play~; the transport (scheduler timing) is here
    admio::item_player m_player;
    bool m_running{ false };

    // capturing: the objects and their timelines live in the capture shared
    // with mc.ear.record~; the clock (Max's scheduler) is here
    admio::object_capture m_capture;
    double m_capture_origin{ 0.0 };    // scheduler time (ms) when the capture started
    admio::bed_capture m_bed;          // the DirectSpeakers channels after the objects (static)
    admio::scene_capture m_scene;      // the HOA scene after the bed (static)

public:
    inlet<> in_main{ this, "(read/time/start/stop/seek) play a file's metadata; (record/write/setvalue...) capture metadata" };
    outlet<> out_objects{ this, "(messages) for mc.ear.objects~: tracks, setvalue N ramp/parameters" };
    outlet<> out_direct{ this, "(messages) for mc.ear.direct~: tracks, setvalue N speakerlabel/position/lfe/packformat" };
    outlet<> out_hoa{ this, "(messages) for mc.ear.hoa~: tracks, order, normalization" };
    outlet<> out_info{ this, "(messages) file, programme, item and warning reports, position, end" };

    ear_adm(const atoms& args = {})
    {
        (void)args;
        m_capture.resize(static_cast<size_t>(static_cast<int>(chans)));
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<number> ramp{ this, "ramp", 10.0,
        description{ "Default interpolation time in milliseconds written for captured changes, as the renderer's "
                     "ramp attribute; 'setvalue N ramp ms' overrides it per object (a negative value returns to it)." },
        setter{ MIN_FUNCTION {
            const double ms = std::max(0.0, static_cast<double>(args[0]));
            m_capture.set_default_ramp(ms);
            return { ms };
        } } };

    attribute<int> chans{ this, "chans", 16,
        description{ "Number of objects captured for writing (one per audio track of the file written)." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(1, std::min(n, 1024));
            m_capture.resize(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<symbol> programmename{ this, "programmename", "libear-max",
        description{ "Name of the audioProgramme written." } };

    attribute<int> directchans{ this, "directchans", 0,
        description{ "Number of DirectSpeakers channels written as a bed on the tracks after the objects (0: no bed); "
                     "their metadata comes from 'direct' messages." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(0, std::min(n, 1024));
            m_bed.resize(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<int> hoaorder{ this, "hoaorder", -1,
        description{ "Ambisonic order of the HOA scene written on the (order+1)^2 tracks after the bed, in ACN order; "
                     "-1 for no scene. Also set by 'hoa order N'." },
        setter{ MIN_FUNCTION {
            std::string error;
            if (!m_scene.set_order(static_cast<int>(args[0]), error)) {
                cerr << "hoaorder: " << error << endl;
            }
            return { m_scene.scene().order };
        } } };

    attribute<symbol> hoanormalization{ this, "hoanormalization", "SN3D",
        description{ "Normalization of the HOA scene written: SN3D, N3D or FuMa. Also set by 'hoa normalization name'." },
        setter{ MIN_FUNCTION {
            std::string error;
            if (!m_scene.set_normalization(std::string(args[0]), error)) {
                cerr << "hoanormalization: " << error << endl;
            }
            return { symbol(m_scene.scene().normalization) };
        } } };

    // ------------------------------------------------------------------
    // reading
    // ------------------------------------------------------------------

    message<> read{ this, "read",
        "Read an ADM (BW64) file: 'read path'. Reports the file, its programmes and rendering items on the info outlet, "
        "sends the track lists and static metadata to the renderer outlets and emits the object metadata for time 0.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "read needs a file path" << endl;
                return {};
            }
            load(admio::resolve_path(std::string(args[0]), true));
            return {};
        } };

    message<> programme{ this, "programme",
        "Select the audioProgramme to render by index (1-based) when the file has several, and re-read the items.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "programme needs an index (1-based)" << endl;
                return {};
            }
            select_programme(std::max(0, static_cast<int>(static_cast<double>(args[0])) - 1));
            return {};
        } };

    message<> dump{ this, "dump", "Report the file, its programmes, rendering items and warnings on the info outlet.",
        MIN_FUNCTION {
            m_player.report(sinks());
            return {};
        } };

    message<> time{ this, "time",
        "Emit the object metadata for a time position in milliseconds ('time 1500'), as the renderer messages for the "
        "blocks active at that time. Only blocks that changed since the last emission are sent.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "time needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            if (ms < m_player.position() * 1000.0) {
                m_player.reset_emitted();    // going back in time: re-emit everything as a jump
            }
            m_player.set_position(ms / 1000.0);
            m_player.emit(m_player.position(), false, sinks());
            return {};
        } };

    message<> start{ this, "start",
        "Start the transport: emits the object metadata at every block boundary from the current position, on Max's "
        "scheduler, until the end of the file. Send 'start' to mc.sfplay~ at the same time to play the audio.",
        MIN_FUNCTION {
            if (!m_player.loaded()) {
                cerr << "no file read" << endl;
                return {};
            }
            m_running = true;
            m_player.reset_emitted();
            m_player.emit(m_player.position(), true, sinks());
            schedule_next();
            return {};
        } };

    message<> stop{ this, "stop", "Stop the transport (and a running capture).",
        MIN_FUNCTION {
            m_running = false;
            if (m_timer) {
                m_timer->stop();
            }
            if (m_capture.capturing()) {
                m_capture.end();
                m_bed.end();
                out_info.send("captured", static_cast<int>(m_capture.size()), m_capture.last_time() * 1000.0);
            }
            return {};
        } };

    message<> seek{ this, "seek", "Move the transport to a position in milliseconds ('seek 0' rewinds) and emit the metadata there.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "seek needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms)) {
                return {};
            }
            m_player.set_position(ms / 1000.0);
            m_player.reset_emitted();
            m_player.emit(m_player.position(), true, sinks());
            if (m_running) {
                schedule_next();
            }
            return {};
        } };

    // ------------------------------------------------------------------
    // writing
    // ------------------------------------------------------------------

    message<> record{ this, "record",
        "Start capturing the object messages sent to this object (setvalue, applyvalues, parameters, lists) and the "
        "bed's 'direct' changes, timestamped from now; the current state of every object and bed channel becomes its "
        "first block. Stop with 'stop'.",
        MIN_FUNCTION {
            begin_capture(now_ms());
            return {};
        } };

    message<> clear{ this, "clear", "Discard the captured timeline and reset every object's and bed channel's parameters.",
        MIN_FUNCTION {
            m_capture.clear();
            m_bed.clear();
            return {};
        } };

    message<> direct{ this, "direct",
        "Metadata of the bed written after the objects (see the directchans attribute), in the mc.ear.direct~ format: "
        "'direct setvalue N speakerlabel M+030' (N is 1-based; 0 sets all channels), 'direct setvalue N position az el "
        "[dist]', azimuth, elevation, distance, bounds, lfe, packformat, 'direct applyvalues parameter v1 v2 ...', "
        "'direct inputlayout 0+5+0' (labels, positions and LFE after a BS.2051 layout, written as a reference to the "
        "common definitions when the layout has one), 'direct name symbol' (the bed's audioObject name), or 'direct "
        "parameter values' for all channels. While 'record' runs, a change of a channel's labels, position or bounds "
        "is captured as a timed block (such a bed is written with its own channel formats). The 'tracks' message of a "
        "reading ear.adm or mc.ear.play~ is ignored, so their direct outlet can be fed to this message.",
        MIN_FUNCTION {
            std::string error;
            if (!admio::apply_direct_message(m_bed, args, capture_time(), error)) {
                cerr << error << endl;
            }
            return {};
        } };

    message<> hoa{ this, "hoa",
        "Metadata of the HOA scene written after the bed, in the mc.ear.hoa~ format: 'hoa order N' (the hoaorder "
        "attribute; -1 for no scene), 'hoa normalization SN3D|N3D|FuMa' and 'hoa name symbol'. The 'tracks' message "
        "of a reading ear.adm or mc.ear.play~ is ignored, so their hoa outlet can be fed to this message.",
        MIN_FUNCTION {
            if (!args.empty() && atom_is_symbol(args[0]) && args.size() > 1) {
                const std::string selector = args[0];
                if (selector == "order") {
                    hoaorder = static_cast<int>(static_cast<double>(args[1]));    // the attribute setter validates
                    return {};
                }
                if (selector == "normalization") {
                    hoanormalization = symbol(args[1]);
                    return {};
                }
            }
            std::string error;
            if (!admio::apply_hoa_message(m_scene, args, error)) {
                cerr << error << endl;
            }
            return {};
        } };

    message<> name{ this, "name", "Name an object for writing: 'name N symbol' (N is 1-based).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "name needs an object number and a name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 1 || !m_capture.set_name(static_cast<size_t>(index - 1), std::string(args[1]))) {
                cerr << "name: object number out of range 1.." << m_capture.size() << endl;
            }
            return {};
        } };

    message<> write{ this, "write",
        "Write a BW64 file with the captured metadata as ADM: 'write out.wav in.wav' copies the audio of in.wav "
        "(recorded with mc.sfrecord~ for example: one track per object, then the bed's channels, then the HOA "
        "components) into out.wav with the chna and axml chunks. Reports 'written path tracks frames'.",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_symbol(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "write needs the output path and the path of the recorded audio" << endl;
                return {};
            }
            const std::string out = admio::resolve_path(std::string(args[0]), false);
            const std::string in = admio::resolve_path(std::string(args[1]), true);
            try {
                auto reader = bw64::readFile(in);
                const double length = static_cast<double>(reader->numberOfFrames()) / reader->sampleRate();
                admio::captured_programme captured = captured_programme();
                if (reader->channels() < captured.channels()) {
                    cerr << "the audio file has " << reader->channels() << " channels but " << captured.channels()
                         << " are captured; only what fits is written (objects first, then the bed, then the scene)" << endl;
                    captured.limit(reader->channels());
                }
                std::vector<bw64::AudioId> chna_ids;
                auto doc = build(captured, length, chna_ids);
                reader.reset();
                const uint64_t frames = admio::write_file(out, in, doc, chna_ids);
                out_info.send("written", symbol(out), static_cast<int>(captured.channels()), static_cast<double>(frames));
            }
            catch (const std::exception& e) {
                cerr << "write: " << e.what() << endl;
            }
            return {};
        } };

    message<> writexml{ this, "writexml",
        "Write the captured metadata as an ADM XML file: 'writexml out.xml [length seconds]' (for inspection, or "
        "for tools that take the metadata separately).",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "writexml needs an output path" << endl;
                return {};
            }
            double length = m_capture.last_time();
            if (args.size() > 1 && atom_is_numeric(args[1])) {
                length = std::max(0.0, static_cast<double>(args[1]));
            }
            try {
                std::vector<bw64::AudioId> chna_ids;
                const admio::captured_programme captured = captured_programme();
                auto doc = build(captured, length, chna_ids);
                std::ofstream file(admio::resolve_path(std::string(args[0]), false));
                if (!file) {
                    throw std::runtime_error("cannot open the file for writing");
                }
                file << admio::to_xml(doc);
                out_info.send("written", args[0], static_cast<int>(captured.channels()));
            }
            catch (const std::exception& e) {
                cerr << "writexml: " << e.what() << endl;
            }
            return {};
        } };

    message<> setvalue{ this, "setvalue",
        "Captured object metadata, in the mc.ear.objects~ format: 'setvalue N parameter values...' (N is 1-based; 0 "
        "sets all objects). Parameters: azimuth elevation distance x y z cartesian position width height depth gain "
        "diffuse channellock channellock_distance divergence divergence_range screenref screenedgelock_h "
        "screenedgelock_v, and ramp (the interpolation time written for the next changes of that object; negative "
        "returns to the ramp attribute).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "setvalue needs an object number (1-based, 0 for all) and a parameter name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 0 || static_cast<size_t>(index) > m_capture.size()) {
                cerr << "setvalue: object number out of range 0.." << m_capture.size() << endl;
                return {};
            }
            const std::string parameter = args[1];
            const atoms values(args.begin() + 2, args.end());
            if (index == 0) {
                capture_all(parameter, values);
            }
            else {
                capture_one(static_cast<size_t>(index - 1), parameter, values);
            }
            return {};
        } };

    message<> applyvalues{ this, "applyvalues",
        "Captured object metadata: 'applyvalues parameter v1 v2 v3 ...' spreads values over the objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "applyvalues needs a parameter name followed by one value per object" << endl;
                return {};
            }
            const std::string parameter = args[0];
            const size_t n = std::min(args.size() - 1, m_capture.size());
            for (size_t i = 0; i < n; ++i) {
                capture_one(i, parameter, atoms{ args[i + 1] });
            }
            return {};
        } };

    message<> anything{ this, "anything", "Captured object metadata: any parameter sent as a message applies to all objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                return {};
            }
            capture_all(std::string(args[0]), atoms(args.begin() + 1, args.end()));
            return {};
        } };

    message<> list{ this, "list", "Captured object metadata: a list sets the position of all objects.",
        MIN_FUNCTION {
            capture_all("position", args);
            return {};
        } };

    // ------------------------------------------------------------------
    // transport timer
    // ------------------------------------------------------------------

    // delivered on Max's main thread, like the messages that share the
    // transport state (the renderers' messages are deferred there anyway).
    // Created on first use: Min's mock kernel (the unit tests) starts a
    // thread for every clock before the clock's own mutexes exist, which
    // can abort the test binary; the tests step the transport without it.
    using transport_timer = timer<timer_options::defer_delivery>;
    std::unique_ptr<transport_timer> m_timer;

    transport_timer& transport()
    {
        if (!m_timer) {
            m_timer = std::make_unique<transport_timer>(this, MIN_FUNCTION {
                on_tick();
                return {};
            });
        }
        return *m_timer;
    }

    // ------------------------------------------------------------------
    // state access (tests)
    // ------------------------------------------------------------------

    bool loaded() const
    {
        return m_player.loaded();
    }

    const admio::selection& items() const
    {
        return m_player.items();
    }

    const admio::file_info& info() const
    {
        return m_player.info();
    }

    double position() const
    {
        return m_player.position();
    }

    /// capture a message at an explicit scheduler time (ms), for tests and
    /// for hosts that timestamp messages themselves
    void capture_at(double scheduler_ms, const std::string& parameter, long index, const atoms& values)
    {
        m_capture_time_override = scheduler_ms;
        if (index == 0) {
            capture_all(parameter, values);
        }
        else {
            capture_one(static_cast<size_t>(index - 1), parameter, values);
        }
        m_capture_time_override = -1.0;
    }

    void begin_capture_at(double scheduler_ms)
    {
        begin_capture(scheduler_ms);
    }

    /// send a 'direct' message as if at a scheduler time (tests)
    void direct_at(double scheduler_ms, const atoms& args)
    {
        m_capture_time_override = scheduler_ms;
        direct(args);
        m_capture_time_override = -1.0;
    }

    const std::vector<admio::captured_block>& captured(size_t i) const
    {
        return m_capture.blocks(i);
    }

    const admio::bed_capture& bed() const
    {
        return m_bed;
    }

    const admio::captured_scene& scene() const
    {
        return m_scene.scene();
    }

    bool running() const
    {
        return m_running;
    }

    /// the transport step the timer performs
    void on_tick()
    {
        advance(true);
    }

    /// one transport step without the scheduler (tests): the next block
    /// boundary is emitted as the timer would
    void step()
    {
        if (!m_player.loaded()) {
            return;
        }
        m_running = true;
        advance(false);
    }

private:
    double m_capture_time_override{ -1.0 };

    std::string programme_name() const
    {
        const symbol name = programmename;
        return name;
    }

    /// everything captured, as written: the objects, the bed, the scene
    admio::captured_programme captured_programme() const
    {
        admio::captured_programme p;
        p.name = programme_name();
        p.objects = m_capture.objects(m_capture.size());
        p.bed = m_bed.bed();
        p.scene = m_scene.scene();
        return p;
    }

    std::shared_ptr<adm::Document> build(const admio::captured_programme& captured, double length, std::vector<bw64::AudioId>& chna_ids)
    {
        std::vector<std::string> warnings;
        auto doc = admio::build_document(captured, length, chna_ids, warnings);
        for (const auto& w : warnings) {
            cerr << w << endl;
        }
        return doc;
    }

    double now_ms() const
    {
        if (m_capture_time_override >= 0.0) {
            return m_capture_time_override;
        }
        return static_cast<double>(c74::max::gettime());
    }

    /// where the transport ends: the end of the audio, or of the last block
    /// when the metadata outlasts the audio
    // ---- reading -----------------------------------------------------

    /// the outlets as the shared player sends to them
    admio::message_sinks sinks()
    {
        admio::message_sinks out;
        out.objects = [this](const atoms& a) { out_objects.send(a); };
        out.direct = [this](const atoms& a) { out_direct.send(a); };
        out.hoa = [this](const atoms& a) { out_hoa.send(a); };
        out.info = [this](const atoms& a) { out_info.send(a); };
        return out;
    }

    void load(const std::string& path)
    {
        m_running = false;
        if (m_timer) {
                m_timer->stop();
            }
        try {
            m_player.load(path);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            m_player.report(sinks());    // "file none": the previous file is gone too
            return;
        }
        announce();
    }

    void select_programme(int index)
    {
        if (!m_player.loaded()) {
            m_player.select(index);    // remembered for the next file
            return;
        }
        try {
            m_player.select(index);
        }
        catch (const std::exception& e) {
            cerr << "read: " << e.what() << endl;
            return;
        }
        announce();
    }

    /// report the file and send the static metadata and the blocks active
    /// at the current position
    void announce()
    {
        const auto out = sinks();
        m_player.report(out);
        m_player.send_static(out, true);
        m_player.emit(m_player.position(), true, out);
    }

    /// emit the next block boundary; `arm` schedules the one after it
    void advance(bool arm)
    {
        if (!m_running || !m_player.loaded()) {
            return;
        }
        const double next = m_player.next_boundary(m_player.position());
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_player.position() * 1000.0);
            return;
        }
        m_player.set_position(next);
        m_player.emit(next, false, sinks());
        out_info.send("position", next * 1000.0);
        if (admio::item_player::same_time(next, m_player.end_time())) {
            m_running = false;
            out_info.send("end", next * 1000.0);
            return;
        }
        if (arm) {
            schedule_next();
        }
    }

    void schedule_next()
    {
        const double next = m_player.next_boundary(m_player.position());
        if (std::isinf(next)) {
            m_running = false;
            out_info.send("end", m_player.position() * 1000.0);
            return;
        }
        transport().delay((next - m_player.position()) * 1000.0);
    }

    // ---- capturing ---------------------------------------------------

    void begin_capture(double scheduler_ms)
    {
        m_capture_origin = scheduler_ms;
        m_capture.begin();
        m_bed.begin();
    }

    /// the time of a change on the capture's clock: seconds since 'record'
    double capture_time() const
    {
        return m_capture.capturing() ? std::max(0.0, (now_ms() - m_capture_origin) / 1000.0) : 0.0;
    }

    void capture_one(size_t i, const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (!m_capture.apply_one(i, parameter, values, capture_time(), error)) {
            cerr << "object " << (i + 1) << ": " << error << endl;
        }
    }

    void capture_all(const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (!m_capture.apply_all(parameter, values, capture_time(), error)) {
            cerr << error << endl;
        }
    }
};
