/// @file
/// @brief   mc.ear.encode~: encode audio objects into an ambisonic scene (ADM
///          HOA) with the EAR's spherical harmonic conventions. A drop-in
///          counterpart of mc.ear.objects~ whose output is ambisonic components
///          instead of loudspeaker signals.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_dsp.h"
#include "../shared/ear_max_hoa.h"
#include "../shared/ear_max_mc.h"

#include "ear/conversion.hpp"

#include <cmath>

using namespace earmax;

class mc_ear_encode_tilde : public object<mc_ear_encode_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Encode audio objects into an ambisonic scene (ADM HOA) with the spherical harmonic conventions "
                     "of the EAR (ITU-R BS.2076), with multichannel signal input and output. Every channel of the "
                     "input is an object positioned with the same messages and parameters as mc.ear.objects~; the "
                     "output carries the summed ambisonic components in ACN order, (order+1)^2 channels, ready for "
                     "mc.ear.hoa~ or any AmbiX decoder. Only the position (polar or cartesian) and the gain of an "
                     "object affect the encoding; the other object parameters are accepted but ignored." };
    MIN_TAGS{ "spatial audio, ADM, ambisonics, audio, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.objects~, mc.ear.hoa~, ear.objects" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    struct object_slot {
        object_metadata meta;
        std::vector<float> gains;    // one gain per ambisonic component
        double ramp_ms{ -1.0 };      // per-object interpolation time; negative = the ramp attribute
    };

    int m_order{ 1 };
    hoa::normalization m_normalization{ hoa::normalization::SN3D };
    std::vector<object_slot> m_objects;
    std::vector<float> m_silence;
    long m_reported_overflow{ 0 };
    bus_renderer m_bus;

public:
    inlet<> in_main{ this, "(multichannelsignal) object audio, one channel per object; (setvalue/applyvalues/parameters) metadata" };
    outlet<> out_main{ this, "(multichannelsignal) ambisonic components in ACN order", "multichannelsignal" };

    mc_ear_encode_tilde(const atoms& args = {})
    {
        if (!args.empty() && atom_is_numeric(args[0])) {
            set_order(static_cast<int>(static_cast<double>(args[0])));
        }
        resize_objects(static_cast<size_t>(static_cast<int>(chans)));
        update_all();
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<int> order{ this, "order", 1,
        description{ "Ambisonic order of the scene, 0 to 8 (3 with FuMa normalization); can also be given as argument. "
                     "The output has (order+1)^2 channels in ACN order; a new channel count takes effect when the "
                     "audio is restarted." },
        setter{ MIN_FUNCTION {
            return { set_order(static_cast<int>(args[0])) };
        } } };

    attribute<symbol> normalization{ this, "normalization", "SN3D",
        description{ "Normalization of the ambisonic components: SN3D (the ADM default, also AmbiX), N3D or FuMa "
                     "(up to order 3)." },
        setter{ MIN_FUNCTION {
            const std::string name = args[0];
            hoa::normalization kind = m_normalization;
            if (!hoa::normalization_from_name(name, kind)) {
                cerr << "normalization must be SN3D, N3D or FuMa" << endl;
                return { symbol(hoa::normalization_name(m_normalization)) };
            }
            if (m_order > hoa::max_order(kind)) {
                cerr << name << " normalization is only defined up to order " << hoa::max_order(kind)
                     << "; lower the order first" << endl;
                return { symbol(hoa::normalization_name(m_normalization)) };
            }
            m_normalization = kind;
            update_all();
            return args;
        } } };

    attribute<int> chans{ this, "chans", 16,
        description{ "Number of objects (input channels) allocated. It grows by itself when the input signal carries more channels, or a setvalue "
                     "or applyvalues addresses a higher one, up to 1024; new objects take effect when the audio is "
                     "restarted." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(1, std::min(n, static_cast<int>(k_max_mc_inputs)));
            resize_objects(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<number> ramp{ this, "ramp", 10.0,
        description{ "Gain interpolation time in milliseconds when a position or gain changes." },
        setter{ MIN_FUNCTION {
            const double ms = std::max(0.0, static_cast<double>(args[0]));
            m_bus.set_ramp_ms(ms);
            return { ms };
        } } };

    // ------------------------------------------------------------------
    // messages
    // ------------------------------------------------------------------

    message<> setvalue{ this, "setvalue",
        "Set a parameter of one object: 'setvalue N parameter values...' (N is 1-based; 0 sets all objects). "
        "Parameters that affect the encoding: azimuth elevation distance x y z cartesian gain position; the other "
        "mc.ear.objects~ parameters are accepted but ignored; ramp sets the interpolation time in milliseconds of the next "
        "changes of that object (negative returns to the ramp attribute).",
        MIN_FUNCTION {
            long index = 0;
            if (!parse_mc_index(args, k_max_mc_inputs, index, [this](const std::string& m) { cerr << m << endl; })) {
                return {};
            }
            if (args.size() < 2 || !atom_is_symbol(args[1])) {
                cerr << "setvalue needs a parameter name after the input number" << endl;
                return {};
            }
            ensure_inputs(static_cast<size_t>(index));
            const std::string name = args[1];
            const atoms rest(args.begin() + 2, args.end());
            if (index == 0) {
                apply_all(name, rest);
            }
            else {
                apply_one(static_cast<size_t>(index - 1), name, rest);
            }
            return {};
        } };

    message<> applyvalues{ this, "applyvalues",
        "Spread values over the objects: 'applyvalues azimuth 0 90 -90' sets the azimuth of object 1 to 0, "
        "object 2 to 90 and object 3 to -90.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "applyvalues needs a parameter name followed by one value per object" << endl;
                return {};
            }
            const std::string name = args[0];
            ensure_inputs(args.size() - 1);
            const size_t n = std::min(args.size() - 1, m_objects.size());
            for (size_t i = 0; i < n; ++i) {
                apply_one(i, name, atoms{ args[i + 1] });
            }
            return {};
        } };

    message<> anything{ this, "anything",
        "Any object parameter sent as a message, such as 'azimuth 30' or 'gain 0.5', is applied to all objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                return {};
            }
            const std::string name = args[0];
            apply_all(name, atoms(args.begin() + 1, args.end()));
            return {};
        } };

    message<> list{ this, "list", "Set the position of all objects: azimuth elevation and optional distance (polar) or x y z (cartesian).",
        MIN_FUNCTION {
            apply_all("position", args);
            return {};
        } };

    message<> components{ this, "components",
        "Post the ambisonic components of the output channels (ACN index, order and degree) to the Max console.",
        MIN_FUNCTION {
            std::string text;
            for (size_t i = 0; i < component_count(); ++i) {
                int n = 0, m = 0;
                hoa::from_acn(static_cast<int>(i), n, m);
                text += std::to_string(i + 1) + ":(" + std::to_string(n) + "," + std::to_string(m) + ") ";
            }
            cout << "order " << m_order << " " << hoa::normalization_name(m_normalization) << ": " << text << endl;
            return {};
        } };

    message<> dspsetup{ this, "dspsetup",
        MIN_FUNCTION {
            m_bus.configure(component_count(), m_objects.size(), static_cast<size_t>(vector_size()), samplerate());
            for (size_t i = 0; i < m_objects.size(); ++i) {
                m_bus.set_gains_now(i, m_objects[i].gains, m_silence);
            }
            return {};
        } };

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_encode_tilde>(c);
            return {};
        } };

    // ------------------------------------------------------------------
    // multichannel plumbing (see ear_max_mc.h)
    // ------------------------------------------------------------------

    long mc_output_channels(long) const
    {
        return static_cast<long>(component_count());
    }

    long mc_input_changed(long, long channels)
    {
        // the allocation follows the input signal, as Max's mc objects do
        ensure_inputs(static_cast<size_t>(std::max(0L, channels)));
        if (channels > static_cast<long>(m_objects.size()) && channels != m_reported_overflow) {
            m_reported_overflow = channels;
            cerr << "input has " << channels << " channels but at most " << m_objects.size()
                 << " objects can be allocated; extra channels are ignored" << endl;
        }
        return 0;    // the output channel count only changes with the order, at the next DSP start
    }

    // ------------------------------------------------------------------
    // audio
    // ------------------------------------------------------------------

    void operator()(audio_bundle input, audio_bundle output)
    {
        m_bus.process(input.samples(), static_cast<size_t>(input.channel_count()), output.samples(),
                      static_cast<size_t>(output.channel_count()), static_cast<size_t>(input.frame_count()));
    }

    // ------------------------------------------------------------------
    // state
    // ------------------------------------------------------------------

    /// number of ambisonic components (output channels) for the current order
    size_t component_count() const
    {
        return hoa::component_count(m_order);
    }

    size_t object_count() const
    {
        return m_objects.size();
    }

    const object_metadata& metadata(size_t i) const
    {
        return m_objects[i].meta;
    }

    /// encoding gains of object `i`, one per component
    const std::vector<float>& gains(size_t i) const
    {
        return m_objects[i].gains;
    }

    int current_order() const
    {
        return m_order;
    }

private:
    int set_order(int n)
    {
        const int limit = hoa::max_order(m_normalization);
        if (n < 0 || n > limit) {
            cerr << "order must be between 0 and " << limit << " with " << hoa::normalization_name(m_normalization)
                 << " normalization" << endl;
            n = std::max(0, std::min(n, limit));
        }
        m_order = n;
        m_silence.assign(component_count(), 0.0f);
        update_all();
        return n;
    }

    /// Allocate objects up to n when a message or the input signal addresses
    /// more than there are: the metadata takes effect at once, the audio
    /// at the next DSP start, as after a change of the chans attribute.
    void ensure_inputs(size_t n)
    {
        n = std::min(n, k_max_mc_inputs);
        if (n <= m_objects.size()) {
            return;
        }
        cout << "chans raised from " << m_objects.size() << " to " << n
             << "; the new objects take effect when the audio is restarted" << endl;
        chans = static_cast<int>(n);    // the setter allocates
    }

    void resize_objects(size_t n)
    {
        const size_t old = m_objects.size();
        m_objects.resize(n);
        for (size_t i = old; i < n; ++i) {
            update(i);
        }
    }

    void update_all()
    {
        for (size_t i = 0; i < m_objects.size(); ++i) {
            update(i);
        }
    }

    /// recalculate the encoding gains of object i and hand them to the audio thread
    void update(size_t i)
    {
        object_slot& slot = m_objects[i];
        const object_metadata& meta = slot.meta;

        double azimuth = meta.azimuth;
        double elevation = meta.elevation;
        if (meta.cartesian) {
            // the ADM conversion of a cartesian position to polar (BS.2127 section 10)
            const ear::PolarPosition polar = ear::conversion::pointCartToPolar(ear::CartesianPosition(meta.x, meta.y, meta.z));
            azimuth = polar.azimuth;
            elevation = polar.elevation;
        }
        constexpr double k_pi = 3.14159265358979323846;
        const double az = azimuth * k_pi / 180.0;
        const double el = elevation * k_pi / 180.0;

        const size_t n_components = component_count();
        slot.gains.assign(n_components, 0.0f);
        for (size_t k = 0; k < n_components; ++k) {
            int n = 0, m = 0;
            hoa::from_acn(static_cast<int>(k), n, m);
            slot.gains[k] = static_cast<float>(meta.otm.gain * hoa::sph_harm(n, m, az, el, m_normalization));
        }
        if (initialized()) {
            m_bus.set_targets(i, slot.gains, m_silence, slot.ramp_ms);
        }
    }

    /// 'ramp' as a per-object parameter: the interpolation time of the next
    /// changes of this object (ear.adm sends it with every block); a negative
    /// value returns to the ramp attribute
    bool apply_ramp(size_t i, const atoms& values)
    {
        if (values.empty() || !atom_is_numeric(values[0]) || !std::isfinite(static_cast<double>(values[0]))) {
            cerr << "object " << (i + 1) << ": ramp needs a time in milliseconds" << endl;
            return false;
        }
        m_objects[i].ramp_ms = static_cast<double>(values[0]);
        return true;
    }

    void apply_one(size_t i, const std::string& name, const atoms& values)
    {
        if (name == "ramp") {
            apply_ramp(i, values);
            return;
        }
        if (m_objects[i].meta.apply(name, values, [this, i](const std::string& m) {
                cerr << "object " << (i + 1) << ": " << m << endl;
            })) {
            update(i);
        }
    }

    void apply_all(const std::string& name, const atoms& values)
    {
        if (name == "ramp") {
            for (size_t i = 0; i < m_objects.size() && apply_ramp(i, values); ++i) {
            }
            return;
        }
        for (size_t i = 0; i < m_objects.size(); ++i) {
            const bool ok = m_objects[i].meta.apply(name, values, [this, i](const std::string& m) {
                if (i == 0) {
                    cerr << m << endl;
                }
            });
            if (ok) {
                update(i);
            }
            else if (i == 0) {
                return;    // the same error would repeat for every object
            }
        }
    }
};
