/// @file
/// @brief   mc.ear.play~: play an ADM (BW64) file, audio and metadata together.
///          The audio is streamed from disk by a reader thread (ear_max_stream.h)
///          and comes out on three multichannel outlets, one per renderer, with
///          the file's tracks already routed: the Objects tracks, the
///          DirectSpeakers tracks and the HOA components. The Objects metadata
///          is emitted from the audio clock (ear_max_adm_player.h), so audio
///          and metadata cannot drift apart as they can with two transports.
///          A file at another sample rate is converted to the audio's by the
///          reader thread.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_adm_player.h"
#include "../shared/ear_max_mc.h"
#include "../shared/ear_max_stream.h"

#include <atomic>
#include <chrono>
#include <cmath>
#include <thread>

using namespace earmax;

class mc_ear_play_tilde : public object<mc_ear_play_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Play an ADM file (BW64 with ADM metadata): the audio is streamed from disk and comes out on three "
                     "multichannel outlets with the file's tracks routed for mc.ear.objects~, mc.ear.direct~ and "
                     "mc.ear.hoa~, and the metadata comes out of three message outlets for the same renderers, timed by "
                     "the audio itself (each Objects block is emitted with the EAR's interpolation rules as 'setvalue N "
                     "ramp' followed by its parameters). 'open' reads the file and reports its rendering items on the "
                     "info outlet; 'start' (or 1) plays from the beginning, 'stop' (or 0), 'pause', 'resume' and 'seek' "
                     "control the transport. The output channel counts follow the file when the audio is restarted. "
                     "Files larger than 4 GB (RF64/BW64) play, and a file at another sample rate is converted to the "
                     "audio's as it streams." };
    MIN_TAGS{ "spatial audio, ADM, files, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "ear.adm, mc.ear.objects~, mc.ear.direct~, mc.ear.hoa~, mc.sfplay~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    static constexpr size_t k_outlets = 3;    // objects, direct, hoa signal outlets

    admio::item_player m_player;    // the file's items and their emission (main thread)
    admio::bw64_stream m_stream;    // the audio, streamed from disk (reader thread), pulled by the audio thread
    std::atomic<bool> m_playing{ false };
    std::atomic<uint64_t> m_next_boundary{ admio::bw64_stream::k_no_frame };    // file frame of the next metadata change
    long m_dsp_counts[k_outlets]{ 1, 1, 1 };    // channels Max allocated per signal outlet at the last DSP start
    std::vector<double*> m_out_ptrs;            // the output channel pointers for the pull (sized at dspsetup)
    double m_samplerate{ 48000.0 };
    long m_vector{ 64 };
    bool m_dsp_started{ false };

public:
    inlet<> in_main{ this, "(open/start/stop/pause/resume/seek) transport; (int) 1 starts, 0 stops" };
    outlet<> out_objects_sig{ this, "(multichannelsignal) the Objects tracks, for mc.ear.objects~", "multichannelsignal" };
    outlet<> out_direct_sig{ this, "(multichannelsignal) the DirectSpeakers tracks, for mc.ear.direct~", "multichannelsignal" };
    outlet<> out_hoa_sig{ this, "(multichannelsignal) the HOA components in ACN order, for mc.ear.hoa~", "multichannelsignal" };
    outlet<> out_objects{ this, "(messages) for mc.ear.objects~: setvalue N ramp/parameters, timed by the audio" };
    outlet<> out_direct{ this, "(messages) for mc.ear.direct~: setvalue N speakerlabel/position/bounds/lfe/packformat" };
    outlet<> out_hoa{ this, "(messages) for mc.ear.hoa~: order, normalization" };
    outlet<> out_info{ this, "(messages) file, programme, item and warning reports, position, end" };

    mc_ear_play_tilde(const atoms& args = {})
    {
        (void)args;
        m_stream.set_output_rate(static_cast<uint32_t>(std::lround(samplerate())));
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<bool> loop{ this, "loop", false,
        description{ "Loop the file: the playback continues from the start when it reaches the end, and the metadata "
                     "starts over with it." },
        setter{ MIN_FUNCTION {
            const bool on = static_cast<bool>(args[0]);
            m_stream.set_loop(on);
            return { on };
        } } };

    // ------------------------------------------------------------------
    // messages
    // ------------------------------------------------------------------

    message<> open{ this, "open",
        "Open an ADM (BW64) file: 'open path'. Reports the file, its programmes and rendering items on the info outlet, "
        "sends the static bed and scene metadata to the renderer outlets and emits the object metadata for time 0. "
        "The signal outlets take the file's channel counts when the audio is restarted.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "open needs a file path" << endl;
                return {};
            }
            open_file(admio::resolve_path(std::string(args[0]), true));
            return {};
        } };

    message<> start{ this, "start", "Play from the beginning (the metadata starts over too).",
        MIN_FUNCTION {
            if (!m_player.loaded()) {
                cerr << "no file open" << endl;
                return {};
            }
            locate(0.0);
            m_playing.store(true, std::memory_order_release);
            return {};
        } };

    message<> stop{ this, "stop", "Stop playing; 'start' plays from the beginning again.",
        MIN_FUNCTION {
            m_playing.store(false, std::memory_order_release);
            return {};
        } };

    message<> pause{ this, "pause", "Stop playing at the current position; 'resume' continues from there.",
        MIN_FUNCTION {
            m_playing.store(false, std::memory_order_release);
            return {};
        } };

    message<> resume{ this, "resume", "Continue playing from the current position.",
        MIN_FUNCTION {
            if (!m_player.loaded()) {
                cerr << "no file open" << endl;
                return {};
            }
            m_playing.store(true, std::memory_order_release);
            return {};
        } };

    message<> seek{ this, "seek", "Move to a position in milliseconds ('seek 0' rewinds) and emit the metadata there; playing continues if it was.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "seek needs a position in milliseconds" << endl;
                return {};
            }
            const double ms = static_cast<double>(args[0]);
            if (!std::isfinite(ms) || !m_player.loaded()) {
                return {};
            }
            locate(std::max(0.0, ms) / 1000.0);
            return {};
        } };

    message<> number{ this, "number", "1 plays from the beginning, 0 stops (as mc.sfplay~).",
        MIN_FUNCTION {
            if (static_cast<double>(args[0]) != 0.0) {
                start();
            }
            else {
                stop();
            }
            return {};
        } };

    message<> programme{ this, "programme",
        "Select the audioProgramme to render by index (1-based) when the file has several, and route the file again.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_numeric(args[0])) {
                cerr << "programme needs an index (1-based)" << endl;
                return {};
            }
            const int index = std::max(0, static_cast<int>(static_cast<double>(args[0])) - 1);
            if (!m_player.loaded()) {
                m_player.select(index);    // remembered for the next file
                return {};
            }
            try {
                m_player.select(index);
            }
            catch (const std::exception& e) {
                cerr << "programme: " << e.what() << endl;
                return {};
            }
            route();
            announce();
            return {};
        } };

    message<> dump{ this, "dump", "Report the file, its programmes, rendering items and warnings on the info outlet.",
        MIN_FUNCTION {
            m_player.report(sinks());
            return {};
        } };

    message<> position{ this, "position", "Report the playback position in milliseconds on the info outlet.",
        MIN_FUNCTION {
            out_info.send("position", current_time() * 1000.0);
            return {};
        } };

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_play_tilde>(c);
            return {};
        } };

    message<> dspsetup{ this, "dspsetup",
        MIN_FUNCTION {
            m_samplerate = samplerate();
            m_vector = static_cast<long>(vector_size());
            m_dsp_started = true;
            m_out_ptrs.assign(static_cast<size_t>(m_dsp_counts[0] + m_dsp_counts[1] + m_dsp_counts[2]), nullptr);
            route();
            m_stream.set_output_rate(static_cast<uint32_t>(std::lround(m_samplerate)));
            check_samplerate();
            return {};
        } };

    // ------------------------------------------------------------------
    // multichannel outlets
    // ------------------------------------------------------------------

    /// the channel count of a signal outlet: the file's items, one channel
    /// each (at least one); Max asks when the audio starts
    long mc_output_channels(long outlet)
    {
        if (outlet < 0 || outlet >= static_cast<long>(k_outlets)) {
            return 1;
        }
        const long count = static_cast<long>(std::max<size_t>(1, item_count(static_cast<size_t>(outlet))));
        m_dsp_counts[outlet] = count;
        return count;
    }

    long mc_input_changed(long, long)
    {
        return 0;
    }

    // ------------------------------------------------------------------
    // audio
    // ------------------------------------------------------------------

    void operator()(audio_bundle input, audio_bundle output)
    {
        (void)input;
        const long frames = output.frame_count();
        const long channels = output.channel_count();
        if (!m_playing.load(std::memory_order_acquire)) {
            silence(output, 0);
            return;
        }
        const long usable = std::min(channels, static_cast<long>(m_out_ptrs.size()));
        for (long ch = 0; ch < usable; ++ch) {
            m_out_ptrs[static_cast<size_t>(ch)] = output.samples(static_cast<size_t>(ch));
        }
        const uint64_t before = m_stream.play_frame();
        const long delivered = m_stream.pull(m_out_ptrs.data(), usable, frames);
        silence(output, delivered);
        for (long ch = usable; ch < channels; ++ch) {
            std::fill(output.samples(static_cast<size_t>(ch)), output.samples(static_cast<size_t>(ch)) + frames, 0.0);
        }

        // wake the main thread when a metadata change is due within the
        // next vector, when the playback wrapped or ended
        const uint64_t after = m_stream.play_frame();
        const uint64_t next = m_next_boundary.load(std::memory_order_acquire);
        const bool ended = m_stream.ready() && m_stream.ended();    // not a stale end while a seek is pending
        if (after < before || ended || (next != admio::bw64_stream::k_no_frame && after + file_frames(frames) >= next)) {
            m_queue.set();
        }
    }

    // ------------------------------------------------------------------
    // state access (tests)
    // ------------------------------------------------------------------

    bool loaded() const
    {
        return m_player.loaded();
    }

    const admio::selection& items() const
    {
        return m_player.items();
    }

    const admio::item_player& player() const
    {
        return m_player;
    }

    bool playing() const
    {
        return m_playing.load();
    }

    /// the playback position in seconds, from the audio thread's frame
    double current_time() const
    {
        const uint32_t sr = m_stream.samplerate();
        return sr ? static_cast<double>(m_stream.play_frame()) / sr : 0.0;
    }

    /// wait for the reader thread to have the audio ready (tests)
    bool wait_ready(int timeout_ms)
    {
        const auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);
        while (!m_stream.ready()) {
            if (std::chrono::steady_clock::now() > deadline) {
                return false;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        return true;
    }

    /// run the main-thread work the audio thread queued (tests: the mock
    /// kernel has no queue)
    void flush()
    {
        on_queue();
    }

private:
    // the main-thread work the audio thread asks for: emitting the metadata
    // of the position reached, reporting the position, wraps and the end
    queue<> m_queue{ this, MIN_FUNCTION {
        on_queue();
        return {};
    } };

    admio::message_sinks sinks()
    {
        admio::message_sinks out;
        out.objects = [this](const atoms& a) { out_objects.send(a); };
        out.direct = [this](const atoms& a) { out_direct.send(a); };
        out.hoa = [this](const atoms& a) { out_hoa.send(a); };
        out.info = [this](const atoms& a) { out_info.send(a); };
        return out;
    }

    size_t item_count(size_t outlet) const
    {
        const auto& items = m_player.items();
        switch (outlet) {
            case 0: return items.objects.size();
            case 1: return items.direct.size();
            default: return items.hoa.empty() ? 0 : items.hoa.front().tracks.size();
        }
    }

    void silence(audio_bundle& output, long from_frame)
    {
        const long frames = output.frame_count();
        for (long ch = 0; ch < output.channel_count(); ++ch) {
            double* out = output.samples(static_cast<size_t>(ch));
            std::fill(out + from_frame, out + frames, 0.0);
        }
    }

    void open_file(const std::string& path)
    {
        m_playing.store(false, std::memory_order_release);
        m_next_boundary.store(admio::bw64_stream::k_no_frame);
        std::unique_ptr<bw64::Bw64Reader> reader;
        try {
            m_player.load(path);
            reader = bw64::readFile(path);
        }
        catch (const std::exception& e) {
            cerr << "open: " << e.what() << endl;
            m_player.unload();
            m_stream.close();
            m_player.report(sinks());
            return;
        }
        route();
        m_stream.open(std::move(reader));
        announce();
        check_samplerate();
    }

    /// the routing of the signal outlets' channels (as allocated at the
    /// last DSP start) to the file's tracks
    void route()
    {
        std::vector<int> routing;
        const auto& items = m_player.items();
        for (long i = 0; i < m_dsp_counts[0]; ++i) {
            routing.push_back(static_cast<size_t>(i) < items.objects.size() ? items.objects[static_cast<size_t>(i)].track : -1);
        }
        for (long i = 0; i < m_dsp_counts[1]; ++i) {
            routing.push_back(static_cast<size_t>(i) < items.direct.size() ? items.direct[static_cast<size_t>(i)].track : -1);
        }
        for (long i = 0; i < m_dsp_counts[2]; ++i) {
            const bool have = !items.hoa.empty() && static_cast<size_t>(i) < items.hoa.front().tracks.size();
            routing.push_back(have ? items.hoa.front().tracks[static_cast<size_t>(i)] : -1);
        }
        m_stream.set_routing(std::move(routing));
    }

    /// report the file and send the static metadata and the blocks active
    /// at the current position
    void announce()
    {
        const auto out = sinks();
        m_player.report(out);
        m_player.send_static(out, false);
        m_player.reset_emitted();
        m_player.emit(m_player.position(), true, out);
        arm(m_player.position());
    }

    void check_samplerate()
    {
        if (m_dsp_started && m_stream.has_file() && static_cast<double>(m_stream.samplerate()) != m_samplerate) {
            cout << "the file's sample rate (" << m_stream.samplerate() << " Hz) is converted to the audio's (" << m_samplerate
                 << " Hz)" << endl;
        }
    }

    /// the file frames `output_frames` output frames cover, rounded up
    uint64_t file_frames(long output_frames) const
    {
        return static_cast<uint64_t>(std::ceil(static_cast<double>(output_frames) * m_stream.ratio()));
    }

    /// move the playback and the metadata to `seconds`
    void locate(double seconds)
    {
        const uint32_t sr = m_stream.samplerate();
        const uint64_t frame = sr ? static_cast<uint64_t>(std::llround(seconds * sr)) : 0;
        m_stream.seek(frame);
        m_player.set_position(seconds);
        m_player.reset_emitted();
        m_player.emit(seconds, true, sinks());
        arm(seconds);
    }

    /// remember the next metadata change after `seconds` for the audio thread
    void arm(double seconds)
    {
        const double next = m_player.next_boundary(seconds);
        const uint32_t sr = m_stream.samplerate();
        if (std::isinf(next) || sr == 0) {
            m_next_boundary.store(admio::bw64_stream::k_no_frame, std::memory_order_release);
        }
        else {
            m_next_boundary.store(static_cast<uint64_t>(std::llround(next * sr)), std::memory_order_release);
        }
    }

    void on_queue()
    {
        if (!m_player.loaded()) {
            return;
        }
        const uint32_t sr = m_stream.samplerate();
        if (sr == 0) {
            return;
        }
        const double now = static_cast<double>(m_stream.play_frame()) / sr;
        const auto out = sinks();
        if (m_stream.take_wrapped()) {
            // looping: the metadata starts over as a jump
            m_player.reset_emitted();
            m_player.set_position(now);
            m_player.emit(now, true, out);
        }
        else {
            // the audio thread wakes us one vector ahead of a change: emit
            // it for the change's time so the renderer has it as the audio
            // gets there
            double time = now;
            const uint64_t next = m_next_boundary.load(std::memory_order_acquire);
            const uint64_t frame = m_stream.play_frame();
            if (next != admio::bw64_stream::k_no_frame && frame + file_frames(m_vector) >= next) {
                time = std::max(time, static_cast<double>(next) / sr);
            }
            m_player.set_position(time);
            m_player.emit(time, false, out);
        }
        out_info.send("position", m_player.position() * 1000.0);
        arm(m_player.position());

        const long underruns = m_stream.take_underruns();
        if (underruns > 0) {
            cerr << underruns << " signal vectors were not filled in time (disk too slow)" << endl;
        }
        if (m_stream.ready() && m_stream.ended() && m_playing.load(std::memory_order_acquire)) {
            m_playing.store(false, std::memory_order_release);
            out_info.send("end", m_player.position() * 1000.0);
        }
    }
};
