/// @file
/// @brief   ear.hoa: the decoding matrix of an ambisonic (ADM HOA) scene for a
///          loudspeaker layout, at control rate (the gains mc.ear.hoa~ applies).
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_hoa.h"

using namespace earmax;

class ear_hoa : public object<ear_hoa> {
public:
    MIN_DESCRIPTION{ "Calculate the decoding matrix of an ambisonic scene (ADM HOA) for a BS.2051 loudspeaker layout "
                     "with libear (ITU-R BS.2127): the gains mc.ear.hoa~ applies, as lists. The scene's components are "
                     "in ACN order (W Y Z X ... for first order), SN3D by default; the decoder is the EAR's AllRAD design "
                     "for the layout. Outputs one list per component (its channel number followed by a gain per "
                     "loudspeaker, ready for coll) and the whole matrix as matrix~ messages (input output gain); "
                     "both outlets send 'clear' first, so a smaller matrix leaves nothing of a larger one behind." };
    MIN_TAGS{ "spatial audio, ADM, ambisonics" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.hoa~, ear.objects, ear.direct" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

    static constexpr int k_max_order = 8;

    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    ear::Layout m_layout;
    std::unique_ptr<ear::GainCalculatorHOA> m_calc;
    std::vector<std::vector<float>> m_matrix;    ///< one vector of loudspeaker gains per ambisonic component
    int m_order{ 1 };
    std::string m_normalization{ "SN3D" };

    inlet<> in_main{ this, "(bang) calculate and output; (order, normalization, layout) attributes" };
    outlet<> out_rows{ this, "(clear, then list) per ambisonic component: its channel number, then a gain per loudspeaker" };
    outlet<> out_matrix{ this, "(clear, then list) the matrix as matrix~ messages: input output gain, one per entry" };
    outlet<> out_info{ this, "(anything) components, channels, positions, layouts" };

    ear_hoa(const atoms& args = {})
    {
        const std::string name = layout_from_args(args);
        if (name != m_layout.name() && !apply_layout(name)) {
            apply_layout(k_default_layout);
        }
        layout = symbol(m_layout.name());
        update();
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<symbol> layout{ this, "layout", k_default_layout,
        description{ "ITU-R BS.2051 loudspeaker layout name, such as 0+2+0, 0+5+0, 2+5+0, 4+5+0, 4+9+0, 9+10+3. "
                     "Send 'layouts' to list all names." },
        setter{ MIN_FUNCTION {
            const std::string name = args[0];
            if (!apply_layout(name)) {
                return { symbol(m_layout.name()) };
            }
            update();
            return args;
        } } };

    attribute<int> order{ this, "order", 1,
        description{ "Ambisonic order of the scene, 0 to 8: the scene has (order+1)^2 components in ACN order." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            if (n < 0 || n > k_max_order) {
                cerr << "order must be between 0 and " << k_max_order << endl;
                n = std::max(0, std::min(n, k_max_order));
            }
            m_order = n;
            update();
            return { n };
        } } };

    attribute<symbol> normalization{ this, "normalization", "SN3D",
        description{ "Normalization of the ambisonic components: SN3D (the ADM default, also AmbiX), N3D or FuMa." },
        setter{ MIN_FUNCTION {
            const std::string name = args[0];
            if (name != "SN3D" && name != "N3D" && name != "FuMa") {
                cerr << "normalization must be SN3D, N3D or FuMa" << endl;
                return { symbol(m_normalization) };
            }
            m_normalization = name;
            update();
            return args;
        } } };

    attribute<bool> autocalc{ this, "autocalc", true,
        description{ "Output the matrix whenever the layout, order or normalization changes. "
                     "When off, send a bang to output it. Nothing is output when the object is created: "
                     "send a bang (from loadbang) for the initial matrix." } };

    // ------------------------------------------------------------------
    // messages
    // ------------------------------------------------------------------

    message<> bang{ this, "bang", "Output the decoding matrix.",
        MIN_FUNCTION {
            calculate();
            return {};
        } };

    message<> components{ this, "components",
        "Output the order and degree of each component from the right outlet: 'components' followed by an "
        "order and degree pair per ACN channel.",
        MIN_FUNCTION {
            atoms pairs;
            for (size_t i = 0; i < input_count(); ++i) {
                int n = 0, m = 0;
                hoa::from_acn(static_cast<int>(i), n, m);
                pairs.push_back(n);
                pairs.push_back(m);
            }
            send_message(out_info, "components", pairs);
            return {};
        } };

    message<> channels{ this, "channels", "Output the channel names of the layout from the right outlet.",
        MIN_FUNCTION {
            send_channels(out_info, m_layout);
            return {};
        } };

    message<> positions{ this, "positions", "Output the nominal loudspeaker positions from the right outlet.",
        MIN_FUNCTION {
            send_positions(out_info, m_layout);
            return {};
        } };

    message<> layouts{ this, "layouts", "Output the names of all known layouts from the right outlet.",
        MIN_FUNCTION {
            send_layouts(out_info);
            return {};
        } };

    // ------------------------------------------------------------------
    // implementation
    // ------------------------------------------------------------------

    size_t channel_count() const
    {
        return m_layout.channels().size();
    }

    /// number of ambisonic components for the current order
    size_t input_count() const
    {
        return static_cast<size_t>((m_order + 1) * (m_order + 1));
    }

    /// loudspeaker gains of ambisonic component `i` (a column of the decoding matrix)
    const std::vector<float>& gains(size_t i) const
    {
        return m_matrix[i];
    }

    bool apply_layout(const std::string& name)
    {
        try {
            ear::Layout new_layout = ear::getLayout(name);
            m_layout = std::move(new_layout);
            m_calc = std::make_unique<ear::GainCalculatorHOA>(m_layout);
            return true;
        }
        catch (const std::exception& e) {
            cerr << e.what() << "; known layouts: " << layout_names_joined() << endl;
            return false;
        }
    }

    /// Recompute the decoding matrix for the current layout, order and
    /// normalization, and output it when autocalc is on.
    void update()
    {
        if (!m_calc) {
            return;
        }
        const size_t n_components = input_count();
        ear::HOATypeMetadata meta;
        meta.normalization = m_normalization;
        for (size_t i = 0; i < n_components; ++i) {
            int n = 0, m = 0;
            hoa::from_acn(static_cast<int>(i), n, m);
            meta.orders.push_back(n);
            meta.degrees.push_back(m);
        }
        std::vector<std::vector<float>> matrix(n_components, std::vector<float>(channel_count(), 0.0f));
        try {
            m_calc->calculate(meta, matrix, [this](const ear::Warning& warning) { cerr << warning.message << endl; });
        }
        catch (const std::exception& e) {
            cerr << e.what() << endl;
            return;
        }
        m_matrix = std::move(matrix);
        if (initialized() && autocalc) {
            calculate();
        }
    }

    /// Send the matrix: the matrix~ messages from the middle outlet first,
    /// then one list per component from the left outlet (right to left).
    /// Both start with 'clear', so that the entries or rows of a previous
    /// size (a higher order, a larger layout) are gone from matrix~ or coll.
    void calculate()
    {
        if (m_matrix.empty()) {
            return;
        }
        out_matrix.send(atoms{ symbol("clear") });
        out_rows.send(atoms{ symbol("clear") });
        for (size_t i = 0; i < m_matrix.size(); ++i) {
            for (size_t ch = 0; ch < m_matrix[i].size(); ++ch) {
                out_matrix.send(atoms{ static_cast<int>(i), static_cast<int>(ch), m_matrix[i][ch] });
            }
        }
        for (size_t i = 0; i < m_matrix.size(); ++i) {
            atoms row{ static_cast<int>(i + 1) };
            for (const float g : m_matrix[i]) {
                row.push_back(g);
            }
            out_rows.send(row);
        }
    }
};
