/// @file
/// @brief   mc.ear.record~: record an ADM (BW64) file, audio and metadata
///          together. The multichannel input is the objects' audio, one
///          channel per object; the object metadata is sent to the object in
///          the mc.ear.objects~ format while recording and captured against
///          the audio's own clock (the frames recorded so far), so the blocks
///          written are aligned with the samples they belong to. The audio is
///          written to disk by a writer thread (ear_max_sink.h) and the ADM
///          (chna and axml chunks) is added when the recording stops. Files
///          over 4 GB are written as RF64.
/// @license Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

#include "../shared/ear_max.h"
#include "../shared/ear_max_adm_capture.h"
#include "../shared/ear_max_adm_player.h"
#include "../shared/ear_max_mc.h"
#include "../shared/ear_max_sink.h"

#include <chrono>
#include <cmath>
#include <thread>

using namespace earmax;

class mc_ear_record_tilde : public object<mc_ear_record_tilde>, public mc_operator<> {
public:
    MIN_DESCRIPTION{ "Record an ADM file (BW64 with ADM metadata): the multichannel input is the objects' audio, one "
                     "channel per object (as fed to mc.ear.objects~), and the object metadata is sent to this object in "
                     "the same format as to mc.ear.objects~ (setvalue N parameter, applyvalues, lists) while it "
                     "records. Every change is written as an audioBlockFormat timed by the audio itself, with the ramp "
                     "in force as its interpolation, so audio and metadata cannot drift apart. 'open path' names the "
                     "file, 'start' (or 1) records from the current parameters, 'stop' (or 0) finishes the file and "
                     "reports it on the outlet. The number of channels written is the chans attribute: extra input "
                     "channels are ignored, missing ones are silent. Files over 4 GB are written as RF64." };
    MIN_TAGS{ "spatial audio, ADM, files, mc" };
    MIN_AUTHOR{ "tsln-lab" };
    MIN_RELATED{ "mc.ear.play~, ear.adm, mc.ear.objects~, mc.ear.encode~, mc.sfrecord~" };
    // the reference page is generated by the unit tests and shipped in docs/ (ear_max_doc.h)
    MIN_FLAGS{ documentation_flags::do_not_generate };

private:
    // ------------------------------------------------------------------
    // state (declared before the attributes: Min runs the attribute
    // setters while constructing the attributes, so this must exist first)
    // ------------------------------------------------------------------

    admio::object_capture m_capture;    // the objects' parameters and the captured timeline (main thread)
    admio::bw64_sink m_sink;            // the file (writer thread), fed by the audio thread
    std::string m_path;                 // the file to write, from 'open' or 'start'
    size_t m_recorded_channels{ 0 };    // channels of the file being recorded (chans at 'start')
    double m_samplerate{ 48000.0 };
    long m_vector{ 64 };
    long m_in_channels{ 0 };            // channels of the multichannel input, from Max
    long m_reported_overflow{ -1 };
    bool m_dsp_started{ false };

public:
    inlet<> in_main{ this, "(multichannelsignal) the objects' audio, one channel per object; (messages) open/start/stop, "
                           "setvalue/applyvalues/parameters as to mc.ear.objects~",
                     "multichannelsignal" };
    outlet<> out_info{ this, "(messages) recording, written, failed, position" };

    mc_ear_record_tilde(const atoms& args = {})
    {
        (void)args;
        m_capture.resize(static_cast<size_t>(static_cast<int>(chans)));
        m_sink.set_notify([this] { m_queue.set(); });
    }

    /// A recording still in progress is finished with the metadata captured
    /// so far (the writer thread is joined by the sink).
    ~mc_ear_record_tilde()
    {
        m_sink.set_notify({});    // the queue goes away with us
        if (m_sink.recording()) {
            m_capture.end();
            m_sink.finish(m_capture.objects(m_recorded_channels), programme_name());
        }
    }

    // ------------------------------------------------------------------
    // attributes
    // ------------------------------------------------------------------

    attribute<int> chans{ this, "chans", 16,
        description{ "Number of objects recorded: the channels of the file written, one per input channel (extra input "
                     "channels are ignored, missing ones are silent). Takes effect at the next 'start'." },
        setter{ MIN_FUNCTION {
            int n = static_cast<int>(args[0]);
            n = std::max(1, std::min(n, 1024));
            m_capture.resize(static_cast<size_t>(n));
            return { n };
        } } };

    attribute<c74::min::number> ramp{ this, "ramp", 10.0,
        description{ "Default interpolation time in milliseconds written for the changes, as the renderer's ramp "
                     "attribute; 'setvalue N ramp ms' overrides it per object (a negative value returns to it)." },
        setter{ MIN_FUNCTION {
            const double ms = std::max(0.0, static_cast<double>(args[0]));
            m_capture.set_default_ramp(ms);
            return { ms };
        } } };

    attribute<int> bitdepth{ this, "bitdepth", 24,
        description{ "Bit depth of the audio written: 16, 24 or 32 (integer PCM). Takes effect at the next 'start'." },
        setter{ MIN_FUNCTION {
            const int bits = static_cast<int>(args[0]);
            return { bits <= 16 ? 16 : bits >= 32 ? 32 : 24 };
        } } };

    attribute<symbol> programmename{ this, "programmename", "libear-max",
        description{ "Name of the audioProgramme written." } };

    // ------------------------------------------------------------------
    // transport
    // ------------------------------------------------------------------

    message<> open{ this, "open", "Name the file to record: 'open path' (an absolute path, or relative to the Max search path).",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "open needs a file path" << endl;
                return {};
            }
            m_path = admio::resolve_path(std::string(args[0]), false);
            return {};
        } };

    message<> start{ this, "start",
        "Start recording the file named by 'open' (or 'start path'): the audio is written from now, the objects' "
        "current parameters become their first blocks. Reports 'recording path' on the outlet.",
        MIN_FUNCTION {
            if (!args.empty() && atom_is_symbol(args[0])) {
                m_path = admio::resolve_path(std::string(args[0]), false);
            }
            begin();
            return {};
        } };

    message<> stop{ this, "stop",
        "Stop recording: the file is finished with the captured metadata and reported as 'written path objects "
        "length-ms' on the outlet (or 'failed path').",
        MIN_FUNCTION {
            end();
            return {};
        } };

    message<> number{ this, "number", "1 starts recording, 0 stops (as mc.sfrecord~).",
        MIN_FUNCTION {
            if (static_cast<double>(args[0]) != 0.0) {
                begin();
            }
            else {
                end();
            }
            return {};
        } };

    message<> position{ this, "position", "Report the recording's length so far in milliseconds on the outlet.",
        MIN_FUNCTION {
            out_info.send("position", current_time() * 1000.0);
            return {};
        } };

    // ------------------------------------------------------------------
    // metadata
    // ------------------------------------------------------------------

    message<> name{ this, "name", "Name an object in the file: 'name N symbol' (N is 1-based).",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "name needs an object number and a name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 1 || !m_capture.set_name(static_cast<size_t>(index - 1), std::string(args[1]))) {
                cerr << "name: object number out of range 1.." << m_capture.size() << endl;
            }
            return {};
        } };

    message<> setvalue{ this, "setvalue",
        "Object metadata, in the mc.ear.objects~ format: 'setvalue N parameter values...' (N is 1-based; 0 sets all "
        "objects). Parameters: azimuth elevation distance x y z cartesian position width height depth gain diffuse "
        "channellock channellock_distance divergence divergence_range screenref screenedgelock_h screenedgelock_v, "
        "and ramp (the interpolation time written for the next changes of that object; negative returns to the ramp "
        "attribute). While recording, a change becomes a block at the audio's current time.",
        MIN_FUNCTION {
            if (args.size() < 2 || !atom_is_numeric(args[0]) || !atom_is_symbol(args[1])) {
                cerr << "setvalue needs an object number (1-based, 0 for all) and a parameter name" << endl;
                return {};
            }
            const long index = static_cast<long>(static_cast<double>(args[0]));
            if (index < 0 || static_cast<size_t>(index) > m_capture.size()) {
                cerr << "setvalue: object number out of range 0.." << m_capture.size() << endl;
                return {};
            }
            const std::string parameter = args[1];
            const atoms values(args.begin() + 2, args.end());
            if (index == 0) {
                capture_all(parameter, values);
            }
            else {
                capture_one(static_cast<size_t>(index - 1), parameter, values);
            }
            return {};
        } };

    message<> applyvalues{ this, "applyvalues",
        "Object metadata: 'applyvalues parameter v1 v2 v3 ...' spreads values over the objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                cerr << "applyvalues needs a parameter name followed by one value per object" << endl;
                return {};
            }
            const std::string parameter = args[0];
            const size_t n = std::min(args.size() - 1, m_capture.size());
            for (size_t i = 0; i < n; ++i) {
                capture_one(i, parameter, atoms{ args[i + 1] });
            }
            return {};
        } };

    message<> anything{ this, "anything", "Object metadata: any parameter sent as a message applies to all objects.",
        MIN_FUNCTION {
            if (args.empty() || !atom_is_symbol(args[0])) {
                return {};
            }
            capture_all(std::string(args[0]), atoms(args.begin() + 1, args.end()));
            return {};
        } };

    message<> list{ this, "list", "Object metadata: a list sets the position of all objects.",
        MIN_FUNCTION {
            capture_all("position", args);
            return {};
        } };

    message<> clear{ this, "clear", "Reset every object's parameters and ramp (not while recording).",
        MIN_FUNCTION {
            if (m_sink.recording()) {
                cerr << "clear: still recording" << endl;
                return {};
            }
            m_capture.clear();
            return {};
        } };

    // ------------------------------------------------------------------
    // audio
    // ------------------------------------------------------------------

    message<> maxclass_setup{ this, "maxclass_setup",
        MIN_FUNCTION {
            c74::max::t_class* c = args[0];
            mc_register_methods<mc_ear_record_tilde>(c);
            return {};
        } };

    message<> dspsetup{ this, "dspsetup",
        MIN_FUNCTION {
            m_samplerate = samplerate();
            m_vector = static_cast<long>(vector_size());
            m_dsp_started = true;
            return {};
        } };

    /// no signal outlets
    long mc_output_channels(long)
    {
        return 1;
    }

    long mc_input_changed(long, long channels)
    {
        m_in_channels = channels;
        if (channels > static_cast<long>(m_capture.size()) && channels != m_reported_overflow) {
            m_reported_overflow = channels;
            cerr << "input has " << channels << " channels but only " << m_capture.size()
                 << " objects are recorded (see the chans attribute); extra channels are ignored" << endl;
        }
        return 0;    // there is no signal output
    }

    void operator()(audio_bundle input, audio_bundle output)
    {
        (void)output;
        if (!m_sink.recording()) {
            return;
        }
        m_sink.push(input.samples(), input.channel_count(), input.frame_count());
        if (m_sink.overruns() > 0) {
            m_queue.set();    // report the dropped vectors from the main thread
        }
    }

    // ------------------------------------------------------------------
    // state access (tests)
    // ------------------------------------------------------------------

    bool recording() const
    {
        return m_sink.recording();
    }

    /// the length recorded so far in seconds, from the audio thread's frames
    double current_time() const
    {
        return m_samplerate > 0.0 ? static_cast<double>(m_sink.frames_pushed()) / m_samplerate : 0.0;
    }

    const std::vector<admio::captured_block>& captured(size_t i) const
    {
        return m_capture.blocks(i);
    }

    /// wait for the writer thread to have finished the file (tests)
    bool wait_done(int timeout_ms)
    {
        const auto deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(timeout_ms);
        while (m_sink.busy()) {
            if (std::chrono::steady_clock::now() > deadline) {
                return false;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        return true;
    }

    /// run the main-thread work the other threads queued (tests: the mock
    /// kernel has no queue)
    void flush()
    {
        on_queue();
    }

private:
    // the main-thread work the writer and audio threads ask for: reporting
    // the finished file and dropped vectors
    queue<> m_queue{ this, MIN_FUNCTION {
        on_queue();
        return {};
    } };

    std::string programme_name() const
    {
        const symbol name = programmename;
        return name;
    }

    void begin()
    {
        if (m_sink.recording()) {
            cerr << "already recording" << endl;
            return;
        }
        if (m_sink.busy()) {
            cerr << "start: the previous file is still being finished" << endl;
            return;
        }
        if (m_path.empty()) {
            cerr << "no file: 'open path' first (or 'start path')" << endl;
            return;
        }
        if (!m_dsp_started) {
            cerr << "the audio is not running: the file will be empty until it is" << endl;
        }
        m_recorded_channels = m_capture.size();
        if (!m_sink.start(m_path, static_cast<uint16_t>(m_recorded_channels), static_cast<uint32_t>(std::lround(m_samplerate)),
                          static_cast<uint16_t>(static_cast<int>(bitdepth)))) {
            cerr << "start: could not start the recording" << endl;
            return;
        }
        m_capture.begin();
        out_info.send("recording", symbol(m_path));
    }

    void end()
    {
        if (!m_sink.recording()) {
            return;
        }
        m_capture.end();
        m_sink.finish(m_capture.objects(m_recorded_channels), programme_name());
    }

    /// the time of a change on the recording's clock: the audio recorded so far
    double capture_time() const
    {
        return m_sink.recording() ? current_time() : 0.0;
    }

    void capture_one(size_t i, const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (!m_capture.apply_one(i, parameter, values, capture_time(), error)) {
            cerr << "object " << (i + 1) << ": " << error << endl;
        }
    }

    void capture_all(const std::string& parameter, const atoms& values)
    {
        std::string error;
        if (!m_capture.apply_all(parameter, values, capture_time(), error)) {
            cerr << error << endl;
        }
    }

    void on_queue()
    {
        const long overruns = m_sink.take_overruns();
        if (overruns > 0) {
            cerr << overruns << " signal vectors were dropped (disk too slow)" << endl;
        }
        if (m_sink.has_outcome()) {
            const auto result = m_sink.take_outcome();
            if (result.ok) {
                const double ms = m_samplerate > 0.0 ? static_cast<double>(result.frames) / m_samplerate * 1000.0 : 0.0;
                out_info.send("written", symbol(result.path), static_cast<int>(result.objects), ms);
            }
            else {
                cerr << "write: " << result.error << endl;
                out_info.send("failed", symbol(result.path));
            }
        }
    }
};
